"""Unit tests for the EH-269 deterministic embedding-admission classifier.

Each never-embed rule is proven with a KNOWN-BAD input that must be
rejected (BUILD-CONTRACT §3: "a gate you add must catch a known-bad input"),
plus at least one admitted PROSE case per surface so the classifier is shown
to be a filter, not a blanket denial.
"""

from __future__ import annotations

import pytest

from epistemic_graph.ingestion.embedding_admission import (
    NEVER_EMBED_CLASSES,
    AdmissionVerdict,
    ContentClass,
    classify_sql_column,
    classify_unit,
    content_hash,
    dedupe_by_content_hash,
    is_sql_row_connector,
    sql_free_text_fields,
)

pytestmark = pytest.mark.no_engine

_PROSE_TEXT = "A hand-written paragraph describing what this record actually means."


def test_admission_verdict_admit_must_match_never_embed_classes() -> None:
    """The dataclass invariant is enforced, not just documented."""
    AdmissionVerdict(admit=True, content_class=ContentClass.PROSE, reason="ok")
    with pytest.raises(ValueError):
        AdmissionVerdict(admit=True, content_class=ContentClass.LOCKFILE, reason="bad")


@pytest.mark.parametrize(
    ("path", "expected"),
    [
        ("project/package-lock.json", ContentClass.LOCKFILE),
        ("api/service_pb2.py", ContentClass.GENERATED),
        ("static/app.min.js", ContentClass.MINIFIED),
        ("repo/vendor/lib/util.go", ContentClass.VENDORED),
        ("repo/node_modules/left-pad/index.js", ContentClass.VENDORED),
        ("assets/logo.png", ContentClass.BINARY),
    ],
)
def test_classify_by_path_rejects_known_bad_paths(
    path: str, expected: ContentClass
) -> None:
    verdict = classify_unit(connector="fixture", row={"path": path}, text=_PROSE_TEXT)
    assert verdict.content_class is expected
    assert verdict.admit is False


def test_classify_by_path_admits_ordinary_source_file() -> None:
    verdict = classify_unit(
        connector="fixture", row={"path": "src/handlers/order.py"}, text=_PROSE_TEXT
    )
    assert verdict.content_class is ContentClass.PROSE
    assert verdict.admit is True


def test_classify_by_content_marker_rejects_generated_header() -> None:
    text = "// Code generated by protoc-gen-go. DO NOT EDIT.\nsome body text here"
    verdict = classify_unit(connector="fixture", row={}, text=text)
    assert verdict.content_class is ContentClass.GENERATED
    assert verdict.admit is False


def test_classify_by_shape_rejects_too_short() -> None:
    verdict = classify_unit(connector="fixture", row={}, text="ok")
    assert verdict.content_class is ContentClass.TOO_SHORT
    assert verdict.admit is False


@pytest.mark.parametrize(
    "text",
    [
        "550e8400-e29b-41d4-a716-446655440000",  # UUID
        # SHA-256 hex digest.
        "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
        "https://example.invalid/path/to/thing",  # bare URL
        "person@example.invalid",  # email
        "2.14.7-release-candidate.1",  # semver
    ],
)
def test_classify_by_shape_rejects_known_bad_structured_tokens(text: str) -> None:
    verdict = classify_unit(connector="fixture", row={}, text=text)
    assert verdict.content_class is ContentClass.STRUCTURED_TOKEN
    assert verdict.admit is False


def test_classify_by_shape_admits_multiword_prose_above_the_floor() -> None:
    verdict = classify_unit(connector="fixture", row={}, text=_PROSE_TEXT)
    assert verdict.content_class is ContentClass.PROSE
    assert verdict.admit is True


def test_classify_by_shape_does_not_reject_ordinary_hyphenated_names() -> None:
    """A human-assigned single-word/hyphenated name is NOT a structured
    token (deliberately narrow — see the module docstring): it has no
    whitespace either, but rejecting it would be exactly the over-claim the
    design brief warns against (under-embedding is worse and harder to
    detect than over-embedding). This is the regression this lane's own
    ``test_ingest_envelopes_batch_auto_embeds_in_one_call`` caught when the
    rule was still a blanket "no whitespace" test."""
    verdict = classify_unit(connector="fixture", row={}, text="rec-object-1-longenough")
    assert verdict.content_class is ContentClass.PROSE
    assert verdict.admit is True


@pytest.mark.parametrize(
    ("name", "value", "expected"),
    [
        ("is_active", True, ContentClass.SQL_BOOLEAN),
        ("retry_count", 3, ContentClass.SQL_NUMERIC),
        ("amount_cents", 1999.5, ContentClass.SQL_NUMERIC),
        ("customer_id", "abc-123", ContentClass.SQL_FOREIGN_KEY),
        ("owner_fk", "abc-123", ContentClass.SQL_FOREIGN_KEY),
        ("created_at", "2026-09-01T12:00:00Z", ContentClass.SQL_TIMESTAMP),
        ("some_col", "2026-09-01", ContentClass.SQL_TIMESTAMP),
        ("status", "ACTIVE", ContentClass.SQL_ENUM),
        ("priority", "HIGH", ContentClass.SQL_ENUM),
    ],
)
def test_classify_sql_column_rejects_known_bad_columns(name, value, expected) -> None:
    assert classify_sql_column(name, value) is expected


def test_classify_sql_column_admits_free_text_varchar() -> None:
    assert (
        classify_sql_column("notes", "Customer called twice about the refund.") is None
    )


def test_is_sql_row_connector_only_cdc_today() -> None:
    assert is_sql_row_connector("cdc") is True
    assert is_sql_row_connector("servicenow") is False


def test_sql_free_text_fields_is_a_noop_for_non_sql_connectors() -> None:
    row = {"status": "ACTIVE", "notes": "free text", "id": "1"}
    assert (
        sql_free_text_fields(
            "servicenow", row, protected_fields=frozenset({"id", "type", "node_type"})
        )
        == row
    )


def test_sql_free_text_fields_drops_enum_fk_timestamp_string_columns_for_cdc() -> None:
    """String-typed enum/FK/timestamp columns are dropped. Non-string
    bool/numeric columns are left in place (harmless either way — the
    downstream fallback text-concatenation already only ever looks at
    ``isinstance(value, str)`` leaves, per ``derive_entity_text_snapshot``),
    which is why this filter only needs to police STRINGS."""
    row = {
        "id": "1",
        "customer_id": "cust-9",
        "status": "ACTIVE",
        "created_at": "2026-09-01T00:00:00Z",
        "is_deleted": False,
        "amount": 42,
        "notes": "the actual free text a human wrote",
    }
    filtered = sql_free_text_fields(
        "cdc", row, protected_fields=frozenset({"id", "type", "node_type"})
    )
    assert filtered == {
        "id": "1",
        "is_deleted": False,
        "amount": 42,
        "notes": "the actual free text a human wrote",
    }
    assert "customer_id" not in filtered
    assert "status" not in filtered
    assert "created_at" not in filtered


def test_sql_free_text_fields_never_strips_structural_or_priority_fields() -> None:
    """``type``/``node_type`` must survive filtering even though "type" is
    also an enum-name-hint substring — breaking node-type detection would be
    a correctness regression, not a savings."""
    row = {"id": "1", "type": "Order", "node_type": "Order", "status": "OPEN"}
    filtered = sql_free_text_fields(
        "cdc", row, protected_fields=frozenset({"id", "type", "node_type"})
    )
    assert filtered["type"] == "Order"
    assert filtered["node_type"] == "Order"
    assert "status" not in filtered


def test_sql_free_text_fields_uses_callers_protected_fields() -> None:
    row = {"status": "OPEN", "notes": "A detailed operator note"}
    assert (
        sql_free_text_fields("cdc", row, protected_fields=frozenset({"status"})) == row
    )
    assert sql_free_text_fields("cdc", row, protected_fields=frozenset()) == {
        "notes": "A detailed operator note"
    }


def test_dedupe_by_content_hash_collapses_exact_duplicates() -> None:
    items = [(0, "same text"), (1, "same text"), (2, "different text")]

    unique, alias = dedupe_by_content_hash(items)

    assert unique == [(0, "same text"), (2, "different text")]
    assert alias == {1: 0}


def test_dedupe_by_content_hash_known_bad_input_is_two_calls_without_it() -> None:
    """Prove the gate actually catches something: without dedupe, 5 identical
    texts would need 5 embed calls; with it, exactly 1 unique text remains."""
    items = [(i, "identical boilerplate paragraph") for i in range(5)]

    unique, alias = dedupe_by_content_hash(items)

    assert len(unique) == 1
    assert len(alias) == 4


def test_content_hash_is_deterministic() -> None:
    assert content_hash("abc") == content_hash("abc")
    assert content_hash("abc") != content_hash("abd")


def test_never_embed_classes_excludes_only_prose() -> None:
    all_classes = set(ContentClass)
    assert all_classes - NEVER_EMBED_CLASSES == {ContentClass.PROSE}
