"""Contract tests for the immutable Dupehound full-tree adapter.

These tests exercise manifest/report joins and command construction with
synthetic data. They deliberately do not invoke Dupehound, Git archive, or a
Cargo build; the release workflow is the scanner execution surface.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from contextlib import contextmanager
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
pytestmark = pytest.mark.no_engine


def _load_script():
    scripts = str(ROOT / "scripts")
    if scripts not in sys.path:
        sys.path.insert(0, scripts)
    name = "eg_dupehound_census_contract_test"
    spec = importlib.util.spec_from_file_location(
        name, ROOT / "scripts" / "check_dupehound_census.py"
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def census():
    return _load_script()


@pytest.fixture(scope="module")
def contract(census):
    return census.scanner_contract.load_contract(ROOT / "pyproject.toml")


def _entry(census, path: str, *, mode: str = "100644", object_sha: str = "a" * 40):
    return census.TreeEntry(path, mode, "blob", object_sha)


def test_scan_command_is_the_pinned_full_tree_profile(census, contract, tmp_path):
    command = census.scan_command("/opt/dupehound", tmp_path / "snapshot", contract)

    assert command[:11] == [
        "/opt/dupehound",
        "scan",
        str(tmp_path / "snapshot"),
        "--json",
        "--all",
        "--threshold",
        "0.85",
        "--min-tokens",
        "40",
        "--exclude-tests",
        "--no-default-excludes",
    ]
    assert "--include-tests" not in command
    assert "--include-classes" not in command
    exclusions = [
        value
        for index, value in enumerate(command)
        if index and command[index - 1] == "--exclude"
    ]
    assert exclusions == census.profile_exclusions(contract)


def test_tree_digest_binds_path_mode_and_blob(census):
    first = [
        _entry(census, "src/z.py", object_sha="b" * 40),
        _entry(census, "src/a.py"),
    ]
    second = list(reversed(first))
    assert census.tree_listing_digest(first) == census.tree_listing_digest(second)
    assert census.tree_listing_digest(first) != census.tree_listing_digest(
        [
            _entry(census, "src/z.py", mode="100755", object_sha="b" * 40),
            _entry(census, "src/a.py"),
        ]
    )


def test_classification_is_complete_and_precedence_is_explicit(census, contract):
    entries = [
        _entry(census, "src/main.py"),
        _entry(census, "tests/test_main.py"),
        _entry(census, ".github/check.py"),
        _entry(census, "generated/codec.py"),
        _entry(census, "src/auto.py"),
        _entry(census, "src/foo-generated.py"),
        _entry(census, "src/foo.generated.py"),
        _entry(census, "src/native.c++"),
        _entry(census, "src/uppercase.PY"),
        _entry(census, "src/huge-line.py"),
        _entry(census, "src/oversize.py"),
        _entry(census, "src/binary.py"),
        _entry(census, "README.txt"),
        _entry(census, "link.py", mode="120000", object_sha="c" * 40),
    ]
    contents = {
        "src/main.py": b"def main():\n    return 1\n",
        "tests/test_main.py": b"def test_main():\n    return 1\n",
        ".github/check.py": b"def check():\n    return 1\n",
        "generated/codec.py": b"def codec():\n    return 1\n",
        "src/auto.py": b"# @generated\ndef auto():\n    return 1\n",
        "src/foo-generated.py": b"def source_name():\n    return 1\n",
        "src/foo.generated.py": b"def generated_name():\n    return 1\n",
        "src/native.c++": b"int source_name() { return 1; }\n",
        "src/uppercase.PY": b"def native_case():\n    return 1\n",
        "src/huge-line.py": (b"# " + b"x" * 2100 + b"\n"),
        "src/oversize.py": b"# Code generated by a producer\n"
        + b"x" * (census.MAX_FILE_BYTES + 1),
        "src/binary.py": b"def bad():\n\xff\n",
        "README.txt": b"documentation\n",
    }

    result = census.classify_entries(entries, contents, contract)
    by_path = {entry.path: entry for entry in result}
    assert set(by_path) == {entry.path for entry in entries}
    assert by_path["src/main.py"].class_name == "production"
    contract_entry = _entry(census, "contract/methods.rs")
    nested_contract_entry = _entry(census, "crates/eg-types/src/contract/crypto.rs")
    contract_result = census.classify_entries(
        [contract_entry, nested_contract_entry],
        {
            "contract/methods.rs": b"generated\n",
            "crates/eg-types/src/contract/crypto.rs": b"fn digest_type() {}\n",
        },
        contract,
    )
    by_contract_path = {entry.path: entry for entry in contract_result}
    assert by_contract_path["contract/methods.rs"].class_name == "generated"
    assert (
        by_contract_path["crates/eg-types/src/contract/crypto.rs"].class_name
        == "production"
    )
    assert by_path["tests/test_main.py"].class_name == "test"
    assert by_path[".github/check.py"].class_name == "hidden"
    assert by_path["generated/codec.py"].class_name == "generated"
    assert by_path["src/auto.py"].reason == "content.generated_marker"
    assert by_path["src/foo-generated.py"].class_name == "production"
    assert by_path["src/foo.generated.py"].class_name == "generated"
    assert by_path["src/native.c++"].class_name == "production"
    assert by_path["src/native.c++"].language == "cpp"
    assert by_path["src/uppercase.PY"].class_name == "unsupported"
    assert by_path["src/huge-line.py"].class_name == "minified"
    assert by_path["src/oversize.py"].class_name == "oversize"
    assert by_path["src/binary.py"].class_name == "invalid_encoding"
    assert by_path["README.txt"].class_name == "unsupported"
    assert by_path["link.py"].class_name == "non_regular"


def test_profile_uses_native_hidden_and_generated_rules_without_invented_suffixes(
    census, contract
):
    profile = census.profile_definition(contract)
    assert profile["native_skip_rules"]["hidden_walker"] == "WalkBuilder.hidden(true)"
    assert "**/*-generated.*" not in profile["exclusions"]
    assert "**/*_generated.*" not in profile["exclusions"]
    assert ".c++" in profile["language_extensions"]["cpp"]
    assert ".c++" in census.universe_definition()["supported_suffixes"]
    assert profile["test_projection"]["finding_minimum_non_test_members"] == 2


def _native_report(snapshot: Path, *, files: int = 2) -> bytes:
    members = [
        {
            "file": str(snapshot / "src" / "a.py"),
            "name": "alpha",
            "start_line": 1,
            "end_line": 8,
            "lines": 8,
            "similarity": 1.0,
            "representative": True,
            "test": False,
        },
        {
            "file": str(snapshot / "src" / "b.py"),
            "name": "beta",
            "start_line": 2,
            "end_line": 9,
            "lines": 8,
            "similarity": 0.95,
            "representative": False,
            "test": False,
        },
    ]
    return json.dumps(
        {
            "schema_version": 1,
            "root": str(snapshot),
            "stats": {
                "files": files,
                "total_lines": 20,
                "significant_lines": 16,
                "functions": 2,
                "elapsed_ms": 5,
                "skipped_generated": 0,
                "skipped_minified": 0,
                "skipped_non_utf8": 0,
            },
            "score": {"slop_percent": 10.0, "grade": "B", "deletable_lines": 8},
            "clusters": [
                {
                    "id": 7,
                    "copies": 2,
                    "similarity": 0.95,
                    "deletable_lines": 8,
                    "test_only": False,
                    "members": members,
                }
            ],
        }
    ).encode()


def _production_entries(census):
    return [
        census.ClassifiedEntry(
            "src/a.py",
            "100644",
            "a" * 40,
            "python",
            "production",
            "source.production",
            "1" * 64,
        ),
        census.ClassifiedEntry(
            "src/b.py",
            "100644",
            "b" * 40,
            "python",
            "production",
            "source.production",
            "2" * 64,
        ),
    ]


def test_native_clusters_are_joined_to_manifest_and_keep_advisory_state(
    census, tmp_path
):
    snapshot = tmp_path / "snapshot"
    snapshot.mkdir()
    entries = _production_entries(census)
    normalized, _ = census.validate_native_report(
        _native_report(snapshot),
        snapshot=snapshot,
        manifest_entries=entries,
        expected_skip_counts={"generated": 0, "minified": 0, "invalid_encoding": 0},
    )
    assert normalized["stats"]["files"] == 2
    cluster = normalized["clusters"][0]
    assert cluster["language"] == "python"
    assert [member["path"] for member in cluster["members"]] == ["src/a.py", "src/b.py"]
    finding = census._make_findings(normalized["clusters"], "f" * 64)[0]
    assert finding["classification"] == "product_debt"
    assert finding["actionability"] == "advisory"
    assert finding["id"].startswith("dupehound:function-clone:v1:")
    assert finding["raw_metric"]["native"]["copies"] == 2
    assert finding["raw_metric"]["production_projection"]["copies"] == 2


def test_inline_test_members_are_retained_and_projected(census, tmp_path):
    snapshot = tmp_path / "snapshot"
    snapshot.mkdir()
    entries = _production_entries(census) + [
        census.ClassifiedEntry(
            "src/c.py",
            "100644",
            "c" * 40,
            "python",
            "production",
            "source.production",
            "3" * 64,
        )
    ]
    report = json.loads(_native_report(snapshot).decode())
    report["stats"]["files"] = 3
    report["stats"]["functions"] = 3
    report["clusters"][0]["copies"] = 3
    report["clusters"][0]["members"].append(
        {
            "file": str(snapshot / "src" / "c.py"),
            "name": "inline_test",
            "start_line": 3,
            "end_line": 10,
            "lines": 8,
            "similarity": 0.9,
            "representative": False,
            "test": True,
        }
    )

    normalized, _ = census.validate_native_report(
        json.dumps(report).encode(),
        snapshot=snapshot,
        manifest_entries=entries,
        expected_skip_counts={"generated": 0, "minified": 0, "invalid_encoding": 0},
    )

    cluster = normalized["clusters"][0]
    assert cluster["test_only"] is False
    assert cluster["production_copies"] == 2
    assert cluster["test_member_count"] == 1
    assert [member["test"] for member in cluster["members"]].count(True) == 1
    assert cluster["projection"] == "product_debt"
    findings = census._make_findings(normalized["clusters"], "f" * 64)
    assert len(findings) == 1
    assert findings[0]["raw_metric"]["copies"] == 3
    assert findings[0]["raw_metric"]["production_projection"]["copies"] == 2
    assert findings[0]["raw_metric"]["production_projection"]["test_member_count"] == 1
    assert all(member["test"] is False for member in findings[0]["members"])

    test_only = json.loads(_native_report(snapshot).decode())
    for member in test_only["clusters"][0]["members"]:
        member["test"] = True
    test_only["clusters"][0]["test_only"] = True
    normalized_test_only, _ = census.validate_native_report(
        json.dumps(test_only).encode(),
        snapshot=snapshot,
        manifest_entries=_production_entries(census),
        expected_skip_counts={"generated": 0, "minified": 0, "invalid_encoding": 0},
    )
    assert normalized_test_only["clusters"][0]["projection"] == "telemetry_only"
    assert census._make_findings(normalized_test_only["clusters"], "f" * 64) == []


def test_native_report_mismatches_fail_closed(census, tmp_path):
    snapshot = tmp_path / "snapshot"
    snapshot.mkdir()
    entries = _production_entries(census)
    with pytest.raises(census.CensusError, match="stats.files"):
        census.validate_native_report(
            _native_report(snapshot, files=1),
            snapshot=snapshot,
            manifest_entries=entries,
            expected_skip_counts={"generated": 0, "minified": 0, "invalid_encoding": 0},
        )

    outside = json.loads(_native_report(snapshot).decode())
    outside["clusters"][0]["members"][0]["file"] = str(tmp_path / "outside.py")
    with pytest.raises(
        census.CensusError, match="escapes materialized root|outside production join"
    ):
        census.validate_native_report(
            json.dumps(outside).encode(),
            snapshot=snapshot,
            manifest_entries=entries,
            expected_skip_counts={"generated": 0, "minified": 0, "invalid_encoding": 0},
        )

    shaped = json.loads(_native_report(snapshot).decode())
    shaped["class_shapes"] = []
    with pytest.raises(census.CensusError, match="class-shape"):
        census.validate_native_report(
            json.dumps(shaped).encode(),
            snapshot=snapshot,
            manifest_entries=entries,
            expected_skip_counts={"generated": 0, "minified": 0, "invalid_encoding": 0},
        )

    invalid_test_flag = json.loads(_native_report(snapshot).decode())
    invalid_test_flag["clusters"][0]["members"][0]["test"] = "false"
    with pytest.raises(census.CensusError, match="test is not boolean"):
        census.validate_native_report(
            json.dumps(invalid_test_flag).encode(),
            snapshot=snapshot,
            manifest_entries=entries,
            expected_skip_counts={"generated": 0, "minified": 0, "invalid_encoding": 0},
        )

    inconsistent_test_only = json.loads(_native_report(snapshot).decode())
    inconsistent_test_only["clusters"][0]["test_only"] = True
    with pytest.raises(census.CensusError, match="test_only disagrees"):
        census.validate_native_report(
            json.dumps(inconsistent_test_only).encode(),
            snapshot=snapshot,
            manifest_entries=entries,
            expected_skip_counts={"generated": 0, "minified": 0, "invalid_encoding": 0},
        )


def test_malformed_success_report_keeps_raw_json_and_stderr(census, tmp_path):
    snapshot = tmp_path / "snapshot"
    snapshot.mkdir()
    raw = b'{"schema_version": 1, "stats": {}}\n'
    stderr = b"native warning before malformed report\n"
    with pytest.raises(census.CensusError) as raised:
        census._validate_native_output(
            raw,
            stderr=stderr,
            snapshot=snapshot,
            manifest_entries=_production_entries(census),
            expected_skip_counts={
                "generated": 0,
                "minified": 0,
                "invalid_encoding": 0,
            },
        )
    assert raised.value.code == "native_report_invalid"
    assert raised.value.raw == raw
    assert raised.value.stderr == stderr


def test_empty_production_universe_is_not_applicable_without_native_scan(
    census, contract, tmp_path, monkeypatch
):
    entry = _entry(census, "README.md")
    profile = census.profile_definition(contract)
    context = census.CandidateContext(
        commit="a" * 40,
        tree="b" * 40,
        entries=[entry],
        tree_listing_sha256="c" * 64,
        config=contract,
        profile=profile,
        profile_sha256=census.digest_json(profile),
        universe_sha256=census.digest_json(census.universe_definition()),
        stage_policy_sha256=census.digest_json(census.stage_policy_definition()),
        config_items=[],
        executable=None,
        tool=census._empty_tool(),
    )
    snapshot = tmp_path / "snapshot"
    snapshot.mkdir()
    materialized = census.MaterializedTree(
        snapshot, {entry.path: b"documentation\n"}, "d" * 64, None
    )

    @contextmanager
    def fake_materialize(_commit, _entries):
        yield materialized

    monkeypatch.setattr(census, "materialize", fake_materialize)
    monkeypatch.setattr(
        census,
        "_invoke_scan",
        lambda _command: pytest.fail("native scan must not run for empty scope"),
    )
    args = argparse.Namespace(
        raw_output=tmp_path / "raw.json",
        normalized_output=tmp_path / "evidence.json",
    )

    evidence, raw, stderr = census._scan_context(
        context, args, "run-id", "2026-09-08T00:00:00Z"
    )

    assert raw == b""
    assert stderr == b""
    assert evidence["result"]["scope"] == "not_applicable"
    assert evidence["result"]["exit_class"] == "not_applicable"
    assert evidence["normalized"]["native"] is None
    assert evidence["normalized"]["production"]["native_scan_executed"] is False
    assert context.tool["invocation"] == []


def test_release_workflow_wires_the_adapter_without_changing_changed_gate():
    workflow = (ROOT / ".github/workflows/release.yml").read_text(encoding="utf-8")
    assert "scripts/check_dupehound_census.py" in workflow
    assert "dupehound-full-tree-v1:epistemic-graph" in workflow
    assert "python -m pytest -q tests/test_dupehound_census.py" in workflow
    assert "actions/upload-artifact" in workflow
    assert "epistemic-graph-dupehound.stderr.txt" in workflow
    assert "--no-default-excludes" in (
        ROOT / "scripts/check_dupehound_census.py"
    ).read_text(encoding="utf-8")
    changed_gate = (ROOT / "scripts/check_dupehound.py").read_text(encoding="utf-8")
    assert "dupehound census" not in changed_gate
