//! Deterministic ontology/SHACL-shape text generated from a typed Rust vocabulary
//! (EG-TYPED-PACKS-R090.1).
//!
//! The canonical ontology and SHACL shape corpus must be owned by a typed Rust
//! vocabulary, not hand-edited Turtle: regenerating the text from the same typed
//! declaration must reproduce byte-identical output across runs. This module is
//! the smallest producer-first slice of that mechanism — one tiny self-contained
//! vocabulary fragment and its generator — so the regeneration guarantee has one
//! real, tested implementation to extend onto the existing `crates/eg-core/ontology/*.ttl`
//! corpus in later child requirements (R090.2+).

/// One `owl:Class` declaration in a typed vocabulary module.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OwlClass {
    pub local_name: &'static str,
    pub label: &'static str,
    pub comment: &'static str,
    pub subclass_of: Option<&'static str>,
}

/// One `owl:DatatypeProperty` declaration in a typed vocabulary module.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DatatypeProperty {
    pub local_name: &'static str,
    pub label: &'static str,
    pub range: &'static str,
}

/// A typed vocabulary module: the single source of truth for one generated
/// ontology fragment. `classes` and `properties` are declared in a fixed order,
/// so turtle generation never depends on iteration order of a hash-based
/// collection — that is what makes regeneration byte-identical.
#[derive(Debug, Clone, Copy)]
pub struct VocabularyModule {
    pub module_id: &'static str,
    pub ontology_label: &'static str,
    pub ontology_comment: &'static str,
    pub classes: &'static [OwlClass],
    pub properties: &'static [DatatypeProperty],
}

impl VocabularyModule {
    /// Render this module's canonical Turtle text. Pure and deterministic: equal
    /// input always produces the equal, byte-identical output.
    pub fn to_turtle(&self) -> String {
        let mut out = String::new();
        out.push_str("@prefix : <http://knuckles.team/kg#> .\n");
        out.push_str("@prefix owl: <http://www.w3.org/2002/07/owl#> .\n");
        out.push_str("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n");
        out.push_str("@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n\n");

        for class in self.classes {
            out.push_str(&format!(":{} a owl:Class ;\n", class.local_name));
            out.push_str(&format!("    rdfs:label \"{}\" ;\n", class.label));
            match class.subclass_of {
                Some(parent) => {
                    out.push_str(&format!("    rdfs:comment \"{}\" ;\n", class.comment));
                    out.push_str(&format!("    rdfs:subClassOf :{} .\n\n", parent));
                }
                None => {
                    out.push_str(&format!("    rdfs:comment \"{}\" .\n\n", class.comment));
                }
            }
        }

        for prop in self.properties {
            out.push_str(&format!(":{} a owl:DatatypeProperty ;\n", prop.local_name));
            out.push_str(&format!("    rdfs:label \"{}\" ;\n", prop.label));
            out.push_str(&format!("    rdfs:range {} .\n\n", prop.range));
        }

        out.push_str(&format!(
            "<http://knuckles.team/kg/{}> a owl:Ontology ;\n",
            self.module_id
        ));
        out.push_str(&format!(
            "    rdfs:label \"{}\" ;\n",
            self.ontology_label
        ));
        out.push_str(&format!(
            "    rdfs:comment \"{}\" .\n",
            self.ontology_comment
        ));
        out
    }
}

/// The codegen-mechanism self-test vocabulary: the first typed module generated by
/// this mechanism. Deliberately tiny — it exists to prove the generator, not to
/// model a real domain; `crates/eg-core/ontology/*.ttl` migrate onto this same
/// mechanism in later child requirements.
pub const CODEGEN_SELFTEST_V1: VocabularyModule = VocabularyModule {
    module_id: "codegen_selftest",
    ontology_label: "codegen_selftest Ontology (generated)",
    ontology_comment: "Smallest self-test fragment proving typed-Rust-vocabulary-to-Turtle codegen is deterministic. CONCEPT:EG-KG.ontology.codegen-from-rust-vocabulary.",
    classes: &[OwlClass {
        local_name: "CodegenSelfTestArtifact",
        label: "Codegen self-test artifact",
        comment: "A generated-ontology regression fixture (generated).",
        subclass_of: None,
    }],
    properties: &[DatatypeProperty {
        local_name: "generated_at",
        label: "Generated_at",
        range: "xsd:dateTime",
    }],
};

/// The checked-in expected output of `CODEGEN_SELFTEST_V1.to_turtle()`. Kept as a
/// file fixture (not only an inline string) so a reviewer can diff generated vs.
/// checked-in Turtle the same way any other `crates/eg-core/ontology/*.ttl` is reviewed.
pub const CODEGEN_SELFTEST_V1_CHECKED_IN: &str =
    include_str!("../ontology_codegen_fixtures/codegen_selftest-v1.ttl");

#[cfg(test)]
mod tests {
    use super::*;

    /// EG-TYPED-PACKS-R090.1: regenerating the Turtle text from the typed vocabulary
    /// twice produces byte-identical output, and that output is byte-identical to
    /// the checked-in fixture.
    #[test]
    fn regeneration_is_byte_identical_across_runs_and_to_checked_in_output() {
        let first = CODEGEN_SELFTEST_V1.to_turtle();
        let second = CODEGEN_SELFTEST_V1.to_turtle();
        assert_eq!(first, second, "regeneration must be deterministic");
        assert_eq!(
            first, CODEGEN_SELFTEST_V1_CHECKED_IN,
            "generated Turtle must be byte-identical to the checked-in artifact"
        );
    }

    /// A changed vocabulary (different label) must NOT match the checked-in fixture —
    /// confirms the byte-equality check is not vacuously true.
    #[test]
    fn a_different_module_does_not_match_the_checked_in_fixture() {
        let mut mutated = CODEGEN_SELFTEST_V1;
        mutated.ontology_label = "a different label";
        assert_ne!(mutated.to_turtle(), CODEGEN_SELFTEST_V1_CHECKED_IN);
    }
}
