//! Placement, catalog, lifecycle, service, UDF, and materialized-view controls.

use crate::{DurabilityDomain, TxnParticipation};

use super::{make_policy, PolicyFlags, PolicyRow};

pub(crate) const ROWS: &[PolicyRow] = &[
    ("CreateGraph", make_policy(true, DurabilityDomain::GraphRedb, "graph:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Atomic), "native lifecycle MutationBatch before registry publication"),
    ("DeleteGraph", make_policy(true, DurabilityDomain::GraphRedb, "graph:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Atomic), "native lifecycle MutationBatch before registry eviction"),
    ("ListGraphs", make_policy(false, DurabilityDomain::None, "graph:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("Reshard", make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "prepared/committed admin MutationBatch saga"),
    ("CatalogAssign", make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "prepared/committed admin MutationBatch saga"),
    ("CatalogReassign", make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "prepared/committed admin MutationBatch saga"),
    ("CatalogRemove", make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "prepared/committed admin MutationBatch saga"),
    ("CatalogList", make_policy(false, DurabilityDomain::None, "admin:cluster-read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("RebalancePlan", make_policy(false, DurabilityDomain::None, "admin:cluster-read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("RebalanceExecute", make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "prepared/committed admin MutationBatch saga"),
    ("PlacementRoute", make_policy(false, DurabilityDomain::None, "cluster:placement-read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), "engine-authoritative complete route; single-node returns authoritative unplaced group 0/epoch 0, while clustered routing requires a live MultiRaft control leader; GOC-15/BUG-030 narrowed off admin:cluster-read (2026-08-17) -- ordinary kg:read/kg:write routes their OWN tenant, handlers::placement::handle_route requires kg:admin for any other tenant's route"),
    ("RaftAddLearner", make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "leader-only openraft add_learner; attaches a non-voting replica without changing the voter set"),
    ("RaftChangeMembership", make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "leader-only openraft change_membership; sets the group's exact voter set (the usual way to promote a learner added via RaftAddLearner)"),
    ("ClusterMembers", make_policy(false, DurabilityDomain::None, "cluster:topology-read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), "ADR-1/W1.1 engine-authoritative client topology; deliberately NOT admin:cluster-read -- ordinary service roles need it to re-resolve after a failover; answered from any node, not just the leader"),
    ("RegisterServer", make_policy(true, DurabilityDomain::GraphRedb, "registry:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: true }, TxnParticipation::Atomic), "W2.5 fleet server push-registration/heartbeat: self-translates into Method::AddNode against __commons__ (dispatch.rs), writing a REAL :Server graph node, unlike the internal non-graph topology rows"),
    ("PlacementAdmin", make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), "raft-replicated placement-catalog admin op (Assign/Move/AbortMove, the placement DECISION + PLAN->EXECUTE->CATALOG-UPDATE legs): MultiRaft::placement_assign / TenantManager::move_partition / abort_move commit through the DEFAULT group's own client_write / commit_placement, not this gateway's per-graph MutationBatch"),
    ("Ping", make_policy(false, DurabilityDomain::None, "service:control", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::None), ""),
    ("Health", make_policy(false, DurabilityDomain::None, "service:control", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::None), ""),
    ("Shutdown", make_policy(true, DurabilityDomain::VolatileControl, "service:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::None), "explicitly ephemeral process control; never acknowledges a user-data commit"),
    ("CancelRequest", make_policy(false, DurabilityDomain::None, "service:control", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::None), ""),
    ("RegisterForeignSource", make_policy(true, DurabilityDomain::ControlRedb, "federation:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "opaque prepared/committed control receipt; endpoint configuration is not duplicated in the ledger"),
    ("RegisterUdf", make_policy(true, DurabilityDomain::ControlRedb, "udf:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "opaque prepared/committed control receipt; module bytes are not duplicated in the ledger"),
    ("CreateMatView", make_policy(true, DurabilityDomain::ControlRedb, "matview:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "prepared/committed control-plane MutationBatch saga"),
    ("GetMatView", make_policy(false, DurabilityDomain::None, "matview:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("RefreshMatView", make_policy(true, DurabilityDomain::ControlRedb, "matview:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "prepared/committed control-plane MutationBatch saga"),
    ("PlanMatViewDefine", make_policy(true, DurabilityDomain::ControlRedb, "matview:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "prepared/committed control-plane MutationBatch saga"),
    ("PlanMatViewGet", make_policy(false, DurabilityDomain::None, "matview:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("PlanMatViewRefresh", make_policy(true, DurabilityDomain::ControlRedb, "matview:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "prepared/committed control-plane MutationBatch saga"),
    ("PlanMatViewDrop", make_policy(true, DurabilityDomain::ControlRedb, "matview:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "prepared/committed control-plane MutationBatch saga"),
];
