//! Placement, catalog, lifecycle, service, UDF, and materialized-view controls.

use crate::{DurabilityDomain, Stability, TxnParticipation};

use super::{make_policy, spec, PolicyFlags, PolicyRow, NO_CONSUMER, PYTHON};

pub(crate) const ROWS: &[PolicyRow] = &[
    ("CreateGraph", spec(make_policy(true, DurabilityDomain::GraphRedb, "graph:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Atomic), PYTHON, Stability::Stable), "native lifecycle MutationBatch before registry publication"),
    ("DeleteGraph", spec(make_policy(true, DurabilityDomain::GraphRedb, "graph:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Atomic), PYTHON, Stability::Stable), "native lifecycle MutationBatch before registry eviction"),
    ("ListGraphs", spec(make_policy(false, DurabilityDomain::None, "graph:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), ""),
    ("Reshard", spec(make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), PYTHON, Stability::Stable), "prepared/committed admin MutationBatch saga"),
    ("CatalogAssign", spec(make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), PYTHON, Stability::Stable), "prepared/committed admin MutationBatch saga"),
    ("CatalogReassign", spec(make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), PYTHON, Stability::Stable), "prepared/committed admin MutationBatch saga"),
    ("CatalogRemove", spec(make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), PYTHON, Stability::Stable), "prepared/committed admin MutationBatch saga"),
    ("CatalogList", spec(make_policy(false, DurabilityDomain::None, "admin:cluster-read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), ""),
    ("RebalancePlan", spec(make_policy(false, DurabilityDomain::None, "admin:cluster-read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), ""),
    ("RebalanceExecute", spec(make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), PYTHON, Stability::Stable), "prepared/committed admin MutationBatch saga"),
    ("PlacementRoute", spec(make_policy(false, DurabilityDomain::None, "cluster:placement-read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "engine-authoritative complete route; single-node returns authoritative unplaced group 0/epoch 0, while clustered routing requires a live MultiRaft control leader; GOC-15/BUG-030 narrowed off admin:cluster-read (2026-08-17) -- ordinary kg:read/kg:write routes their OWN tenant, handlers::placement::handle_route requires kg:admin for any other tenant's route"),
    ("RaftAddLearner", spec(make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), PYTHON, Stability::Stable), "leader-only openraft add_learner; attaches a non-voting replica without changing the voter set"),
    ("RaftChangeMembership", spec(make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), PYTHON, Stability::Stable), "leader-only openraft change_membership; sets the group's exact voter set (the usual way to promote a learner added via RaftAddLearner)"),
    ("ClusterMembers", spec(make_policy(false, DurabilityDomain::None, "cluster:topology-read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "ADR-1/W1.1 engine-authoritative client topology; deliberately NOT admin:cluster-read -- ordinary service roles need it to re-resolve after a failover; answered from any node, not just the leader"),
    ("RegisterServer", spec(make_policy(true, DurabilityDomain::GraphRedb, "registry:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: true }, TxnParticipation::Atomic), PYTHON, Stability::Stable), "W2.5 fleet server push-registration/heartbeat: self-translates into Method::AddNode against __commons__ (dispatch.rs), writing a REAL :Server graph node, unlike the internal non-graph topology rows"),
    ("ListRegisteredServers", spec(make_policy(false, DurabilityDomain::None, "registry:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "typed, RLS-projected live :Server snapshot forced to __commons__; revision+digest-fenced keyset pages; authoritative on the single-node/full route (no cluster read barrier is claimed)"),
    ("PlacementAdmin", spec(make_policy(true, DurabilityDomain::ControlRedb, "admin:cluster", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), PYTHON, Stability::Stable), "raft-replicated placement-catalog admin op (Assign/Move/AbortMove, the placement DECISION + PLAN->EXECUTE->CATALOG-UPDATE legs): MultiRaft::placement_assign / TenantManager::move_partition / abort_move commit through the DEFAULT group's own client_write / commit_placement, not this gateway's per-graph MutationBatch"),
    ("Ping", spec(make_policy(false, DurabilityDomain::None, "service:control", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::None), PYTHON, Stability::Stable), ""),
    ("Health", spec(make_policy(false, DurabilityDomain::None, "service:control", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::None), PYTHON, Stability::Stable), ""),
    ("Shutdown", spec(make_policy(true, DurabilityDomain::VolatileControl, "service:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::None), PYTHON, Stability::Stable), "explicitly ephemeral process control; never acknowledges a user-data commit"),
    ("CancelRequest", spec(make_policy(false, DurabilityDomain::None, "service:control", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::None), PYTHON, Stability::Stable), ""),
    ("RegisterForeignSource", spec(make_policy(true, DurabilityDomain::ControlRedb, "federation:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), PYTHON, Stability::Stable), "opaque prepared/committed control receipt; endpoint configuration is not duplicated in the ledger"),
    ("RegisterUdf", spec(make_policy(true, DurabilityDomain::ControlRedb, "udf:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), NO_CONSUMER, Stability::Internal), "opaque prepared/committed control receipt; module bytes are not duplicated in the ledger"),
    ("CreateMatView", spec(make_policy(true, DurabilityDomain::ControlRedb, "matview:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), NO_CONSUMER, Stability::Internal), "prepared/committed control-plane MutationBatch saga"),
    ("GetMatView", spec(make_policy(false, DurabilityDomain::None, "matview:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), NO_CONSUMER, Stability::Internal), ""),
    ("RefreshMatView", spec(make_policy(true, DurabilityDomain::ControlRedb, "matview:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), NO_CONSUMER, Stability::Internal), "prepared/committed control-plane MutationBatch saga"),
    ("PlanMatViewDefine", spec(make_policy(true, DurabilityDomain::ControlRedb, "matview:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), PYTHON, Stability::Stable), "prepared/committed control-plane MutationBatch saga"),
    ("PlanMatViewGet", spec(make_policy(false, DurabilityDomain::None, "matview:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), ""),
    ("PlanMatViewRefresh", spec(make_policy(true, DurabilityDomain::ControlRedb, "matview:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), PYTHON, Stability::Stable), "prepared/committed control-plane MutationBatch saga"),
    ("PlanMatViewDrop", spec(make_policy(true, DurabilityDomain::ControlRedb, "matview:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), PYTHON, Stability::Stable), "prepared/committed control-plane MutationBatch saga"),
];
