//! Work-item, capacity, development-lane, job, and statechart coordination.

use crate::{DurabilityDomain, OpaqueKind, SchemaRef, Stability, TxnParticipation};

use super::{make_policy, spec, PolicyFlags, PolicyRow, PYTHON};

pub(crate) const ROWS: &[PolicyRow] = &[
    ("ClaimNext", spec(make_policy(true, DurabilityDomain::GraphRedb, "node:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), ""),
    ("ClaimWorkItem", spec(make_policy(true, DurabilityDomain::GraphRedb, "work:claim", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "engine-native tenant/fair WorkItem lease claim"),
    ("AcquireCapacity", spec(make_policy(true, DurabilityDomain::GraphRedb, "capacity:lease", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "atomic multi-dimensional capacity admission with epoch/fence ownership"),
    ("RenewCapacity", spec(make_policy(true, DurabilityDomain::GraphRedb, "capacity:lease", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "bounded all-or-nothing lease renewal"),
    ("ReleaseCapacity", spec(make_policy(true, DurabilityDomain::GraphRedb, "capacity:lease", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "bounded all-or-nothing lease release"),
    ("ReclaimExpiredCapacity", spec(make_policy(true, DurabilityDomain::GraphRedb, "capacity:lease", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "bounded expiry reclaim with native aggregate accounting"),
    ("ReconcileCapacity", spec(make_policy(false, DurabilityDomain::None, "capacity:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "bounded native cells/leases reconciliation page"),
    ("CapacityStatus", spec(make_policy(false, DurabilityDomain::None, "capacity:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "exact tenant-scoped native capacity status"),
    ("UpdateCapacityCell", spec(make_policy(true, DurabilityDomain::GraphRedb, "capacity:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Raw), PYTHON, Stability::Stable), "controller epoch CAS for resource dimension/capacity policy"),
    ("SubmitWorkItem", spec(make_policy(true, DurabilityDomain::GraphRedb, "work:submit", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "native tenant-scoped WorkItem command-log admission and outbox commit"),
    ("SubmitWorkItems", spec(make_policy(true, DurabilityDomain::GraphRedb, "work:submit", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "bounded all-or-nothing WorkItem admission batch"),
    ("MintWorkItemClaimCapability", spec(make_policy(true, DurabilityDomain::GraphRedb, "work:claim-capability", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "opaque native capability is retained in a private ledger and never projected"),
    ("VerifyWorkItemClaimCapability", spec(make_policy(false, DurabilityDomain::GraphRedb, "work:claim-capability", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "linearizable live-lease check precedes private capability lookup"),
    ("RenewWorkItemLease", spec(make_policy(true, DurabilityDomain::GraphRedb, "work:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "lease epoch and fencing token are validated atomically"),
    ("CommitWorkItemResult", spec(make_policy(true, DurabilityDomain::GraphRedb, "work:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "terminal result references and outbox commit atomically"),
    ("CancelWorkItem", spec(make_policy(true, DurabilityDomain::GraphRedb, "work:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "pending cancellation never steals an active lease"),
    ("DeferWorkItem", spec(make_policy(true, DurabilityDomain::GraphRedb, "work:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "fenced lease release schedules retry without consuming an attempt"),
    ("CasWorkItemMetadata", spec(make_policy(true, DurabilityDomain::GraphRedb, "work:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "BUG-111: atomic single-field CAS on non-authority scheduling metadata (checkpoint_id/metadata/prio_bucket); status/lease/tenant are fenced but never written"),
    ("ReserveWorkItemResources", spec(make_policy(true, DurabilityDomain::GraphRedb, "resource:reserve", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "controller-only atomic host admission and WorkItem fence validation"),
    ("ReleaseWorkItemResources", spec(make_policy(true, DurabilityDomain::GraphRedb, "resource:reserve", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "controller-only lifecycle release with retained tombstone"),
    ("ReclaimWorkItemResources", spec(make_policy(true, DurabilityDomain::GraphRedb, "resource:reserve", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "controller-only expiry/supersession reclaim with retained tombstone"),
    ("QueryWorkItemReservation", spec(make_policy(false, DurabilityDomain::None, "resource:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "linearizable exact native authority read"),
    ("ResourceReservationStatus", spec(make_policy(false, DurabilityDomain::None, "resource:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "bounded linearizable reconciliation read"),
    ("UpdateResourceHost", spec(make_policy(true, DurabilityDomain::GraphRedb, "resource:host", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "controller-only monotonic host telemetry update"),
    ("ReserveDevelopmentLane", spec(make_policy(true, DurabilityDomain::GraphRedb, "lane:reserve", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "controller-only atomic branch/worktree uniqueness and multi-scope quota hold; now_ms is authority-normalized"),
    ("RenewDevelopmentLane", spec(make_policy(true, DurabilityDomain::GraphRedb, "lane:reserve", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "in-place O(1) hold renewal bound to the current WorkItem lease; now_ms is authority-normalized"),
    ("ObserveDevelopmentLane", spec(make_policy(true, DurabilityDomain::GraphRedb, "lane:reserve", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "monotonic retained-footprint observation replaces the prior native charge; now_ms is authority-normalized"),
    ("FinishDevelopmentLane", spec(make_policy(true, DurabilityDomain::GraphRedb, "lane:reserve", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "terminal lifecycle releases active count but retains cleanup charges and identity; now_ms is authority-normalized"),
    ("CleanupDevelopmentLane", spec(make_policy(true, DurabilityDomain::GraphRedb, "lane:cleanup", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "distinct cleanup WorkItem fence releases retained disk and exclusivity; now_ms is authority-normalized"),
    ("QueryDevelopmentLane", spec(make_policy(false, DurabilityDomain::None, "lane:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "linearizable exact lane hold/tombstone read"),
    ("DevelopmentLaneStatus", spec(make_policy(false, DurabilityDomain::None, "lane:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "bounded tenant-scoped status with maintained counters"),
    ("UpdateDevelopmentLaneQuota", spec(make_policy(true, DurabilityDomain::GraphRedb, "lane:quota", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Raw), PYTHON, Stability::Stable), "controller/admin-only monotonic server-owned quota policy with numeric expected_policy_revision CAS; now_ms is authority-normalized"),
    ("ResourceStatsPage", spec(make_policy(false, DurabilityDomain::None, "service:control", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::None), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "bounded ACL-filtered keyset page; summary suppresses detail arrays"),
    #[cfg(feature = "jobs")]
    ("AnalyticsJob", spec(make_policy(true, DurabilityDomain::JobsRedb, "jobs:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "runtime-conditional: Status is a read; Submit/Cancel/Resume commit through the native jobs.redb MutationBatch gateway"),
    #[cfg(feature = "statechart")]
    ("Statechart", spec(make_policy(true, DurabilityDomain::StatechartRedb, "statechart:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), PYTHON, Stability::Stable), "runtime-conditional: GetState/List are reads; Define/Instantiate/SendEvent commit to the native statecharts.redb store (CONCEPT:INT-P2-2)"),
];
