//! Work-item, capacity, development-lane, job, and statechart coordination.

use crate::{DurabilityDomain, TxnParticipation};

use super::{make_policy, PolicyFlags, PolicyRow};

pub(crate) const ROWS: &[PolicyRow] = &[
    ("ClaimNext", make_policy(true, DurabilityDomain::GraphRedb, "node:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("ClaimWorkItem", make_policy(true, DurabilityDomain::GraphRedb, "work:claim", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "engine-native tenant/fair WorkItem lease claim"),
    ("AcquireCapacity", make_policy(true, DurabilityDomain::GraphRedb, "capacity:lease", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "atomic multi-dimensional capacity admission with epoch/fence ownership"),
    ("RenewCapacity", make_policy(true, DurabilityDomain::GraphRedb, "capacity:lease", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "bounded all-or-nothing lease renewal"),
    ("ReleaseCapacity", make_policy(true, DurabilityDomain::GraphRedb, "capacity:lease", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "bounded all-or-nothing lease release"),
    ("ReclaimExpiredCapacity", make_policy(true, DurabilityDomain::GraphRedb, "capacity:lease", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "bounded expiry reclaim with native aggregate accounting"),
    ("ReconcileCapacity", make_policy(false, DurabilityDomain::None, "capacity:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), "bounded native cells/leases reconciliation page"),
    ("CapacityStatus", make_policy(false, DurabilityDomain::None, "capacity:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), "exact tenant-scoped native capacity status"),
    ("UpdateCapacityCell", make_policy(true, DurabilityDomain::GraphRedb, "capacity:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "controller epoch CAS for resource dimension/capacity policy"),
    ("SubmitWorkItem", make_policy(true, DurabilityDomain::GraphRedb, "work:submit", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "native tenant-scoped WorkItem command-log admission and outbox commit"),
    ("SubmitWorkItems", make_policy(true, DurabilityDomain::GraphRedb, "work:submit", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "bounded all-or-nothing WorkItem admission batch"),
    ("MintWorkItemClaimCapability", make_policy(true, DurabilityDomain::GraphRedb, "work:claim-capability", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Atomic), "opaque native capability is retained in a private ledger and never projected"),
    ("VerifyWorkItemClaimCapability", make_policy(false, DurabilityDomain::GraphRedb, "work:claim-capability", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), "linearizable live-lease check precedes private capability lookup"),
    ("RenewWorkItemLease", make_policy(true, DurabilityDomain::GraphRedb, "work:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "lease epoch and fencing token are validated atomically"),
    ("CommitWorkItemResult", make_policy(true, DurabilityDomain::GraphRedb, "work:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "terminal result references and outbox commit atomically"),
    ("CancelWorkItem", make_policy(true, DurabilityDomain::GraphRedb, "work:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "pending cancellation never steals an active lease"),
    ("DeferWorkItem", make_policy(true, DurabilityDomain::GraphRedb, "work:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "fenced lease release schedules retry without consuming an attempt"),
    ("CasWorkItemMetadata", make_policy(true, DurabilityDomain::GraphRedb, "work:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "BUG-111: atomic single-field CAS on non-authority scheduling metadata (checkpoint_id/metadata/prio_bucket); status/lease/tenant are fenced but never written"),
    ("ReserveWorkItemResources", make_policy(true, DurabilityDomain::GraphRedb, "resource:reserve", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "controller-only atomic host admission and WorkItem fence validation"),
    ("ReleaseWorkItemResources", make_policy(true, DurabilityDomain::GraphRedb, "resource:reserve", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "controller-only lifecycle release with retained tombstone"),
    ("ReclaimWorkItemResources", make_policy(true, DurabilityDomain::GraphRedb, "resource:reserve", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "controller-only expiry/supersession reclaim with retained tombstone"),
    ("QueryWorkItemReservation", make_policy(false, DurabilityDomain::None, "resource:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), "linearizable exact native authority read"),
    ("ResourceReservationStatus", make_policy(false, DurabilityDomain::None, "resource:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), "bounded linearizable reconciliation read"),
    ("UpdateResourceHost", make_policy(true, DurabilityDomain::GraphRedb, "resource:host", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "controller-only monotonic host telemetry update"),
    ("ReserveDevelopmentLane", make_policy(true, DurabilityDomain::GraphRedb, "lane:reserve", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "controller-only atomic branch/worktree uniqueness and multi-scope quota hold; now_ms is authority-normalized"),
    ("RenewDevelopmentLane", make_policy(true, DurabilityDomain::GraphRedb, "lane:reserve", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "in-place O(1) hold renewal bound to the current WorkItem lease; now_ms is authority-normalized"),
    ("ObserveDevelopmentLane", make_policy(true, DurabilityDomain::GraphRedb, "lane:reserve", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "monotonic retained-footprint observation replaces the prior native charge; now_ms is authority-normalized"),
    ("FinishDevelopmentLane", make_policy(true, DurabilityDomain::GraphRedb, "lane:reserve", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "terminal lifecycle releases active count but retains cleanup charges and identity; now_ms is authority-normalized"),
    ("CleanupDevelopmentLane", make_policy(true, DurabilityDomain::GraphRedb, "lane:cleanup", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "distinct cleanup WorkItem fence releases retained disk and exclusivity; now_ms is authority-normalized"),
    ("QueryDevelopmentLane", make_policy(false, DurabilityDomain::None, "lane:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), "linearizable exact lane hold/tombstone read"),
    ("DevelopmentLaneStatus", make_policy(false, DurabilityDomain::None, "lane:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), "bounded tenant-scoped status with maintained counters"),
    ("UpdateDevelopmentLaneQuota", make_policy(true, DurabilityDomain::GraphRedb, "lane:quota", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "controller/admin-only monotonic server-owned quota policy with numeric expected_policy_revision CAS; now_ms is authority-normalized"),
    ("ResourceStats", make_policy(false, DurabilityDomain::None, "service:control", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::None), ""),
    ("ResourceStatsPage", make_policy(false, DurabilityDomain::None, "service:control", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::None), "bounded ACL-filtered keyset page; summary suppresses detail arrays"),
    #[cfg(feature = "jobs")]
    ("AnalyticsJob", make_policy(true, DurabilityDomain::JobsRedb, "jobs:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Atomic), "runtime-conditional: Status is a read; Submit/Cancel/Resume commit through the native jobs.redb MutationBatch gateway"),
    #[cfg(feature = "statechart")]
    ("Statechart", make_policy(true, DurabilityDomain::StatechartRedb, "statechart:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Atomic), "runtime-conditional: GetState/List are reads; Define/Instantiate/SendEvent commit to the native statecharts.redb store (CONCEPT:INT-P2-2)"),
];
