//! Graph primitives, snapshots, summaries, scenes, and graph-local lifecycle effects.

use crate::{DurabilityDomain, TxnParticipation};

use super::{make_policy, PolicyFlags, PolicyRow};

pub(crate) const ROWS: &[PolicyRow] = &[
    ("AddNode", make_policy(true, DurabilityDomain::GraphRedb, "node:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: true }, TxnParticipation::Atomic), ""),
    ("CreateNodeIfAbsent", make_policy(true, DurabilityDomain::GraphRedb, "node:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: true }, TxnParticipation::Atomic), "atomic create returns true only to the inserting writer, so its result is not cross-request cacheable"),
    ("RemoveNode", make_policy(true, DurabilityDomain::GraphRedb, "node:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: true }, TxnParticipation::Atomic), ""),
    ("HasNode", make_policy(false, DurabilityDomain::None, "node:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("GetNodes", make_policy(false, DurabilityDomain::None, "node:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("GetNodesByLabel", make_policy(false, DurabilityDomain::None, "node:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("GetNodeProperties", make_policy(false, DurabilityDomain::None, "node:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("CompareAndSetNodeFields", make_policy(true, DurabilityDomain::GraphRedb, "node:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: true }, TxnParticipation::Atomic), ""),
    ("CreateSummaryNode", make_policy(true, DurabilityDomain::GraphRedb, "memory:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("Consolidate", make_policy(true, DurabilityDomain::GraphRedb, "memory:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("Reinforce", make_policy(true, DurabilityDomain::GraphRedb, "memory:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("DecayNode", make_policy(true, DurabilityDomain::GraphRedb, "memory:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("DecayMemories", make_policy(true, DurabilityDomain::GraphRedb, "memory:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("EvictBelow", make_policy(true, DurabilityDomain::GraphRedb, "memory:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("Maintain", make_policy(true, DurabilityDomain::GraphRedb, "memory:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("SummaryChildren", make_policy(false, DurabilityDomain::None, "memory:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("SummariesAtLevel", make_policy(false, DurabilityDomain::None, "memory:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("AddSceneObject", make_policy(true, DurabilityDomain::GraphRedb, "scene:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("SetPose", make_policy(true, DurabilityDomain::GraphRedb, "scene:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("Reparent", make_policy(true, DurabilityDomain::GraphRedb, "scene:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("WorldTransform", make_policy(false, DurabilityDomain::None, "scene:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("SceneChildren", make_policy(false, DurabilityDomain::None, "scene:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("StartTrajectory", make_policy(true, DurabilityDomain::GraphRedb, "memory:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("AppendStep", make_policy(true, DurabilityDomain::GraphRedb, "memory:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("DiscountedReturn", make_policy(false, DurabilityDomain::None, "memory:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("BestTrajectory", make_policy(false, DurabilityDomain::None, "memory:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("GetNodePropertiesBatch", make_policy(false, DurabilityDomain::None, "node:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("HasNodesBatch", make_policy(false, DurabilityDomain::None, "node:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("NodeCount", make_policy(false, DurabilityDomain::None, "node:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("NodeIds", make_policy(false, DurabilityDomain::None, "node:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("AddEdge", make_policy(true, DurabilityDomain::GraphRedb, "edge:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: true }, TxnParticipation::Atomic), ""),
    ("RemoveEdge", make_policy(true, DurabilityDomain::GraphRedb, "edge:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: true }, TxnParticipation::Atomic), ""),
    ("InvalidateEdge", make_policy(true, DurabilityDomain::GraphRedb, "edge:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("SupersedeEdge", make_policy(true, DurabilityDomain::GraphRedb, "edge:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("HasEdge", make_policy(false, DurabilityDomain::None, "edge:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("GetEdges", make_policy(false, DurabilityDomain::None, "edge:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("GetEdgesPage", make_policy(false, DurabilityDomain::None, "edge:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("ClearGraph", make_policy(true, DurabilityDomain::GraphRedb, "graph:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: true }, TxnParticipation::Atomic), ""),
    ("GetEdgeProperties", make_policy(false, DurabilityDomain::None, "edge:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("GetEdgePropertiesBatch", make_policy(false, DurabilityDomain::None, "edge:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("EdgeCount", make_policy(false, DurabilityDomain::None, "edge:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("InDegree", make_policy(false, DurabilityDomain::None, "edge:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("OutDegree", make_policy(false, DurabilityDomain::None, "edge:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("GetPredecessors", make_policy(false, DurabilityDomain::None, "edge:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("GetSuccessors", make_policy(false, DurabilityDomain::None, "edge:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("GetNeighbors", make_policy(false, DurabilityDomain::None, "edge:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("GetNeighborsBatch", make_policy(false, DurabilityDomain::None, "edge:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("UnionGetNodeProperties", make_policy(false, DurabilityDomain::None, "node:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("UnionGetNodesByLabel", make_policy(false, DurabilityDomain::None, "node:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("UnionGetNeighbors", make_policy(false, DurabilityDomain::None, "node:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("PruneByLifecycle", make_policy(true, DurabilityDomain::GraphRedb, "node:admin", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Atomic), "state-backed MutationBatch commits the resulting authoritative image"),
    ("Metrics", make_policy(false, DurabilityDomain::None, "service:control", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::None), ""),
    ("EvictLRU", make_policy(true, DurabilityDomain::GraphRedb, "node:admin", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Atomic), "state-backed MutationBatch commits the resulting authoritative image"),
    ("DecaySweep", make_policy(true, DurabilityDomain::GraphRedb, "node:admin", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Atomic), "state-backed MutationBatch commits the resulting authoritative image"),
    ("TouchNodes", make_policy(true, DurabilityDomain::GraphRedb, "node:admin", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Atomic), "state-backed MutationBatch commits the resulting authoritative image"),
    ("GetSubgraph", make_policy(false, DurabilityDomain::None, "node:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("Fork", make_policy(false, DurabilityDomain::None, "graph:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), "returns the forked snapshot to the caller; never registers/persists it server-side"),
    ("DiffAgainst", make_policy(false, DurabilityDomain::None, "graph:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("CompactNodesByType", make_policy(true, DurabilityDomain::GraphRedb, "node:admin", PolicyFlags { idempotent: false, audited: true, emits_cdc: true }, TxnParticipation::Atomic), "state-backed MutationBatch"),
    ("Reconcile", make_policy(true, DurabilityDomain::GraphRedb, "graph:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: true }, TxnParticipation::Saga), "state-backed MutationBatch commits the merged image"),
    ("ApplyMutation", make_policy(true, DurabilityDomain::GraphRedb, "graph:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: true }, TxnParticipation::Atomic), "state-backed MutationBatch"),
    ("AddTriples", make_policy(true, DurabilityDomain::GraphRedb, "rdf:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("RemoveTriples", make_policy(true, DurabilityDomain::GraphRedb, "rdf:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("DropNamedGraph", make_policy(true, DurabilityDomain::GraphRedb, "rdf:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
];
