//! Broker, stream, channel, change-feed, trigger, and CEP capabilities.

use crate::{DurabilityDomain, TxnParticipation};

use super::{make_policy, PolicyFlags, PolicyRow};

pub(crate) const ROWS: &[PolicyRow] = &[
    ("DeclareExchange", make_policy(true, DurabilityDomain::Outbox, "broker:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("DeleteExchange", make_policy(true, DurabilityDomain::Outbox, "broker:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("BindQueue", make_policy(true, DurabilityDomain::Outbox, "broker:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("UnbindQueue", make_policy(true, DurabilityDomain::Outbox, "broker:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("Publish", make_policy(true, DurabilityDomain::Outbox, "broker:publish", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "PublishIdempotent is the one exception (producer-id/seq dedup makes replays idempotent by construction)"),
    ("DeclareQueue", make_policy(true, DurabilityDomain::Outbox, "broker:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("PublishEx", make_policy(true, DurabilityDomain::Outbox, "broker:publish", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "PublishIdempotent is the one exception (producer-id/seq dedup makes replays idempotent by construction)"),
    ("BrokerConsume", make_policy(true, DurabilityDomain::Outbox, "broker:consume", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("BrokerAck", make_policy(true, DurabilityDomain::Outbox, "broker:ack", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("BrokerReject", make_policy(true, DurabilityDomain::Outbox, "broker:ack", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("SweepExpired", make_policy(true, DurabilityDomain::Outbox, "broker:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("StreamDeclare", make_policy(true, DurabilityDomain::Outbox, "stream:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("StreamPublish", make_policy(true, DurabilityDomain::Outbox, "stream:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("StreamRead", make_policy(false, DurabilityDomain::None, "stream:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("StreamTrim", make_policy(true, DurabilityDomain::Outbox, "stream:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("StreamCommitOffset", make_policy(true, DurabilityDomain::Outbox, "stream:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), ""),
    ("StreamCommittedOffset", make_policy(false, DurabilityDomain::None, "stream:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("PublishConfirmed", make_policy(true, DurabilityDomain::Outbox, "broker:publish", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "PublishIdempotent is the one exception (producer-id/seq dedup makes replays idempotent by construction)"),
    ("PublishIdempotent", make_policy(true, DurabilityDomain::Outbox, "broker:publish", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "PublishIdempotent is the one exception (producer-id/seq dedup makes replays idempotent by construction)"),
    ("BrokerAckTag", make_policy(true, DurabilityDomain::Outbox, "broker:ack", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "current-generation result must not be replay-cached across requests"),
    ("BrokerNackTag", make_policy(true, DurabilityDomain::Outbox, "broker:ack", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "current-generation result must not be replay-cached across requests"),
    ("BrokerRenewTag", make_policy(true, DurabilityDomain::Outbox, "broker:ack", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), "current-generation result must not be replay-cached across requests"),
    ("CreateChannel", make_policy(true, DurabilityDomain::ControlRedb, "channel:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "opaque prepared/committed session-control MutationBatch; message/member payloads stay out of the ledger"),
    ("JoinChannel", make_policy(true, DurabilityDomain::ControlRedb, "channel:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "opaque prepared/committed session-control MutationBatch"),
    ("LeaveChannel", make_policy(true, DurabilityDomain::ControlRedb, "channel:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "opaque prepared/committed session-control MutationBatch"),
    ("CloseChannel", make_policy(true, DurabilityDomain::ControlRedb, "channel:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "opaque prepared/committed session-control MutationBatch"),
    ("SendMessage", make_policy(true, DurabilityDomain::ControlRedb, "channel:write", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "request-scoped opaque session-control receipt prevents acknowledgement-lost duplicate sends"),
    ("GetChannelMessages", make_policy(false, DurabilityDomain::None, "channel:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("ListChannels", make_policy(false, DurabilityDomain::None, "channel:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("GetChannelMembers", make_policy(false, DurabilityDomain::None, "channel:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("CdcRead", make_policy(false, DurabilityDomain::None, "cdc:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("RegisterContinuousQuery", make_policy(true, DurabilityDomain::ControlRedb, "cdc:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "opaque prepared/committed session-control MutationBatch"),
    ("ReadContinuousQuery", make_policy(false, DurabilityDomain::None, "cdc:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("DropContinuousQuery", make_policy(true, DurabilityDomain::ControlRedb, "cdc:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "opaque prepared/committed session-control MutationBatch"),
    ("Watch", make_policy(false, DurabilityDomain::None, "cdc:read", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::None), "opens a push subscription; not a snapshot read nor a mutation"),
    ("RegisterTrigger", make_policy(true, DurabilityDomain::ControlRedb, "cdc:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "opaque prepared/committed session-control MutationBatch"),
    ("DropTrigger", make_policy(true, DurabilityDomain::ControlRedb, "cdc:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "opaque prepared/committed session-control MutationBatch"),
    ("ListTriggers", make_policy(false, DurabilityDomain::None, "cdc:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("FiredTriggers", make_policy(false, DurabilityDomain::None, "cdc:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("CepSubscribe", make_policy(true, DurabilityDomain::ControlRedb, "cep:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "opaque prepared/committed session-control MutationBatch"),
    ("CepPoll", make_policy(false, DurabilityDomain::None, "cep:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), ""),
    ("CepUnsubscribe", make_policy(true, DurabilityDomain::ControlRedb, "cep:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), "opaque prepared/committed session-control MutationBatch"),
];
