//! Query, provenance, materialization, and read-projection capabilities.

use crate::{DurabilityDomain, Stability, TxnParticipation};

use super::{make_policy, spec, PolicyFlags, PolicyRow, PYTHON};

pub(crate) const ROWS: &[PolicyRow] = &[
    ("GetContextView", spec(make_policy(false, DurabilityDomain::None, "node:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), ""),
    ("GetChangeEnvelope", spec(make_policy(false, DurabilityDomain::None, "ingest:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "Verified tenant-scoped reconciliation read"),
    ("GetContentVersion", spec(make_policy(false, DurabilityDomain::None, "ingest:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "Typed content versions are never compared lexically"),
    ("GetChangeCursor", spec(make_policy(false, DurabilityDomain::None, "ingest:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "Typed source cursors are tenant/graph/partition scoped"),
    ("Sql", spec(make_policy(true, DurabilityDomain::GraphRedb, "query:sql", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), PYTHON, Stability::Stable), "runtime-conditional; graph DML uses staged graph state while table/catalog writes atomically commit SQL rows plus MutationBatch status/fence/idempotency/outbox"),
    ("CypherQuery", spec(make_policy(true, DurabilityDomain::GraphRedb, "query:cypher", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), PYTHON, Stability::Stable), "runtime-conditional; writes execute against a staged graph and publish only after durable MutationBatch commit"),
    ("GraphQl", spec(make_policy(true, DurabilityDomain::GraphRedb, "query:graphql", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), PYTHON, Stability::Stable), "runtime-conditional; ordinary writes stage through MutationBatch and cross-modal commit atomically includes universal status/fence/idempotency/outbox"),
    #[cfg(feature = "knowledge-batch")]
    ("KnowledgeStream", spec(make_policy(false, DurabilityDomain::None, "query:stream", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "one RequestContext/RLS/placement-bound stream with the sole native Arrow IPC projection for all seven query families"),
    ("UnifiedQuery", spec(make_policy(false, DurabilityDomain::None, "query:unified", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), ""),
    ("UnifiedQueryText", spec(make_policy(false, DurabilityDomain::None, "query:unified", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), ""),
    ("ExplainPlan", spec(make_policy(false, DurabilityDomain::None, "explain:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), ""),
    ("ExplainProvenance", spec(make_policy(false, DurabilityDomain::None, "explain:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), ""),
    ("ExplainProvenanceByIds", spec(make_policy(false, DurabilityDomain::None, "explain:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "CONCEPT:EG-KB-CURRENCY — ID-seeded sibling of ExplainProvenance, same policy profile"),
    ("ExplainPolicy", spec(make_policy(false, DurabilityDomain::None, "explain:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), ""),
    ("ExplainBelief", spec(make_policy(false, DurabilityDomain::None, "explain:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), ""),
    ("EpistemicStatus", spec(make_policy(false, DurabilityDomain::None, "explain:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "L53 (EPI-P3-5) acceptance capstone; handler additionally gated `epistemic-tms`"),
    ("WhatChanged", spec(make_policy(false, DurabilityDomain::None, "explain:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "L53 (EPI-P3-5) bitemporal diff; handler additionally gated `epistemic-tms`"),
    ("RecomputeMaterialization", spec(make_policy(true, DurabilityDomain::ReasoningProjection, "reasoning:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Atomic), PYTHON, Stability::Stable), "fenced recompute/writeback resolves provenance from the authoritative graph and fsyncs the per-graph projection"),
    ("MaterializationStatus", spec(make_policy(false, DurabilityDomain::None, "explain:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "read-only status from the durable per-graph incremental reasoning authority"),
    ("StaleMaterializations", spec(make_policy(false, DurabilityDomain::None, "explain:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "bulk opaque stale references from the durable per-graph incremental reasoning authority"),
    ("ResolveConflict", spec(make_policy(false, DurabilityDomain::None, "explain:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "EPI-P3-7 (gap-fill) standalone Dung argumentation (grounded/preferred/stable) conflict resolution over a BeliefGraph snapshot; handler additionally gated `epistemic-tms`"),
    ("ExplainEvidence", spec(make_policy(false, DurabilityDomain::None, "explain:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "CONCEPT:EG-X1 multimodal-citation resolver; handler additionally gated `evidence-graph`"),
    ("CausalEstimate", spec(make_policy(false, DurabilityDomain::None, "explain:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "EPI-P3-3/P3-6 do-calculus intervention OR observational conditioning (selected by `mode`) over a request-carried SCM; handler additionally gated `epistemic-causal`"),
    ("CausalCounterfactual", spec(make_policy(false, DurabilityDomain::None, "explain:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "EPI-P3-6 Pearl point-counterfactual over a request-carried SCM + a fully-observed unit; handler additionally gated `epistemic-causal`"),
    ("RankByProvenance", spec(make_policy(false, DurabilityDomain::None, "explain:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "EPI-P3-3 provenance-aware retrieval ranking; handler additionally gated `epistemic-causal`"),
    ("NlQuery", spec(make_policy(false, DurabilityDomain::None, "query:nl", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), ""),
    ("TxnUnifiedQuery", spec(make_policy(false, DurabilityDomain::None, "txn:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), PYTHON, Stability::Stable), ""),
    ("TxnUnifiedQueryText", spec(make_policy(false, DurabilityDomain::None, "txn:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), PYTHON, Stability::Stable), ""),
];
