//! Audit, identity, RBAC, and policy-export capabilities.

use crate::{DurabilityDomain, Stability, TxnParticipation};

use super::{make_policy, spec, PolicyFlags, PolicyRow, PYTHON};

pub(crate) const ROWS: &[PolicyRow] = &[
    ("GetLedger", spec(make_policy(false, DurabilityDomain::None, "ledger:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), ""),
    ("AuditVerify", spec(make_policy(false, DurabilityDomain::None, "security:audit", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), ""),
    ("AuditProveInclusion", spec(make_policy(false, DurabilityDomain::None, "security:audit", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "provenance anchoring: Merkle inclusion proof for one node against a prior PROVENANCE_ANCHOR audit-chain entry"),
    ("RegisterIdentity", spec(make_policy(true, DurabilityDomain::ControlRedb, "security:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), PYTHON, Stability::Stable), "RBAC/identity snapshot and MutationBatch metadata share one rbac.redb WTX; IDM-03: each registration appends a hash-chained identity-audit entry in that same WTX, and a principal owned by the identity store is refused"),
    ("RbacAdmin", spec(make_policy(true, DurabilityDomain::ControlRedb, "security:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), PYTHON, Stability::Stable), "runtime-conditional: List is a read; role and grant updates share one rbac.redb WTX with MutationBatch metadata; IDM-03: each write appends a hash-chained identity-audit entry in that WTX, and the identity store's idm: namespace is refused"),
    ("RbacElevation", spec(make_policy(true, DurabilityDomain::ControlRedb, "rbac:elevation", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), PYTHON, Stability::Stable), "EH-404 just-in-time elevation, runtime-conditional: list is a read (rbac:elevation-read); request/revoke need rbac:elevation, approve needs the EXACT rbac:approve-elevation scope from a direct (undelegated) principal sharing no identity with the requester; every transition is hash-chain audited in the elevation ledger that shares the rbac.redb policy WTX"),
    ("Identity", spec(make_policy(true, DurabilityDomain::ControlRedb, "identity:admin", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), PYTHON, Stability::Stable), "IDM-01..04 engine-owned identity store, runtime-conditional: reads are identity:read/identity:authenticate; writes need the op's EXACT identity:* scope (never implied by kg:admin or *) from the boundary-stamped actor; every secret is hashed, verified or sealed at the request boundary and cleared before replication; the store and its full RBAC projection share one rbac.redb WTX with a hash-chained identity audit trail"),
    ("GetIdentity", spec(make_policy(false, DurabilityDomain::None, "security:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "identity read-back closing the RegisterIdentity blind-upsert gap: None means unregistered/unknown, Some(identity) with empty roles means registered-and-confirmed-empty -- gated security:admin like RegisterIdentity/RbacAdmin so it grants no caller new privilege"),
    ("CheckAccess", spec(make_policy(false, DurabilityDomain::None, "security:check", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), PYTHON, Stability::Stable), "confused-deputy-safe executor re-check: would this principal's own request of read/write on the request graph be admitted now (the engine's isolation/RBAC decision). Answers only allowed yes/no for one principal on one graph the caller can itself read; never the identity or the policy"),
];
