//! Ledger, serialization, native stores, time series, blobs, KV, and SQLite.

use crate::{
    DurabilityDomain, OpaqueKind, PayloadShape, SchemaProvenance, SchemaRef, Stability,
    TxnParticipation,
};

use super::{make_policy, spec, PolicyFlags, PolicyRow, NO_CONSUMER, PYTHON};

pub(crate) const ROWS: &[PolicyRow] = &[
    ("ToMsgpack", spec(make_policy(false, DurabilityDomain::None, "graph:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), SchemaProvenance::Undeclared, PYTHON, Stability::Stable), ""),
    ("FromMsgpack", spec(make_policy(true, DurabilityDomain::GraphRedb, "graph:admin", PolicyFlags { idempotent: false, audited: true, emits_cdc: true }, TxnParticipation::Atomic), SchemaRef::Payload(PayloadShape::Text), SchemaProvenance::DispatchOnly, PYTHON, Stability::Stable), "state-backed MutationBatch commits the imported authoritative image"),
    ("ClearLedger", spec(make_policy(true, DurabilityDomain::GraphRedb, "ledger:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: true }, TxnParticipation::Atomic), SchemaRef::Payload(PayloadShape::Text), SchemaProvenance::DispatchOnly, PYTHON, Stability::Stable), "state-backed MutationBatch"),
    ("ApplyLedger", spec(make_policy(true, DurabilityDomain::GraphRedb, "ledger:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: true }, TxnParticipation::Atomic), SchemaRef::Payload(PayloadShape::Text), SchemaProvenance::DispatchOnly, PYTHON, Stability::Stable), "state-backed MutationBatch"),
    ("Backup", spec(make_policy(false, DurabilityDomain::None, "admin:backup", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Json), SchemaProvenance::DispatchOnly, PYTHON, Stability::Stable), "reads a consistent snapshot out to a bundle; does not mutate the live graph"),
    ("Restore", spec(make_policy(true, DurabilityDomain::ControlRedb, "admin:backup", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Opaque(OpaqueKind::Json), SchemaProvenance::DispatchOnly, PYTHON, Stability::Stable), "prepared/committed admin MutationBatch saga"),
    ("AgentLibrary", spec(make_policy(true, DurabilityDomain::ControlRedb, "agent:library-write", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Raw), SchemaProvenance::DispatchOnly, PYTHON, Stability::Stable), "runtime-conditional: Current/History/Status are authenticated tenant-bound read snapshots; Publish/Retire atomically commit native revisions, action provenance, replay receipts, and outbox through ControlRedb"),
    ("AgentGraph", spec(make_policy(true, DurabilityDomain::ControlRedb, "agent:graph-write", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Raw), SchemaProvenance::DispatchOnly, PYTHON, Stability::Stable), "RF-ADR-008. Runtime-conditional exactly like AgentLibrary: Current/History/Status are authenticated tenant-bound read snapshots; Publish/Retire atomically commit native graph revisions, action provenance, replay receipts, and outbox through ControlRedb into the SAME agent_library.redb owner"),
    ("AgentComponent", spec(make_policy(true, DurabilityDomain::ControlRedb, "agent:component-write", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Raw), SchemaProvenance::DispatchOnly, PYTHON, Stability::Stable), "RF-ADR-008 layer 1. Runtime-conditional like AgentLibrary/AgentGraph: Current/History/Status/Search are authenticated tenant-bound read snapshots; Publish/Retire atomically commit native component revisions, action provenance, replay receipts and outbox through ControlRedb into the SAME agent_library.redb owner"),
    ("AgentTemplate", spec(make_policy(true, DurabilityDomain::ControlRedb, "agent:template-write", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Raw), SchemaProvenance::DispatchOnly, PYTHON, Stability::Stable), "RF-ADR-008 item C. Runtime-conditional like the three layers beside it: Current/History/Status/Instantiate are authenticated tenant-bound read snapshots (Instantiate binds parameters and returns a draft, committing nothing); Publish/Retire atomically commit native template revisions, action provenance, replay receipts and outbox through ControlRedb into the SAME agent_library.redb owner. Its own authz action because publishing a parameterized FAMILY of agents is a distinct privilege from publishing one"),
    ("TsAppend", spec(make_policy(true, DurabilityDomain::SeriesRedb, "timeseries:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Payload(PayloadShape::Count), SchemaProvenance::Confirmed, PYTHON, Stability::Stable), "graph ACL + placement policy precede the tenant/graph/series-scoped series.redb write"),
    ("TsRange", spec(make_policy(false, DurabilityDomain::None, "timeseries:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), SchemaProvenance::Undeclared, PYTHON, Stability::Stable), ""),
    ("TsAsofJoin", spec(make_policy(false, DurabilityDomain::None, "timeseries:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), SchemaProvenance::Undeclared, PYTHON, Stability::Stable), ""),
    ("TsWindow", spec(make_policy(false, DurabilityDomain::None, "timeseries:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), SchemaProvenance::Undeclared, PYTHON, Stability::Stable), ""),
    ("TsGapFill", spec(make_policy(false, DurabilityDomain::None, "timeseries:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), SchemaProvenance::Undeclared, PYTHON, Stability::Stable), ""),
    ("TsEvict", spec(make_policy(true, DurabilityDomain::SeriesRedb, "timeseries:write", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Payload(PayloadShape::Count), SchemaProvenance::Confirmed, PYTHON, Stability::Stable), "content-idempotent unlike TsAppend: re-evicting an already-past cutoff is a safe no-op (see SeriesStore::evict_before)"),
    ("TsDeleteSeries", spec(make_policy(true, DurabilityDomain::SeriesRedb, "timeseries:write", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Payload(PayloadShape::Count), SchemaProvenance::Confirmed, PYTHON, Stability::Stable), "content-idempotent unlike TsAppend: re-deleting an already-gone series is a safe no-op (see SeriesStore::delete_series)"),
    ("TsListSeries", spec(make_policy(false, DurabilityDomain::None, "timeseries:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), SchemaProvenance::Undeclared, PYTHON, Stability::Stable), ""),
    ("BlobBegin", spec(make_policy(true, DurabilityDomain::BlobRedb, "blob:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Count), SchemaProvenance::Confirmed, PYTHON, Stability::Stable), "multi-call chunked-upload protocol (Begin ... ChunkPut* ... Commit); no single-call atomicity; durable via its own blob.redb (group-committed Immediate), self-routes before dispatch_graph_op"),
    ("BlobChunkPut", spec(make_policy(true, DurabilityDomain::BlobRedb, "blob:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Count), SchemaProvenance::Confirmed, PYTHON, Stability::Stable), "durable via its own blob.redb (group-committed Immediate); self-routes before dispatch_graph_op"),
    ("BlobCommit", spec(make_policy(true, DurabilityDomain::BlobRedb, "blob:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Text), SchemaProvenance::Confirmed, PYTHON, Stability::Stable), "multi-call chunked-upload protocol (Begin ... ChunkPut* ... Commit); no single-call atomicity; durable via its own blob.redb (group-committed Immediate), self-routes before dispatch_graph_op"),
    ("BlobFetchBegin", spec(make_policy(false, DurabilityDomain::None, "blob:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), SchemaProvenance::Undeclared, PYTHON, Stability::Stable), ""),
    ("BlobChunkGet", spec(make_policy(false, DurabilityDomain::None, "blob:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), SchemaProvenance::Undeclared, PYTHON, Stability::Stable), ""),
    ("BlobFetchEnd", spec(make_policy(false, DurabilityDomain::None, "blob:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::Confirmed, PYTHON, Stability::Stable), ""),
    ("BlobRef", spec(make_policy(true, DurabilityDomain::BlobRedb, "blob:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Payload(PayloadShape::Count), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "refcount increment; idempotent-ish but re-invocation adds another ref, so not idempotent; durable via blob.redb"),
    ("BlobUnref", spec(make_policy(true, DurabilityDomain::BlobRedb, "blob:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Payload(PayloadShape::Count), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "durable via blob.redb"),
    ("BlobGc", spec(make_policy(true, DurabilityDomain::BlobRedb, "blob:admin", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), SchemaProvenance::Undeclared, PYTHON, Stability::Stable), "durable via blob.redb"),
    ("KvGet", spec(make_policy(false, DurabilityDomain::None, "kv:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), SchemaProvenance::Undeclared, NO_CONSUMER, Stability::Internal), ""),
    ("KvPut", spec(make_policy(true, DurabilityDomain::KvRedb, "kv:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Payload(PayloadShape::Text), SchemaProvenance::DispatchOnly, NO_CONSUMER, Stability::Internal), "durable via its own kv.redb (redb::Durability::Immediate, commit-before-ack); self-routes before graph dispatch"),
    ("KvDelete", spec(make_policy(true, DurabilityDomain::KvRedb, "kv:write", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::DispatchOnly, NO_CONSUMER, Stability::Internal), "durable via its own kv.redb (redb::Durability::Immediate); self-routes before dispatch_graph_op"),
    ("KvScan", spec(make_policy(false, DurabilityDomain::None, "kv:read", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Undeclared), SchemaProvenance::Undeclared, NO_CONSUMER, Stability::Internal), ""),
    ("KvCas", spec(make_policy(true, DurabilityDomain::KvRedb, "kv:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::DispatchOnly, NO_CONSUMER, Stability::Internal), "durable via its own kv.redb (redb::Durability::Immediate, commit-before-ack); self-routes before graph dispatch"),
    ("ImportSqliteFile", spec(make_policy(true, DurabilityDomain::ControlRedb, "admin:sqlite-file", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Json), SchemaProvenance::DispatchOnly, PYTHON, Stability::Stable), "native SQL-catalog MutationBatch; logical transfer name is excluded from the durable receipt"),
    ("ExportSqliteFile", spec(make_policy(false, DurabilityDomain::None, "admin:sqlite-file", PolicyFlags { idempotent: true, audited: true, emits_cdc: false }, TxnParticipation::Snapshot), SchemaRef::Opaque(OpaqueKind::Json), SchemaProvenance::DispatchOnly, PYTHON, Stability::Stable), "operator-provisioned transfer root; logical filenames only"),
];
