//! Batch, change-envelope, multisig, and transaction-protocol capabilities.

use crate::{
    DurabilityDomain, OpaqueKind, PayloadShape, SchemaProvenance, SchemaRef, Stability,
    TxnParticipation,
};

use super::{make_policy, spec, PolicyFlags, PolicyRow, PYTHON};

pub(crate) const ROWS: &[PolicyRow] = &[
    ("BatchUpdate", spec(make_policy(true, DurabilityDomain::GraphRedb, "node:write", PolicyFlags { idempotent: false, audited: true, emits_cdc: false }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Json), SchemaProvenance::DispatchOnly, PYTHON, Stability::Stable), ""),
    ("MultiGraphBatchUpdate", spec(make_policy(true, DurabilityDomain::ControlRedb, "node:write", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Opaque(OpaqueKind::Undeclared), SchemaProvenance::Undeclared, PYTHON, Stability::Stable), "durable parent coordinator with per-graph MutationBatch children"),
    ("ApplyChangeEnvelope", spec(make_policy(true, DurabilityDomain::GraphRedb, "ingest:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: true }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Json), SchemaProvenance::DispatchOnly, PYTHON, Stability::Stable), "Engine-native object/material/governance/version/cursor/outbox commit; verified context is mandatory"),
    ("ApplyChangeEnvelopes", spec(make_policy(true, DurabilityDomain::GraphRedb, "ingest:write", PolicyFlags { idempotent: true, audited: true, emits_cdc: true }, TxnParticipation::Atomic), SchemaRef::Opaque(OpaqueKind::Undeclared), SchemaProvenance::Undeclared, PYTHON, Stability::Stable), "Batch envelope coordinator: one coalesced graph transaction per shard-partition; same policy class as ApplyChangeEnvelope"),
    ("ApplyMultisigMutation", spec(make_policy(true, DurabilityDomain::GraphRedb, "security:admin", PolicyFlags { idempotent: true, audited: true, emits_cdc: true }, TxnParticipation::Saga), SchemaRef::Opaque(OpaqueKind::Conflicting), SchemaProvenance::Contradicted { dispatch: "Bool", annotation: "String" }, PYTHON, Stability::Stable), "threshold validation translates into the graph MutationBatch gateway"),
    ("BeginTxn", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:control", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Text), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "encrypted Raft-native transaction staging authority"),
    ("TxnAddNode", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "encrypted Raft-native staging; Commit owns graph publication"),
    ("TxnRemoveNode", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:write", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "encrypted Raft-native staging; Commit owns graph publication"),
    ("TxnAddEdge", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "encrypted Raft-native staging; Commit owns graph publication"),
    ("TxnRemoveEdge", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:write", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "encrypted Raft-native staging; Commit owns graph publication"),
    ("TxnCas", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:write", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "encrypted Raft-native staging; Commit owns graph publication"),
    ("TxnAddEmbedding", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "encrypted Raft-native cross-modal staging"),
    ("TxnBlobRef", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "encrypted Raft-native cross-modal staging"),
    ("TxnAddMeasurement", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "encrypted Raft-native cross-modal staging"),
    ("TxnAxiom", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "encrypted Raft-native cross-modal staging"),
    ("TxnConstruct", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "encrypted Raft-native cross-modal staging"),
    ("TxnPlanWriteback", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "encrypted Raft-native cross-modal staging"),
    ("TxnMaterializeBelief", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:write", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "encrypted Raft-native cross-modal staging"),
    ("Commit", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:control", PolicyFlags { idempotent: true, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Opaque(OpaqueKind::Undeclared), SchemaProvenance::Undeclared, PYTHON, Stability::Stable), "named parent receipt plus atomic graph/cross-modal child batches"),
    ("Rollback", spec(make_policy(true, DurabilityDomain::ControlRedb, "txn:control", PolicyFlags { idempotent: false, audited: false, emits_cdc: false }, TxnParticipation::Saga), SchemaRef::Payload(PayloadShape::Bool), SchemaProvenance::AnnotationOnly, PYTHON, Stability::Stable), "encrypted Raft-native transaction staging removal"),
];
