//! Snapshots of the four current classifier surfaces used by consistency checks.

/// Mirrors `src/server/access.rs::requires_write`'s UNCONDITIONAL-true set (both the
/// feature-gated `if matches!(...) { return true; }` blocks -- rdf/kv/broker -- and the
/// final unconditional `matches!(...)` tail). For every one of these, `requires_write`
/// returns `true` no matter what the request's fields are.
pub(crate) const ACCESS_RS_MUTATES_UNCONDITIONAL: &[&str] = &[
    "AddEdge",
    "AddEmbedding",
    "AddNode",
    "AddSceneObject",
    "AddTriples",
    "AppendStep",
    "ApplyChangeEnvelope",
    "ApplyChangeEnvelopes",
    "ApplyLedger",
    "ApplyMultisigMutation",
    "ApplyMutation",
    "BatchUpdate",
    "BeginTxn",
    "BindQueue",
    "BrokerAck",
    "BrokerAckTag",
    "BrokerConsume",
    "BrokerNackTag",
    "BrokerReject",
    "BrokerRenewTag",
    "CancelWorkItem",
    "CasWorkItemMetadata",
    "ClaimNext",
    "ClaimWorkItem",
    "KgDelegate",
    "SubmitWorkItem",
    "SubmitWorkItems",
    "AcquireCapacity",
    "RenewCapacity",
    "ReleaseCapacity",
    "ReclaimExpiredCapacity",
    "UpdateCapacityCell",
    "MintWorkItemClaimCapability",
    "ClearGraph",
    "ClearLedger",
    "CompactNodesByType",
    "CompareAndSetNodeFields",
    "CommitWorkItemResult",
    "Consolidate",
    "CreateNodeIfAbsent",
    "CreateSummaryNode",
    "DecayMemories",
    "DecayNode",
    "DecaySweep",
    "DeferWorkItem",
    "DeclareExchange",
    "DeclareQueue",
    "DeleteExchange",
    "DeleteGraph",
    "DropNamedGraph",
    "EvictBelow",
    "EvictLRU",
    "FromMsgpack",
    "ImportSqliteFile",
    "IcvConfigure",
    "InvalidateEdge",
    "KvCas",
    "KvDelete",
    "KvPut",
    "Maintain",
    "MiningPipelineServe",
    "PruneByLifecycle",
    "Publish",
    "PublishEx",
    "ReclaimWorkItemResources",
    "Reconcile",
    "Reinforce",
    "ReleaseWorkItemResources",
    "RemoveEdge",
    "RemoveNode",
    "RemoveTriples",
    "Reparent",
    "RenewWorkItemLease",
    "ReserveWorkItemResources",
    "RunDatalogReasoning",
    "Rollback",
    "SetPose",
    "StartTrajectory",
    "SupersedeEdge",
    "SweepExpired",
    "UpdateResourceHost",
    "TouchNodes",
    "UnbindQueue",
];

/// Mirrors `src/server/access.rs::requires_write`'s RUNTIME-CONDITIONAL set: the Mine*/
/// GraphLearn* families (`return *writeback;`) and the Sql/CypherQuery/GraphQl variants.
/// SQL and GraphQL are parsed here; Cypher carries a required declared mode which the
/// handler independently verifies against the native parser before execution.
/// `policy()`'s `mutates: true` for these is a conservative UPPER BOUND, not an equality --
/// the real answer depends on data the static table cannot see.
pub(crate) const ACCESS_RS_MUTATES_CONDITIONAL: &[&str] = &[
    // Publish/Retire write; Current/History/Status remain authenticated reads.
    // All four RF-ADR-008 agent-hierarchy layers have this shape: each
    // delegates `access::requires_write` to its own op's `is_mutation()`,
    // while the registry row carries the conservative `mutates = true` upper
    // bound. `AgentComponent`'s `Search` and `AgentTemplate`'s `Instantiate`
    // are reads for the same reason the `Current`/`History` arms are.
    "AgentComponent",
    "AgentGraph",
    "AgentLibrary",
    "AgentTemplate",
    "CypherQuery",
    "GraphLearnFit",
    "GraphLearnPredict",
    "GraphQl",
    "MineAnomaly",
    "MineAssociate",
    "MineCausalImpact",
    "MineClassifyPredict",
    "MineCluster",
    "MineCommunity",
    "MineEntityResolve",
    "MineForecast",
    "MineOntologyGap",
    "MineProcess",
    "MineReduce",
    "MineRetrievalQuality",
    "MineRiskPropagation",
    "MineRootCause",
    "MineSequence",
    "MineSubgraph",
    "MineText",
    "MiningPipelineTrain",
    "MiningPipelinePredict",
    "Sql",
    #[cfg(feature = "modality-serving")]
    "ServedModality",
];

/// Mirrors `access.rs`'s ONE explicit-false special case: `MineClassifyFit` always returns
/// `false` from `requires_write` regardless of any field (it never writes back).
pub(crate) const ACCESS_RS_MUTATES_EXPLICIT_FALSE: &[&str] = &["MineClassifyFit"];

/// Mirrors `src/mutation_apply.rs::is_durable_mutation`'s GraphRedb-domain true set (the plain
/// node/edge/memory/scene/trajectory primitives + RDF triples + the writeback-true Mine*/
/// GraphLearn* variants that DO make the durable list).
pub(crate) const MUTATION_APPLY_DURABLE_GRAPHREDB: &[&str] = &[
    "AddEdge",
    "AddEmbedding",
    "AddNode",
    "AddSceneObject",
    "AddTriples",
    "AppendStep",
    "BatchUpdate",
    "CancelWorkItem",
    "CasWorkItemMetadata",
    "ClaimNext",
    "ClaimWorkItem",
    "ClearGraph",
    "CompareAndSetNodeFields",
    "CommitWorkItemResult",
    "Consolidate",
    "CreateNodeIfAbsent",
    "CreateSummaryNode",
    "DecayMemories",
    "DecayNode",
    "DeferWorkItem",
    "DropNamedGraph",
    "EvictBelow",
    "GraphLearnFit",
    "GraphLearnPredict",
    "InvalidateEdge",
    "Maintain",
    "MineAnomaly",
    "MineAssociate",
    "MineCausalImpact",
    "MineClassifyPredict",
    "MineCluster",
    "MineCommunity",
    "MineEntityResolve",
    "MineForecast",
    "MineOntologyGap",
    "MineProcess",
    "MineReduce",
    "MineRetrievalQuality",
    "MineRiskPropagation",
    "MineRootCause",
    "MineSequence",
    "MineSubgraph",
    "MineText",
    "Reinforce",
    "RemoveEdge",
    "RemoveNode",
    "RemoveTriples",
    "Reparent",
    "RenewWorkItemLease",
    "SetPose",
    "StartTrajectory",
    "SupersedeEdge",
    #[cfg(feature = "modality-serving")]
    "ServedModality",
];
// NOTE: `RegisterServer` (W2.5) is intentionally ABSENT from this list -- it self-translates
// into `Method::AddNode` (see `NATIVE_GRAPHREDB_DURABLE` below), so `AddNode` above already
// carries the real `mutation_apply::is_durable_mutation` classification for its effect.

/// GraphRedb operations that own a native transaction/status/outbox commit point
/// outside the per-method graph mutation-applier classifier.
pub(crate) const NATIVE_GRAPHREDB_DURABLE: &[&str] = &[
    "ApplyChangeEnvelope",
    "ApplyChangeEnvelopes",
    "ApplyLedger",
    "ApplyMultisigMutation",
    "ApplyMutation",
    "ClearLedger",
    "CompactNodesByType",
    "CreateGraph",
    "CypherQuery",
    "DecaySweep",
    "DeleteGraph",
    "EvictLRU",
    "FromMsgpack",
    "GraphQl",
    "IcvConfigure",
    // Mining pipeline writes are committed by the dedicated pipeline handler,
    // not by mutation_apply's graph-core replay classifier.
    "MiningPipelinePredict",
    "MiningPipelineServe",
    "MiningPipelineTrain",
    "PruneByLifecycle",
    // RMDD-27: native GraphRedb reservation/host transactions bypass the
    // graph-core mutation applier and commit their resource indexes in the
    // MutationBatch transaction.
    "ReclaimWorkItemResources",
    "Reconcile",
    "ReleaseWorkItemResources",
    "ReserveWorkItemResources",
    // W2.5: self-translates into `Method::AddNode` (dispatch.rs) BEFORE any durable
    // commit -- exactly the "ApplyMultisigMutation -> ApplyMutation" shape above --
    // so its real durability is AddNode's own MUTATION_APPLY_DURABLE_GRAPHREDB entry.
    "RegisterServer",
    "RunDatalogReasoning",
    "Sql",
    "TouchNodes",
    "UpdateResourceHost",
    "MintWorkItemClaimCapability",
    "VerifyWorkItemClaimCapability",
    "ReserveDevelopmentLane",
    "RenewDevelopmentLane",
    "ObserveDevelopmentLane",
    "FinishDevelopmentLane",
    "CleanupDevelopmentLane",
    "UpdateDevelopmentLaneQuota",
    "KgDelegate",
    "SubmitWorkItem",
    "SubmitWorkItems",
    "AcquireCapacity",
    "RenewCapacity",
    "ReleaseCapacity",
    "ReclaimExpiredCapacity",
    "UpdateCapacityCell",
];

/// Mirrors `src/mutation_apply.rs::is_durable_mutation`'s message-broker/stream true set.
pub(crate) const MUTATION_APPLY_DURABLE_OUTBOX: &[&str] = &[
    "BindQueue",
    "BrokerAck",
    "BrokerAckTag",
    "BrokerConsume",
    "BrokerNackTag",
    "BrokerReject",
    "BrokerRenewTag",
    "DeclareExchange",
    "DeclareQueue",
    "DeleteExchange",
    "Publish",
    "PublishConfirmed",
    "PublishEx",
    "PublishIdempotent",
    "StreamCommitOffset",
    "StreamDeclare",
    "StreamPublish",
    "StreamTrim",
    "SweepExpired",
    "UnbindQueue",
];

/// Mirrors `src/audit.rs::audit_line`'s explicit match (everything else falls to its
/// `_ => return None` catch-all, i.e. NOT chained into the tamper-evident hash log).
///
/// L3/EG-P0-6: originally just the 2 (later 7, after EG-P0-2) node/edge CRUD
/// primitives -- `audit_line` is now EXHAUSTIVE over every `GraphRedb`- and
/// `Outbox`-domain durable mutation (every durable mutation actually reaches
/// `redb_store::append_audit_entry` via `record`/`record_durable` ->
/// `commit_ops`/`commit_crossmodal`, gateway-routed or not), so this mirror grows
/// with the durable surface and is compared exactly below.
pub(crate) const AUDIT_RS_AUDITED: &[&str] = &[
    "AddEdge",
    "AddEmbedding",
    "AddNode",
    "AddSceneObject",
    "AddTriples",
    "AppendStep",
    "ApplyChangeEnvelope",
    "ApplyChangeEnvelopes",
    "ApplyLedger",
    "ApplyMultisigMutation",
    "ApplyMutation",
    "BatchUpdate",
    "BindQueue",
    "BrokerAck",
    "BrokerAckTag",
    "BrokerConsume",
    "BrokerNackTag",
    "BrokerReject",
    "BrokerRenewTag",
    "CancelWorkItem",
    "CasWorkItemMetadata",
    "ClaimNext",
    "ClaimWorkItem",
    "KgDelegate",
    "SubmitWorkItem",
    "SubmitWorkItems",
    "AcquireCapacity",
    "RenewCapacity",
    "ReleaseCapacity",
    "ReclaimExpiredCapacity",
    "UpdateCapacityCell",
    "ClearGraph",
    "ClearLedger",
    "CompactNodesByType",
    "CompareAndSetNodeFields",
    "CommitWorkItemResult",
    "Consolidate",
    "CreateNodeIfAbsent",
    "CreateSummaryNode",
    "CypherQuery",
    "DecayMemories",
    "DecayNode",
    "DeferWorkItem",
    "DeclareExchange",
    "DeclareQueue",
    "DeleteExchange",
    "DropNamedGraph",
    "EvictBelow",
    "ExportSqliteFile",
    "FromMsgpack",
    "GraphLearnFit",
    "GraphLearnPredict",
    "GraphQl",
    "IcvConfigure",
    "ImportSqliteFile",
    "InvalidateEdge",
    "Maintain",
    "MineAnomaly",
    "MineAssociate",
    "MineCausalImpact",
    "MineClassifyPredict",
    "MineCluster",
    "MineCommunity",
    "MineEntityResolve",
    "MineForecast",
    "MineOntologyGap",
    "MineProcess",
    "MineReduce",
    "MineRetrievalQuality",
    "MineRiskPropagation",
    "MineRootCause",
    "MineSequence",
    "MineSubgraph",
    "MineText",
    "MiningPipelinePredict",
    "MiningPipelineServe",
    "MiningPipelineTrain",
    "Publish",
    "PublishConfirmed",
    "PublishEx",
    "PublishIdempotent",
    "ReclaimWorkItemResources",
    "Reconcile",
    "ReleaseWorkItemResources",
    "Reinforce",
    "RegisterServer",
    "RemoveEdge",
    "RemoveNode",
    "RemoveTriples",
    "Reparent",
    "RenewWorkItemLease",
    "ReserveWorkItemResources",
    "RunDatalogReasoning",
    "SetPose",
    "Sql",
    "StartTrajectory",
    "StreamCommitOffset",
    "StreamDeclare",
    "StreamPublish",
    "StreamTrim",
    "SupersedeEdge",
    "SweepExpired",
    "UnbindQueue",
    "UpdateResourceHost",
    "ReserveDevelopmentLane",
    "RenewDevelopmentLane",
    "ObserveDevelopmentLane",
    "FinishDevelopmentLane",
    "CleanupDevelopmentLane",
    "UpdateDevelopmentLaneQuota",
    #[cfg(feature = "modality-serving")]
    "ServedModality",
];

/// Mirrors `src/server/cdc.rs::emit_for_method`'s explicit match (everything else falls to
/// its `_ => {}` catch-all, i.e. emits NO Change-Data-Capture event).
/// Native resource rows are controller-plane capacity/accounting state, not
/// GraphCore node/edge state; their typed results/status and audit lines are the
/// reconciliation surfaces, so `emits_cdc: false` is deliberate.
pub(crate) const CDC_RS_EMITS_CDC: &[&str] = &[
    "AddEdge",
    "AddNode",
    "ApplyChangeEnvelope",
    "ApplyChangeEnvelopes",
    "ApplyLedger",
    "ApplyMultisigMutation",
    "ApplyMutation",
    "ClearGraph",
    "ClearLedger",
    "CompactNodesByType",
    "CompareAndSetNodeFields",
    "CreateNodeIfAbsent",
    "FromMsgpack",
    "IcvConfigure",
    "Reconcile",
    "RegisterServer",
    "RemoveEdge",
    "RemoveNode",
    "RunDatalogReasoning",
    #[cfg(feature = "modality-serving")]
    "ServedModality",
];

// ── KNOWN_DIVERGENCE ────────────────────────────────────────────────────────────────
//
