#!/usr/bin/env python3
"""Differential gate for the facade-full test suite.

`main` is legitimately RED here: the facade-full row carries a set of
long-standing failures that predate any one change, and for a long time they
were invisible because the suite ABORTED on a stack overflow before reporting.
An absolute-green push gate over that state is a deadlock -- it blocks every
fix, including the fixes for the very failures it is complaining about.

So this is a RATCHET keyed by test NAME, exactly like the concept-governance
and swallowed-error gates already in this fleet, and exactly like the merge
queue's own differential gating (which compares a candidate against a base-ref
baseline rather than demanding absolute green):

* FAIL on any failing test NOT in the baseline -- a real regression, always.
* PASS over a baselined failure -- known debt, tracked, cleaned up deliberately.
* REPORT baselined tests that now pass, so the baseline only ever shrinks.

A name key (not a count) is deliberate: a count cannot tell "a new failure
appeared" from "an old one was fixed and a different old one remains", and is
trivially satisfied by fixing something unrelated.

Run with --update-baseline after fixing or knowingly accepting a batch.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASELINE = ROOT / "scripts" / "facade_full_test_baseline.txt"
# `test <name> ... FAILED` in libtest output.
FAILED_RE = re.compile(r"^test (\S+) \.\.\. FAILED\s*$", re.M)


def load_baseline() -> set[str]:
    if not BASELINE.is_file():
        return set()
    return {
        line.strip()
        for line in BASELINE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    }


def write_baseline(names: set[str]) -> None:
    header = (
        "# Facade-full tests known to FAIL, accepted as tracked debt.\n"
        "# Generated by `scripts/cargo_test_ratchet.py --update-baseline`.\n"
        "# RATCHET: the gate fails on any failing test NOT listed here.\n"
        "# This list must only ever SHRINK.\n"
    )
    BASELINE.write_text(header + "\n".join(sorted(names)) + "\n", encoding="utf-8")


def run_suite(extra: list[str]) -> tuple[str, int]:
    cmd = ["cargo", "test", "-p", "epistemic-graph", "--features", "full", *extra]
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    return proc.stdout + proc.stderr, proc.returncode


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--update-baseline", action="store_true")
    ap.add_argument("cargo_args", nargs="*", default=[])
    args = ap.parse_args()

    output, code = run_suite(args.cargo_args)
    failing = set(FAILED_RE.findall(output))

    # A crash (stack overflow / SIGABRT) reports no per-test FAILED lines but
    # still exits non-zero. That must never be mistaken for "no new failures":
    # it is the single most destructive outcome, because it hides every result
    # behind it -- which is exactly how these failures stayed invisible.
    if code != 0 and not failing:
        print("cargo test failed WITHOUT reporting individual test failures.")
        print("That is a crash/abort, not a test result -- refusing to ratchet over it.")
        print(output[-4000:])
        return 1

    if args.update_baseline:
        write_baseline(failing)
        print(f"baseline updated: {len(failing)} known-failing test(s)")
        return 0

    baseline = load_baseline()
    new = sorted(failing - baseline)
    fixed = sorted(baseline - failing)

    if fixed:
        print(f"{len(fixed)} baselined test(s) now PASS -- shrink the baseline:")
        for name in fixed[:20]:
            print(f"  + {name}")
        print("  run: python scripts/cargo_test_ratchet.py --update-baseline")

    if new:
        print(f"\nREGRESSION: {len(new)} test(s) failing that are not baselined:")
        for name in new:
            print(f"  - {name}")
        print("\nFix them, or -- if deliberately accepted -- re-baseline with a reason.")
        return 1

    print(f"facade-full ratchet OK: {len(failing)} known failure(s), 0 new.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
