#!/usr/bin/env python3
"""Run the immutable, advisory full-tree dupehound census.

The existing :mod:`check_dupehound` wrapper is deliberately a changed-source
gate.  This adapter is a separate census surface: it archives one commit,
classifies every tree entry, runs the pinned ``dupehound scan`` command over
that immutable materialization, and emits a ``scanner-evidence/v2`` receipt.
It never writes a baseline and it never turns native exit ``0`` into a claim
that a tree has no duplicate functions.

Only the standard library and the repository's checked-in scanner contract
are used.  A missing identity, malformed report, path/source mismatch, or
tool drift exits ``2`` (``cannot_run``).  A complete census exits ``0``;
clusters remain visible advisory findings in the receipt.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import io
import json
import math
import os
import re
import subprocess
import sys
import tarfile
import tempfile
import unicodedata
import uuid
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath, PureWindowsPath
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))

import check_dupehound  # noqa: E402
import scanner_contract  # noqa: E402

REPOSITORY = "agent-packages/epistemic-graph"
PROFILE_ID = "dupehound-full-tree-v1:epistemic-graph"
EXPECTED_UNIVERSE_ID = "dupehound-source-universe-v1:epistemic-graph"
STAGE_POLICY_ID = "scanner-stage:release-full-census-advisory-v1"
ALGORITHM_ID = "dupehound:function-clone:v1"
THRESHOLD_POLICY_ID = "dupehound-threshold:0.85:min-tokens:40"
THREAD_BOUND = 8
SCAN_TIMEOUT_SECONDS = 900
MAX_FILE_BYTES = 2 * 1024 * 1024
EXPECTED_SCHEMA_VERSION = 1
INLINE_TEST_PROJECTION_ID = "dupehound-inline-test-projection:v1"

_FULL_SHA = re.compile(r"^[0-9a-f]{40,64}$")
_GENERATED_MARKERS = (
    "@generated",
    "do not edit",
    "auto-generated",
    "autogenerated",
    "code generated by",
)
_VENDOR_NAMES = frozenset({"vendor", "third_party"})
_FIXTURE_NAMES = frozenset({"fixture", "fixtures", "__snapshots__"})
_DOCUMENTATION_NAMES = frozenset(
    {"doc", "docs", "documentation", "example", "examples", "sample", "samples"}
)
_GENERATED_NAMES = frozenset(
    {
        ".cache",
        ".import_linter_cache",
        ".venv",
        "build",
        "cache",
        "dist",
        "generated",
        "node_modules",
        "out",
        "target",
        "venv",
    }
)
_NATIVE_DEFAULT_EXCLUSIONS = (
    "**/node_modules/**",
    "**/vendor/**",
    "**/third_party/**",
    "**/dist/**",
    "**/build/**",
    "**/out/**",
    "**/target/**",
    "**/.next/**",
    "**/.nuxt/**",
    "**/.venv/**",
    "**/venv/**",
    "**/__pycache__/**",
    "**/.git/**",
    "**/*.min.js",
    "**/*.min.mjs",
    "**/*.bundle.js",
    "**/*.pb.go",
    "**/*_pb2.py",
    "**/*_pb2.pyi",
    "**/*_pb2_grpc.py",
    "**/*.gen.go",
    "**/*.gen.ts",
    "**/*.d.ts",
    "**/*.generated.*",
)
_CLASS_ORDER = (
    "production",
    "test",
    "generated",
    "vendor",
    "fixture",
    "documentation",
    "unsupported",
    "hidden",
    "oversize",
    "invalid_encoding",
    "non_regular",
    "minified",
)

# This is the closed profile table from the approved changed-source wrapper.
# Importing SUPPORTED_SUFFIXES and is_dupehound_test_path keeps the two EG
# adapters on one command/classifier authority.  The language labels are
# census profile data and are intentionally explicit here.
LANGUAGE_EXTENSIONS: dict[str, tuple[str, ...]] = {
    "c": (".c", ".h"),
    "cpp": (".cc", ".cpp", ".cxx", ".c++", ".hpp", ".hh", ".hxx"),
    "csharp": (".cs",),
    "go": (".go",),
    "java": (".java",),
    "javascript": (".js", ".mjs", ".cjs", ".jsx"),
    "php": (".php",),
    "python": (".py", ".pyi"),
    "ruby": (".rb",),
    "rust": (".rs",),
    "swift": (".swift",),
    "typescript": (".ts", ".mts", ".cts"),
    "tsx": (".tsx",),
}
EXTENSION_LANGUAGE = {
    extension: language
    for language, extensions in LANGUAGE_EXTENSIONS.items()
    for extension in extensions
}


class CensusError(RuntimeError):
    """A fail-closed census error with optional native process output."""

    def __init__(
        self,
        message: str,
        *,
        code: str = "cannot_run",
        raw: bytes = b"",
        stderr: bytes = b"",
    ) -> None:
        super().__init__(message)
        self.code = code
        self.raw = raw
        self.stderr = stderr


@dataclass(frozen=True)
class TreeEntry:
    path: str
    mode: str
    object_type: str
    object_sha: str

    @property
    def regular(self) -> bool:
        return self.object_type == "blob" and self.mode in {"100644", "100755"}


@dataclass(frozen=True)
class ClassifiedEntry:
    path: str
    mode: str
    object_sha: str | None
    language: str | None
    class_name: str
    reason: str
    content_sha256: str | None


@dataclass
class MaterializedTree:
    root: Path
    contents: dict[str, bytes]
    materialized_root_sha256: str
    _temporary: tempfile.TemporaryDirectory[str]

    def close(self) -> None:
        self._temporary.cleanup()


@dataclass
class CandidateContext:
    commit: str
    tree: str
    entries: list[TreeEntry]
    tree_listing_sha256: str
    config: scanner_contract.ScannerContract
    profile: dict[str, Any]
    profile_sha256: str
    universe_sha256: str
    stage_policy_sha256: str
    config_items: list[dict[str, str]]
    executable: str | None
    tool: dict[str, Any]
    manifest: dict[str, Any] | None = None


def canonical_json(value: object) -> bytes:
    """Return the repository's compact, sorted UTF-8 JSON representation."""

    try:
        return (
            json.dumps(
                value,
                ensure_ascii=False,
                allow_nan=False,
                sort_keys=True,
                separators=(",", ":"),
            ).encode("utf-8")
            + b"\n"
        )
    except (TypeError, ValueError, UnicodeEncodeError) as exc:
        raise CensusError(f"cannot canonicalize evidence: {exc}") from exc


def digest_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def digest_json(value: object) -> str:
    return digest_bytes(canonical_json(value))


def _path_text(raw: str | bytes) -> str:
    if isinstance(raw, bytes):
        try:
            value = raw.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise CensusError("git tree contains a non-UTF-8 path") from exc
    elif isinstance(raw, str):
        value = raw
    else:
        raise CensusError("tree path is not text")
    return value


def _validate_path_text(value: str) -> str:
    if not value or "\x00" in value or "\\" in value:
        raise CensusError("tree path is empty, NUL-containing, or backslash-ambiguous")
    if any(ord(char) < 0x20 for char in value):
        raise CensusError("tree path contains a control character")
    if unicodedata.normalize("NFC", value) != value:
        raise CensusError(f"tree path is not NFC-normalized: {value!r}")
    return value


def _validate_path_shape(value: str) -> str:
    posix = PurePosixPath(value)
    windows = PureWindowsPath(value)
    if posix.is_absolute() or windows.is_absolute() or windows.drive:
        raise CensusError(f"tree path is absolute: {value!r}")
    if any(part in {"", ".", ".."} for part in posix.parts):
        raise CensusError(f"tree path has an unsafe component: {value!r}")
    normalized_path = posix.as_posix()
    if normalized_path != value:
        raise CensusError(f"tree path is not canonically slash-separated: {value!r}")
    return normalized_path


def _safe_path(raw: str | bytes) -> str:
    return _validate_path_shape(_validate_path_text(_path_text(raw)))


def _git_bytes(args: list[str], *, timeout: int = 120) -> bytes:
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=str(ROOT),
            env=scanner_contract.sanitized_env(),
            capture_output=True,
            text=False,
            timeout=timeout,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise CensusError(f"could not execute git: {exc}") from exc
    if result.returncode != 0:
        detail = result.stderr.decode("utf-8", "replace").strip()[:400]
        raise CensusError(f"git {' '.join(args)} failed: {detail}")
    return result.stdout


def _resolve_candidate(ref: str) -> tuple[str, str]:
    commit = _git_bytes(["rev-parse", "--verify", f"{ref}^{{commit}}"]).decode().strip()
    if not _FULL_SHA.fullmatch(commit):
        raise CensusError("candidate commit did not resolve to a full object ID")
    tree = _git_bytes(["show", "-s", "--format=%T", commit]).decode().strip()
    if not _FULL_SHA.fullmatch(tree):
        raise CensusError("candidate commit did not resolve to a full tree ID")
    _git_bytes(["cat-file", "-e", f"{commit}^{{commit}}"])
    _git_bytes(["cat-file", "-e", f"{tree}^{{tree}}"])
    return commit, tree


def _tree_entries(commit: str) -> list[TreeEntry]:
    raw = _git_bytes(["ls-tree", "-r", "-z", "--full-tree", commit])
    entries: list[TreeEntry] = []
    seen: set[str] = set()
    for record in raw.split(b"\x00"):
        if not record:
            continue
        try:
            header, path_bytes = record.split(b"\t", 1)
            mode_bytes, type_bytes, object_bytes = header.split(b" ", 2)
            mode = mode_bytes.decode("ascii")
            object_type = type_bytes.decode("ascii")
            object_sha = object_bytes.decode("ascii")
        except (ValueError, UnicodeDecodeError) as exc:
            raise CensusError("git tree listing has a malformed record") from exc
        path = _safe_path(path_bytes)
        if path in seen:
            raise CensusError(f"git tree listing has a duplicate path: {path}")
        if not _FULL_SHA.fullmatch(object_sha):
            raise CensusError(f"git tree listing has an invalid object ID: {path}")
        seen.add(path)
        entries.append(TreeEntry(path, mode, object_type, object_sha))
    entries.sort(key=lambda entry: entry.path.encode("utf-8"))
    return entries


def tree_listing_digest(entries: list[TreeEntry]) -> str:
    records = [
        entry.path.encode("utf-8")
        + b"\x00"
        + entry.mode.encode("ascii")
        + b"\x00"
        + entry.object_sha.encode("ascii")
        + b"\n"
        for entry in sorted(entries, key=lambda item: item.path.encode("utf-8"))
    ]
    return digest_bytes(b"".join(records))


def _blob_sha(data: bytes) -> str:
    # EG currently uses SHA-1 object IDs.  Computing the Git blob preimage
    # locally avoids a per-file mutable checkout lookup and proves archive
    # bytes match the immutable tree listing.
    return hashlib.sha1(
        b"blob " + str(len(data)).encode("ascii") + b"\x00" + data
    ).hexdigest()


def _archive_member_path(raw: str) -> str:
    return _safe_path(raw)


def _archive_bytes(commit: str) -> bytes:
    try:
        archive = subprocess.run(
            ["git", "archive", "--format=tar", commit],
            cwd=str(ROOT),
            env=scanner_contract.sanitized_env(),
            capture_output=True,
            text=False,
            timeout=120,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise CensusError(f"could not materialize candidate tree: {exc}") from exc
    if archive.returncode != 0:
        detail = archive.stderr.decode("utf-8", "replace").strip()[:400]
        raise CensusError(f"git archive failed: {detail}")
    return archive.stdout


def _read_archive_file(
    member: tarfile.TarInfo,
    archive: tarfile.TarFile,
    path: str,
    entry: TreeEntry,
    seen: set[str],
) -> tuple[str, bytes]:
    if not member.isfile() or member.issym() or member.islnk():
        raise CensusError(f"archive contains a non-regular path: {path}")
    if path in seen:
        raise CensusError(f"archive contains a duplicate file: {path}")
    mode = "100755" if member.mode & 0o111 else "100644"
    if mode != entry.mode:
        raise CensusError(f"archive mode mismatch for {path}")
    source = archive.extractfile(member)
    if source is None:
        raise CensusError(f"archive file could not be read: {path}")
    data = source.read()
    if _blob_sha(data) != entry.object_sha:
        raise CensusError(f"archive bytes do not match tree blob: {path}")
    return mode, data


def _write_archive_file(root: Path, path: str, mode: str, data: bytes) -> None:
    destination = root / Path(*PurePosixPath(path).parts)
    destination.parent.mkdir(parents=True, exist_ok=True)
    if any(
        parent.is_symlink()
        for parent in [destination.parent, *destination.parent.parents]
    ):
        raise CensusError(f"archive extraction encountered symlink traversal: {path}")
    destination.write_bytes(data)
    if mode == "100755":
        destination.chmod(0o755)


def _extract_archive_member(
    member: tarfile.TarInfo,
    archive: tarfile.TarFile,
    root: Path,
    tree_by_path: dict[str, TreeEntry],
    seen: set[str],
) -> tuple[str, bytes] | None:
    if member.isdir():
        _safe_path(member.name)
        return None
    path = _archive_member_path(member.name)
    entry = tree_by_path.get(path)
    if entry is None:
        raise CensusError(f"archive contains an unlisted file: {path}")
    if not entry.regular:
        if member.issym() or member.islnk():
            # The manifest retains the tracked non-regular path; the target
            # is never extracted or followed.
            return None
        raise CensusError(f"archive contains an unsupported non-regular path: {path}")
    mode, data = _read_archive_file(member, archive, path, entry, seen)
    _write_archive_file(root, path, mode, data)
    return path, data


def _materialized_listing(
    contents: dict[str, bytes], expected: dict[str, TreeEntry], seen: set[str]
) -> str:
    missing = sorted(set(expected) - seen)
    if missing:
        raise CensusError(f"archive omitted tracked regular path: {missing[0]}")
    listing = b"".join(
        path.encode("utf-8")
        + b"\x00"
        + expected[path].mode.encode("ascii")
        + b"\x00"
        + digest_bytes(contents[path]).encode("ascii")
        + b"\n"
        for path in sorted(contents, key=lambda value: value.encode("utf-8"))
    )
    return digest_bytes(listing)


@contextmanager
def materialize(commit: str, entries: list[TreeEntry]) -> Iterator[MaterializedTree]:
    temporary = tempfile.TemporaryDirectory(
        prefix=".dupehound-census-", dir=str(ROOT.parent)
    )
    root = Path(temporary.name)
    expected = {entry.path: entry for entry in entries if entry.regular}
    contents: dict[str, bytes] = {}
    seen: set[str] = set()
    try:
        try:
            archive = tarfile.open(
                fileobj=io.BytesIO(_archive_bytes(commit)), mode="r:"
            )
        except (tarfile.TarError, OSError) as exc:
            raise CensusError(f"candidate archive is invalid: {exc}") from exc
        tree_by_path = {entry.path: entry for entry in entries}
        with archive:
            for member in archive:
                extracted = _extract_archive_member(
                    member, archive, root, tree_by_path, seen
                )
                if extracted is not None:
                    path, data = extracted
                    contents[path] = data
                    seen.add(path)
        listing_sha256 = _materialized_listing(contents, expected, seen)
        yield MaterializedTree(root, contents, listing_sha256, temporary)
    finally:
        temporary.cleanup()


def _matching_exclusion(
    path: str, config: scanner_contract.ScannerContract
) -> str | None:
    for pattern in profile_exclusions(config):
        if scanner_contract._glob_match(path, pattern):
            return pattern
    return None


def profile_exclusions(config: scanner_contract.ScannerContract) -> list[str]:
    """Return the sorted explicit union of repo and native exclusions."""

    return sorted(set(config.exclusions).union(_NATIVE_DEFAULT_EXCLUSIONS))


def _path_class_for_exclusion(path: str) -> str:
    parts = {part.casefold() for part in PurePosixPath(path).parts}
    if parts & _VENDOR_NAMES:
        return "vendor"
    if parts & _FIXTURE_NAMES:
        return "fixture"
    if parts & _DOCUMENTATION_NAMES:
        return "documentation"
    if parts & _GENERATED_NAMES:
        return "generated"
    # The remaining explicit profile exclusions are build/cache/lock policy
    # entries.  Supported-language paths in them are generated artifacts from
    # the scanner's perspective; unsupported lockfiles are classified before
    # this function is reached.
    return "generated"


def _is_hidden(path: str) -> bool:
    return any(part.startswith(".") for part in PurePosixPath(path).parts)


def _generated_marker(text: str) -> bool:
    first_ten = "\n".join(text.splitlines()[:10]).casefold()
    return any(marker in first_ten for marker in _GENERATED_MARKERS)


def _minified(text: str) -> bool:
    lines = text.splitlines() or [text]
    # Dupehound's Rust walker measures UTF-8 byte lengths and uses integer
    # division for the average; mirror that behavior so skip counters join
    # exactly rather than approximating it with Python character counts.
    lengths = [len(line.encode("utf-8")) for line in lines]
    return max(lengths, default=0) > 2000 or sum(lengths) // len(lengths) > 300


def _entry_for_nonregular(entry: TreeEntry) -> ClassifiedEntry:
    return ClassifiedEntry(
        entry.path, entry.mode, None, None, "non_regular", "mode.non_regular", None
    )


def _entry_for_unsupported(entry: TreeEntry, content_sha: str) -> ClassifiedEntry:
    return ClassifiedEntry(
        entry.path,
        entry.mode,
        entry.object_sha,
        None,
        "unsupported",
        "language.unsupported",
        content_sha,
    )


def _classify_path(
    entry: TreeEntry,
    language: str,
    content_sha: str,
    config: scanner_contract.ScannerContract,
) -> ClassifiedEntry | None:
    exclusion = _matching_exclusion(entry.path, config)
    if exclusion is not None:
        return ClassifiedEntry(
            entry.path,
            entry.mode,
            entry.object_sha,
            language,
            _path_class_for_exclusion(entry.path),
            f"path.exclusion:{exclusion}",
            content_sha,
        )
    if check_dupehound.is_dupehound_test_path(entry.path):
        return ClassifiedEntry(
            entry.path,
            entry.mode,
            entry.object_sha,
            language,
            "test",
            "path.test",
            content_sha,
        )
    if _is_hidden(entry.path):
        return ClassifiedEntry(
            entry.path,
            entry.mode,
            entry.object_sha,
            language,
            "hidden",
            "path.hidden",
            content_sha,
        )
    return None


def _classify_content(
    entry: TreeEntry, data: bytes, language: str, content_sha: str
) -> ClassifiedEntry:
    # The native walker checks the byte size before loading content.  An
    # oversized file therefore cannot become a generated/minified counter;
    # it is omitted before content classification regardless of its prefix.
    if len(data) > MAX_FILE_BYTES:
        return ClassifiedEntry(
            entry.path,
            entry.mode,
            entry.object_sha,
            language,
            "oversize",
            "content.oversize_2mib",
            content_sha,
        )
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return ClassifiedEntry(
            entry.path,
            entry.mode,
            entry.object_sha,
            language,
            "invalid_encoding",
            "content.invalid_utf8",
            content_sha,
        )
    if _generated_marker(text):
        return ClassifiedEntry(
            entry.path,
            entry.mode,
            entry.object_sha,
            language,
            "generated",
            "content.generated_marker",
            content_sha,
        )
    if _minified(text):
        return ClassifiedEntry(
            entry.path,
            entry.mode,
            entry.object_sha,
            language,
            "minified",
            "content.minified",
            content_sha,
        )
    return ClassifiedEntry(
        entry.path,
        entry.mode,
        entry.object_sha,
        language,
        "production",
        "source.production",
        content_sha,
    )


def _classify_entry(
    entry: TreeEntry,
    contents: dict[str, bytes],
    config: scanner_contract.ScannerContract,
) -> ClassifiedEntry:
    if not entry.regular:
        return _entry_for_nonregular(entry)
    data = contents.get(entry.path)
    if data is None:
        raise CensusError(f"materialization did not provide {entry.path}")
    content_sha = digest_bytes(data)
    # Lang::from_path uses the final extension verbatim; uppercase variants
    # are outside the native language universe and must remain unsupported.
    suffix = PurePosixPath(entry.path).suffix
    language = EXTENSION_LANGUAGE.get(suffix)
    # This closed map mirrors dupehound's Lang::from_path table.  The older
    # changed-source wrapper intentionally has a narrower Python suffix set;
    # using it here would incorrectly turn native C++ ``.c++`` inputs into
    # unsupported paths.
    if language is None:
        return _entry_for_unsupported(entry, content_sha)
    path_entry = _classify_path(entry, language, content_sha, config)
    return path_entry or _classify_content(entry, data, language, content_sha)


def classify_entries(
    entries: list[TreeEntry],
    contents: dict[str, bytes],
    config: scanner_contract.ScannerContract,
) -> list[ClassifiedEntry]:
    classified = [_classify_entry(entry, contents, config) for entry in entries]
    classified.sort(key=lambda item: item.path.encode("utf-8"))
    if len({item.path for item in classified}) != len(classified):
        raise CensusError("manifest classification produced duplicate paths")
    if {item.path for item in classified} != {item.path for item in entries}:
        raise CensusError("manifest classification does not cover the tree listing")
    return classified


def profile_definition(config: scanner_contract.ScannerContract) -> dict[str, Any]:
    return {
        "id": PROFILE_ID,
        "instrument": "dupehound",
        "scope_kind": "full_census",
        "comparison_mode": "census",
        "claim": "conformance_only",
        "decision": "advisory",
        "tool_version": config.dupehound_version,
        "threshold": config.dupehound_threshold,
        "min_tokens": config.dupehound_min_tokens,
        "exclude_tests": True,
        "no_default_excludes": True,
        "thread_bound": THREAD_BOUND,
        "timeout_seconds": SCAN_TIMEOUT_SECONDS,
        "exclusions": profile_exclusions(config),
        "native_default_exclusions": sorted(_NATIVE_DEFAULT_EXCLUSIONS),
        "language_extensions": {
            language: list(extensions)
            for language, extensions in sorted(LANGUAGE_EXTENSIONS.items())
        },
        "classification_precedence": [
            "non_regular",
            "unsupported",
            "profile_exclusion",
            "test",
            "hidden",
            "generated",
            "oversize",
            "invalid_encoding",
            "minified",
            "production",
        ],
        "native_skip_rules": {
            "generated_markers": list(_GENERATED_MARKERS),
            "hidden_walker": "WalkBuilder.hidden(true)",
            "oversize_bytes": MAX_FILE_BYTES,
            "minified_line_chars": 2000,
            "minified_average_line_chars": 300,
        },
        "test_projection": {
            "id": INLINE_TEST_PROJECTION_ID,
            "path_policy": "exclude path-classified test files",
            "inline_member_policy": "retain native test members as telemetry",
            "finding_minimum_non_test_members": 2,
        },
    }


def universe_definition() -> dict[str, Any]:
    return {
        "id": EXPECTED_UNIVERSE_ID,
        "supported_suffixes": sorted(EXTENSION_LANGUAGE),
        "language_extensions": {
            language: list(extensions)
            for language, extensions in sorted(LANGUAGE_EXTENSIONS.items())
        },
        "test_directories": sorted(check_dupehound._TEST_DIRECTORY_NAMES),
        "test_suffixes": list(check_dupehound._TEST_FILE_SUFFIXES),
    }


def stage_policy_definition() -> dict[str, Any]:
    return {
        "id": STAGE_POLICY_ID,
        "stage": "release",
        "scope_kind": "full_census",
        "instrument": "dupehound",
        "decision": "advisory",
        "claim": "conformance_only",
        "comparison_mode": "census",
        "metrics": [ALGORITHM_ID],
    }


def _source_digest(entries: list[ClassifiedEntry]) -> str:
    records = [
        entry.path.encode("utf-8") + b"\x00" + entry.class_name.encode("ascii") + b"\n"
        for entry in entries
        if entry.class_name == "production"
    ]
    return digest_bytes(b"".join(records))


def _path_counts(entries: list[ClassifiedEntry]) -> dict[str, int]:
    counts = {class_name: 0 for class_name in _CLASS_ORDER}
    for entry in entries:
        counts[entry.class_name] += 1
    return counts


def build_manifest(
    *,
    commit: str,
    tree: str,
    tree_listing_sha256: str,
    materialized: MaterializedTree,
    entries: list[ClassifiedEntry],
    profile_sha256: str,
) -> tuple[dict[str, Any], list[ClassifiedEntry]]:
    manifest_entries = []
    for entry in entries:
        value = asdict(entry)
        value["class"] = value.pop("class_name")
        value["blob_sha"] = value.pop("object_sha")
        manifest_entries.append(value)
    production = [entry for entry in entries if entry.class_name == "production"]
    excluded = [entry for entry in entries if entry.class_name != "production"]
    core: dict[str, Any] = {
        "schema": "scanner-manifest/v1",
        "repository": REPOSITORY,
        "candidate": {
            "commit_sha": commit,
            "tree_sha": tree,
            "tree_listing_sha256": tree_listing_sha256,
            "materialized_root_sha256": materialized.materialized_root_sha256,
        },
        "profile_id": PROFILE_ID,
        "profile_sha256": profile_sha256,
        "expected_universe_id": EXPECTED_UNIVERSE_ID,
        "expected_universe_sha256": digest_json(universe_definition()),
        "scope": "applicable" if production else "not_applicable",
        "scope_reason": None if production else "empty-production-universe-v1",
        "stage_policy_id": STAGE_POLICY_ID,
        "scope_kind": "full_census",
        "input_hash_mode": "tree_only",
        "entries": manifest_entries,
        "included": [
            {"path": entry.path, "class": "production", "reason": entry.reason}
            for entry in production
        ],
        "excluded": [
            {"path": entry.path, "class": entry.class_name, "reason": entry.reason}
            for entry in excluded
        ],
        "added": [],
        "deleted": [],
        "reclassified": [],
        "moves": [],
        "source_paths_sha256": _source_digest(entries),
    }
    core["sha256"] = digest_json(core)
    return core, entries


def _validate_finite_number(
    value: object,
    name: str,
    *,
    minimum: float | None = None,
    maximum: float | None = None,
) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise CensusError(f"native report {name} is not numeric")
    result = float(value)
    if not math.isfinite(result):
        raise CensusError(f"native report {name} is not finite")
    if minimum is not None and result < minimum:
        raise CensusError(f"native report {name} is below its minimum")
    if maximum is not None and result > maximum:
        raise CensusError(f"native report {name} is above its maximum")
    return result


def _positive_int(value: object, name: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise CensusError(f"native report {name} must be a positive integer")
    return value


def _nonnegative_int(value: object, name: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        raise CensusError(f"native report {name} must be a nonnegative integer")
    return value


def _native_relative_path(raw: object, snapshot: Path) -> str:
    if not isinstance(raw, str) or not raw:
        raise CensusError("native cluster member has no file path")
    value = raw.replace("\\", "/")
    if value.startswith("/"):
        candidate = Path(value).resolve()
        try:
            return _safe_path(candidate.relative_to(snapshot.resolve()).as_posix())
        except ValueError as exc:
            raise CensusError(
                "native cluster member escapes materialized root"
            ) from exc
    return _safe_path(value.removeprefix("./"))


def _native_document(raw: bytes) -> tuple[dict[str, Any], dict[str, Any], list[Any]]:
    try:
        document = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise CensusError(f"dupehound returned invalid JSON: {exc}") from exc
    if not isinstance(document, dict):
        raise CensusError("dupehound JSON result is not an object")
    if document.get("schema_version") != EXPECTED_SCHEMA_VERSION:
        raise CensusError("dupehound JSON schema drift")
    if "class_shapes" in document:
        raise CensusError("dupehound class-shape output is outside this profile")
    stats = document.get("stats")
    score = document.get("score")
    clusters = document.get("clusters")
    if (
        not isinstance(stats, dict)
        or not isinstance(score, dict)
        or not isinstance(clusters, list)
    ):
        raise CensusError("dupehound report is missing stats, score, or clusters")
    return stats, score, clusters


def _validate_native_stats(
    stats: dict[str, Any],
    score: dict[str, Any],
    production_count: int,
    expected_skip_counts: dict[str, int],
) -> None:
    required_stats = (
        "files",
        "total_lines",
        "significant_lines",
        "functions",
        "elapsed_ms",
        "skipped_generated",
        "skipped_minified",
        "skipped_non_utf8",
    )
    for key in required_stats:
        _nonnegative_int(stats.get(key), f"stats.{key}")
    if stats["files"] != production_count:
        raise CensusError(
            "dupehound stats.files does not equal the production manifest"
        )
    expected_generated = expected_skip_counts["generated"]
    expected_minified = expected_skip_counts["minified"]
    expected_non_utf8 = expected_skip_counts["invalid_encoding"]
    if stats["skipped_generated"] != expected_generated:
        raise CensusError("dupehound generated skip count disagrees with the manifest")
    if stats["skipped_minified"] != expected_minified:
        raise CensusError("dupehound minified skip count disagrees with the manifest")
    if stats["skipped_non_utf8"] != expected_non_utf8:
        raise CensusError("dupehound UTF-8 skip count disagrees with the manifest")
    _validate_finite_number(
        score.get("slop_percent"), "score.slop_percent", minimum=0.0
    )
    if not isinstance(score.get("grade"), str) or not score["grade"]:
        raise CensusError("dupehound score.grade is invalid")
    _nonnegative_int(score.get("deletable_lines"), "score.deletable_lines")


def _native_member(
    member: Any,
    *,
    cluster_index: int,
    member_index: int,
    snapshot: Path,
    production: dict[str, ClassifiedEntry],
) -> tuple[dict[str, Any], tuple[Any, ...], str]:
    if not isinstance(member, dict):
        raise CensusError(
            f"dupehound cluster {cluster_index} member {member_index} is not an object"
        )
    path = _native_relative_path(member.get("file"), snapshot)
    entry = production.get(path)
    if entry is None:
        raise CensusError(f"native cluster member is outside production join: {path}")
    name = member.get("name")
    if not isinstance(name, str) or not name:
        raise CensusError(
            f"dupehound cluster {cluster_index} member has no function name"
        )
    start_line = _positive_int(
        member.get("start_line"),
        f"clusters[{cluster_index}].members[{member_index}].start_line",
    )
    end_line = _positive_int(
        member.get("end_line"),
        f"clusters[{cluster_index}].members[{member_index}].end_line",
    )
    if end_line < start_line:
        raise CensusError("dupehound member line span is reversed")
    _positive_int(
        member.get("lines"), f"clusters[{cluster_index}].members[{member_index}].lines"
    )
    lines = member["lines"]
    _validate_finite_number(
        member.get("similarity"),
        f"clusters[{cluster_index}].members[{member_index}].similarity",
        minimum=0.0,
        maximum=1.0,
    )
    similarity = float(member["similarity"])
    representative = member.get("representative")
    if not isinstance(representative, bool):
        raise CensusError(
            f"clusters[{cluster_index}].members[{member_index}].representative "
            "is not boolean"
        )
    test = member.get("test")
    if not isinstance(test, bool):
        raise CensusError(
            f"clusters[{cluster_index}].members[{member_index}].test is not boolean"
        )
    if entry.language is None or entry.content_sha256 is None:
        raise CensusError(f"production member has no language/content digest: {path}")
    key = (path, name, start_line, end_line)
    normalized = {
        "path": path,
        "name": name,
        "start_line": start_line,
        "end_line": end_line,
        "content_sha256": entry.content_sha256,
        "language": entry.language,
        "lines": lines,
        "similarity": similarity,
        "representative": representative,
        "test": test,
    }
    return normalized, key, entry.language


def _native_cluster(
    cluster: Any,
    *,
    index: int,
    snapshot: Path,
    production: dict[str, ClassifiedEntry],
    cluster_ids: set[int],
) -> dict[str, Any]:
    if not isinstance(cluster, dict):
        raise CensusError(f"dupehound cluster {index} is not an object")
    cluster_id = _positive_int(cluster.get("id"), f"clusters[{index}].id")
    if cluster_id in cluster_ids:
        raise CensusError(f"dupehound cluster id is duplicated: {cluster_id!r}")
    cluster_ids.add(cluster_id)
    copies = _positive_int(cluster.get("copies"), f"clusters[{index}].copies")
    similarity = _validate_finite_number(
        cluster.get("similarity"),
        f"clusters[{index}].similarity",
        minimum=0.0,
        maximum=1.0,
    )
    deletable_lines = _nonnegative_int(
        cluster.get("deletable_lines"), f"clusters[{index}].deletable_lines"
    )
    test_only = cluster.get("test_only")
    if not isinstance(test_only, bool):
        raise CensusError(f"dupehound cluster {index} test_only is not boolean")
    members = cluster.get("members")
    if not isinstance(members, list) or len(members) != copies or not members:
        raise CensusError(f"dupehound cluster {index} has an invalid member count")
    normalized_members: list[dict[str, Any]] = []
    member_keys: set[tuple[Any, ...]] = set()
    languages: set[str] = set()
    for member_index, member in enumerate(members):
        normalized, key, language = _native_member(
            member,
            cluster_index=index,
            member_index=member_index,
            snapshot=snapshot,
            production=production,
        )
        if key in member_keys:
            raise CensusError("dupehound cluster contains a duplicate member")
        member_keys.add(key)
        languages.add(language)
        normalized_members.append(normalized)
    representatives = [
        member for member in normalized_members if member["representative"]
    ]
    if len(representatives) != 1:
        raise CensusError(
            f"dupehound cluster {index} must contain exactly one representative"
        )
    actual_test_only = all(member["test"] for member in normalized_members)
    if test_only != actual_test_only:
        raise CensusError(
            f"dupehound cluster {index} test_only disagrees with member test flags"
        )
    if len(languages) != 1:
        raise CensusError("dupehound returned a cross-language cluster")
    normalized_members.sort(
        key=lambda item: (
            item["path"],
            item["name"],
            item["start_line"],
            item["end_line"],
        )
    )
    language = next(iter(languages))
    production_members = [member for member in normalized_members if not member["test"]]
    test_member_count = len(normalized_members) - len(production_members)
    projected_representative = next(
        (member for member in production_members if member["representative"]),
        None,
    )
    if projected_representative is None and production_members:
        projected_representative = max(
            production_members,
            key=lambda member: (
                member["lines"],
                -member["start_line"],
                member["path"],
                member["name"],
            ),
        )
    production_deletable_lines = (
        sum(
            member["lines"]
            for member in production_members
            if member is not projected_representative
        )
        if len(production_members) >= 2
        else 0
    )
    finding_subject = {
        "repository": REPOSITORY,
        "candidate_tree_sha256": "",  # filled by the caller for stable IDs
        "language": language,
        "members": [
            {
                field: member[field]
                for field in (
                    "path",
                    "name",
                    "start_line",
                    "end_line",
                    "content_sha256",
                )
            }
            for member in production_members
        ],
    }
    return {
        "native_id": cluster_id,
        "copies": copies,
        "similarity": similarity,
        "deletable_lines": deletable_lines,
        "test_only": test_only,
        "language": language,
        "members": normalized_members,
        "production_members": production_members,
        "production_representative": projected_representative,
        "production_copies": len(production_members),
        "production_deletable_lines": production_deletable_lines,
        "test_member_count": test_member_count,
        "projection": (
            "product_debt" if len(production_members) >= 2 else "telemetry_only"
        ),
        "_finding_subject": finding_subject,
    }


def validate_native_report(
    raw: bytes,
    *,
    snapshot: Path,
    manifest_entries: list[ClassifiedEntry],
    expected_skip_counts: dict[str, int],
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    stats, score, clusters = _native_document(raw)
    production = {
        entry.path: entry
        for entry in manifest_entries
        if entry.class_name == "production"
    }
    _validate_native_stats(stats, score, len(production), expected_skip_counts)

    cluster_ids: set[object] = set()
    normalized_clusters: list[dict[str, Any]] = []
    for index, cluster in enumerate(clusters):
        normalized_clusters.append(
            _native_cluster(
                cluster,
                index=index,
                snapshot=snapshot,
                production=production,
                cluster_ids=cluster_ids,
            )
        )

    normalized_clusters.sort(
        key=lambda item: (
            item["language"],
            item["members"][0]["path"],
            item["members"][0]["start_line"],
            str(item["native_id"]),
        )
    )
    return {
        "stats": {
            "files": stats["files"],
            "total_lines": stats["total_lines"],
            "significant_lines": stats["significant_lines"],
            "functions": stats["functions"],
            "elapsed_ms": stats["elapsed_ms"],
            "skipped_generated": stats["skipped_generated"],
            "skipped_minified": stats["skipped_minified"],
            "skipped_non_utf8": stats["skipped_non_utf8"],
        },
        "score": {
            "slop_percent": float(score["slop_percent"]),
            "grade": score["grade"],
            "deletable_lines": score["deletable_lines"],
        },
        "clusters": normalized_clusters,
    }, []


def _native_skip_counts(entries: list[ClassifiedEntry]) -> dict[str, int]:
    return {
        "generated": sum(
            entry.reason.startswith("content.generated_") for entry in entries
        ),
        # Dupehound's walker filters oversize files before loading them, so
        # those entries have no native ``skipped_minified`` counter.  Content
        # minification is the only class represented by that counter.
        "minified": sum(entry.class_name == "minified" for entry in entries),
        "invalid_encoding": sum(
            entry.class_name == "invalid_encoding" for entry in entries
        ),
    }


def scan_command(
    executable: str, snapshot: Path, config: scanner_contract.ScannerContract
) -> list[str]:
    command = [
        executable,
        "scan",
        str(snapshot),
        "--json",
        "--all",
        "--threshold",
        str(config.dupehound_threshold),
        "--min-tokens",
        str(config.dupehound_min_tokens),
        "--exclude-tests",
        "--no-default-excludes",
    ]
    for pattern in profile_exclusions(config):
        command.extend(("--exclude", pattern))
    return command


def _finding_id(cluster: dict[str, Any], tree_listing_sha256: str) -> str:
    subject = copy.deepcopy(cluster["_finding_subject"])
    subject["candidate_tree_sha256"] = tree_listing_sha256
    return f"{ALGORITHM_ID}:{digest_json(subject)}"


def _make_findings(
    clusters: list[dict[str, Any]], tree_listing_sha256: str
) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []
    for cluster in clusters:
        members = cluster["production_members"]
        if len(members) < 2:
            continue
        representative = cluster["production_representative"] or members[0]
        finding_id = _finding_id(cluster, tree_listing_sha256)
        findings.append(
            {
                "id": finding_id,
                "path": representative["path"],
                "span": {
                    "start_line": representative["start_line"],
                    "end_line": representative["end_line"],
                },
                "raw_metric": {
                    "similarity": cluster["similarity"],
                    "copies": cluster["copies"],
                    "deletable_lines": cluster["deletable_lines"],
                    "native": {
                        "copies": cluster["copies"],
                        "deletable_lines": cluster["deletable_lines"],
                        "test_only": cluster["test_only"],
                    },
                    "production_projection": {
                        "copies": cluster["production_copies"],
                        "deletable_lines": cluster["production_deletable_lines"],
                        "test_member_count": cluster["test_member_count"],
                    },
                },
                "threshold_or_policy_id": THRESHOLD_POLICY_ID,
                "classification": "product_debt",
                "actionability": "advisory",
                "owner": "epistemic-graph-maintainers",
                "disposition": "advisory-clone-cluster",
                "cluster_id": cluster["native_id"],
                "language": cluster["language"],
                "members": members,
            }
        )
    findings.sort(
        key=lambda item: (item["id"], item["path"], item["span"]["start_line"])
    )
    return findings


def _public_native_report(normalized: dict[str, Any]) -> dict[str, Any]:
    """Drop only internal finding-ID assembly fields from the receipt."""

    report = copy.deepcopy(normalized)
    for cluster in report["clusters"]:
        cluster.pop("_finding_subject", None)
    return report


def _test_projection_metrics(clusters: list[dict[str, Any]]) -> dict[str, Any]:
    """Summarize native test telemetry and the auditable product projection."""

    projected = [cluster for cluster in clusters if cluster["production_copies"] >= 2]
    return {
        "policy_id": INLINE_TEST_PROJECTION_ID,
        "native": {
            "cluster_count": len(clusters),
            "extra_copies": sum(max(0, cluster["copies"] - 1) for cluster in clusters),
            "deletable_lines": sum(cluster["deletable_lines"] for cluster in clusters),
            "test_only_cluster_count": sum(
                cluster["test_only"] for cluster in clusters
            ),
            "clusters_with_test_members": sum(
                cluster["test_member_count"] > 0 for cluster in clusters
            ),
            "test_member_count": sum(
                cluster["test_member_count"] for cluster in clusters
            ),
        },
        "production": {
            "rule": "at_least_two_native_non_test_members",
            "cluster_count": len(projected),
            "extra_copies": sum(
                max(0, cluster["production_copies"] - 1) for cluster in projected
            ),
            "deletable_lines": sum(
                cluster["production_deletable_lines"] for cluster in projected
            ),
            "mixed_cluster_count": sum(
                cluster["test_member_count"] > 0 and cluster["production_copies"] > 0
                for cluster in clusters
            ),
            "single_production_member_cluster_count": sum(
                cluster["production_copies"] == 1 for cluster in clusters
            ),
            "test_only_cluster_count": sum(
                cluster["production_copies"] == 0 for cluster in clusters
            ),
        },
    }


def _base_envelope(
    *,
    run_id: str,
    started_at: str,
    profile: dict[str, Any],
    universe: dict[str, Any],
    stage_policy: dict[str, Any],
    raw_sha256: str,
    raw_ref: str,
    normalized_ref: str,
    commit: str | None,
    tree: str | None,
    tree_listing_sha256: str | None,
    manifest: dict[str, Any] | None,
    config_items: list[dict[str, str]],
    tool: dict[str, Any],
) -> dict[str, Any]:
    source_paths = list(manifest.get("included", [])) if manifest else []
    source_paths = sorted(source_paths, key=lambda item: item["path"].encode("utf-8"))
    source_digest = (
        _source_digest(
            [
                ClassifiedEntry(
                    item["path"], "", None, None, item["class"], item["reason"], None
                )
                for item in source_paths
            ]
        )
        if source_paths
        else digest_bytes(b"")
    )
    path_counts = _path_counts(
        [
            ClassifiedEntry(
                item["path"], "", None, None, item["class"], item["reason"], None
            )
            for item in (manifest.get("entries", []) if manifest else [])
        ]
    )
    candidate = {
        "kind": "commit",
        "commit": commit,
        "tree_id": tree,
        "tree_sha256": tree_listing_sha256,
        "index_sha256": None,
        "worktree_status": "unknown",
        "proof": {
            "method": "git_tree_listing_" + "v1",
            "manifest_matches": manifest is not None,
            "head_commit_matches": commit is not None,
            "candidate_tree_matches_index": None,
            "candidate_absent_deleted": True,
            "worktree_clean": None,
        },
    }
    evidence_manifest = manifest or {
        "schema": "scanner-manifest/v1",
        "scope": "not_applicable",
        "scope_reason": "census-could-not-start",
        "stage_policy_id": STAGE_POLICY_ID,
        "scope_kind": "full_census",
        "profile_id": PROFILE_ID,
        "expected_universe_id": EXPECTED_UNIVERSE_ID,
        "expected_universe_sha256": digest_json(universe),
        "included": [],
        "excluded": [],
        "added": [],
        "deleted": [],
        "reclassified": [],
        "moves": [],
        "entries": [],
        "sha256": digest_json(
            {"scope": "not_applicable", "reason": "census-could-not-start"}
        ),
    }
    return {
        "schema": "scanner-evidence/v2",
        "run": {
            "run_id": run_id,
            "started_at": started_at,
            "repository": REPOSITORY,
            "stage": "release",
            "stage_policy": {
                "id": STAGE_POLICY_ID,
                "sha256": digest_json(stage_policy),
            },
            "scope_kind": "full_census",
            "profile": {"id": PROFILE_ID, "sha256": digest_json(profile)},
            "expected_universe": {
                "id": EXPECTED_UNIVERSE_ID,
                "sha256": digest_json(universe),
            },
            "claim": "conformance_only",
            "optimization_scorecard": {"ref": None, "sha256": None},
            "instrument": "dupehound",
            "decision": "advisory",
            "comparison": {"mode": "census"},
            "base": None,
            "candidate": candidate,
            "config": config_items,
            "tool": tool,
            "manifest": evidence_manifest,
            "inputs": [],
        },
        "result": {
            "scope": evidence_manifest["scope"],
            "exit_class": "cannot_run",
            "blocking_findings": 0,
            "advisory_findings": 0,
            "findings_by_class": {
                "product_debt": 0,
                "parser_artifact": 0,
                "flat_exhaustive": 0,
                "generated": 0,
                "feature_omission": 0,
                "unknown": 0,
            },
            "artifact_counts": {
                "parser_artifact": 0,
                "flat_exhaustive": 0,
                "generated": 0,
                "feature_omission": 0,
                "unknown": 0,
            },
            "path_class_counts": path_counts,
            "metrics": [],
            "source_paths_sha256": source_digest,
        },
        "findings": [],
        "report": {
            "source_paths": source_paths,
            "raw_sha256": raw_sha256,
            "raw_ref": raw_ref,
            "normalized_sha256": None,
            "normalized_ref": normalized_ref,
            "normalization": "canonical",
            "normalization_reason": None,
        },
        "artifact_dispositions": [],
        "exceptions": [],
        "errors": [],
    }


def _finalize_normalized_digest(evidence: dict[str, Any]) -> None:
    subject = copy.deepcopy(evidence)
    subject["report"]["normalized_sha256"] = None
    for metric in subject["result"].get("metrics", []):
        metric["normalized_sha256"] = None
    normalized_sha256 = digest_json(subject)
    evidence["report"]["normalized_sha256"] = normalized_sha256
    for metric in evidence["result"].get("metrics", []):
        metric["normalized_sha256"] = normalized_sha256


def _write_bytes(path: Path, data: bytes) -> None:
    if path.is_symlink():
        raise CensusError(f"refusing to write through symlink: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def _write_json(path: Path, value: object) -> None:
    _write_bytes(path, canonical_json(value))


def _empty_tool() -> dict[str, Any]:
    return {
        "name": "dupehound",
        "version": "unknown",
        "artifact": {
            "kind": "binary_sha256",
            "digest": "unknown",
            "locator": "dupehound",
            "index_id": None,
            "lockfile_sha256": None,
            "trust_boundary": "runner-local-pinned-binary",
        },
        "invocation": [],
        "environment": {
            "RAYON_NUM_THREADS": str(THREAD_BOUND),
            "LC_ALL": "C",
            "LANG": "C",
        },
    }


def _source_identity(commit: str) -> tuple[bytes, bytes, bytes, list[dict[str, str]]]:
    adapter = _git_bytes(["show", f"{commit}:scripts/check_dupehound_census.py"])
    wrapper = _git_bytes(["show", f"{commit}:scripts/check_dupehound.py"])
    contract = _git_bytes(["show", f"{commit}:scripts/scanner_contract.py"])
    current = {
        "adapter": digest_bytes(Path(__file__).read_bytes()),
        "wrapper": digest_bytes(Path(check_dupehound.__file__).read_bytes()),
        "contract": digest_bytes(Path(scanner_contract.__file__).read_bytes()),
    }
    selected = {
        "adapter": digest_bytes(adapter),
        "wrapper": digest_bytes(wrapper),
        "contract": digest_bytes(contract),
    }
    if selected["adapter"] != current["adapter"]:
        raise CensusError("adapter source differs from the selected candidate tree")
    if selected["wrapper"] != current["wrapper"]:
        raise CensusError(
            "changed-source wrapper differs from the selected candidate tree"
        )
    if selected["contract"] != current["contract"]:
        raise CensusError("scanner contract differs from the selected candidate tree")
    config_items = [
        {
            "scope": "repo",
            "logical_path": "scripts/check_dupehound_census.py",
            "sha256": selected["adapter"],
            "source_id": "eg-dupehound-census-adapter",
        },
        {
            "scope": "repo",
            "logical_path": "scripts/check_dupehound.py",
            "sha256": selected["wrapper"],
            "source_id": "eg-dupehound-changed-wrapper",
        },
        {
            "scope": "repo",
            "logical_path": "scripts/scanner_contract.py",
            "sha256": selected["contract"],
            "source_id": "eg-scanner-contract-loader",
        },
    ]
    return adapter, wrapper, contract, config_items


def _candidate_contract(
    commit: str, pyproject: bytes
) -> scanner_contract.ScannerContract:
    with tempfile.NamedTemporaryFile(suffix="-pyproject.toml") as contract_file:
        contract_file.write(pyproject)
        contract_file.flush()
        try:
            return scanner_contract.load_contract(Path(contract_file.name))
        except scanner_contract.ScannerContractError as exc:
            raise CensusError(f"candidate scanner contract is invalid: {exc}") from exc


def _tool_context(
    config: scanner_contract.ScannerContract,
) -> tuple[str, dict[str, Any]]:
    try:
        executable = scanner_contract.resolve_binary("dupehound", "DUPEHOUND_BIN")
    except (FileNotFoundError, OSError) as exc:
        raise CensusError(str(exc), code="tool_missing") from exc
    try:
        scanner_contract.exact_version(
            executable, config.dupehound_version_output, cwd=ROOT
        )
    except RuntimeError as exc:
        raise CensusError(str(exc), code="tool_drift") from exc
    try:
        binary_digest = digest_bytes(Path(executable).read_bytes())
    except OSError as exc:
        raise CensusError(f"could not hash dupehound binary: {exc}") from exc
    tool = _empty_tool()
    tool["version"] = config.dupehound_version
    tool["artifact"] = {
        "kind": "binary_sha256",
        "digest": binary_digest,
        "locator": f"dupehound@{config.dupehound_version}",
        "index_id": None,
        "lockfile_sha256": None,
        "trust_boundary": "runner-local-pinned-binary",
    }
    return executable, tool


def _load_context(args: argparse.Namespace) -> CandidateContext:
    if args.repository != REPOSITORY:
        raise CensusError(f"unsupported repository profile: {args.repository!r}")
    if args.profile != PROFILE_ID:
        raise CensusError(f"unsupported dupehound profile: {args.profile!r}")
    commit, tree = _resolve_candidate(args.commit)
    entries = _tree_entries(commit)
    tree_listing_sha256 = tree_listing_digest(entries)
    pyproject = _git_bytes(["show", f"{commit}:pyproject.toml"])
    _adapter, wrapper, contract_source, config_items = _source_identity(commit)
    config_items.insert(
        0,
        {
            "scope": "repo",
            "logical_path": "pyproject.toml",
            "sha256": digest_bytes(pyproject),
            "source_id": "eg-scanner-contract",
        },
    )
    config = _candidate_contract(commit, pyproject)
    profile = profile_definition(config)
    return CandidateContext(
        commit=commit,
        tree=tree,
        entries=entries,
        tree_listing_sha256=tree_listing_sha256,
        config=config,
        profile=profile,
        profile_sha256=digest_json(profile),
        universe_sha256=digest_json(universe_definition()),
        stage_policy_sha256=digest_json(stage_policy_definition()),
        config_items=config_items,
        executable=None,
        tool=_empty_tool(),
    )


def _invoke_scan(command: list[str]) -> tuple[bytes, bytes]:
    environment = scanner_contract.sanitized_env(
        base={
            **os.environ,
            "RAYON_NUM_THREADS": str(THREAD_BOUND),
            "LC_ALL": "C",
            "LANG": "C",
        }
    )
    try:
        process = subprocess.run(
            command,
            cwd=str(ROOT),
            env=environment,
            capture_output=True,
            text=False,
            timeout=SCAN_TIMEOUT_SECONDS,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise CensusError(
            f"dupehound timed out after {SCAN_TIMEOUT_SECONDS}s",
            code="timeout",
            raw=exc.stdout or b"",
            stderr=exc.stderr or b"",
        ) from exc
    except (OSError, UnicodeError) as exc:
        raise CensusError(f"could not execute dupehound: {exc}") from exc
    raw = process.stdout or b""
    stderr = process.stderr or b""
    if process.returncode != 0:
        raise CensusError(
            f"dupehound exited {process.returncode}",
            code="native_exit",
            raw=raw,
            stderr=stderr,
        )
    return raw, stderr


def _validate_native_output(
    raw: bytes,
    *,
    stderr: bytes,
    snapshot: Path,
    manifest_entries: list[ClassifiedEntry],
    expected_skip_counts: dict[str, int],
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """Join a successful native process while preserving its output on drift."""

    try:
        return validate_native_report(
            raw,
            snapshot=snapshot,
            manifest_entries=manifest_entries,
            expected_skip_counts=expected_skip_counts,
        )
    except CensusError as exc:
        raise CensusError(
            str(exc),
            code="native_report_invalid",
            raw=exc.raw or raw,
            stderr=exc.stderr or stderr,
        ) from exc


def _success_evidence(
    *,
    context: CandidateContext,
    args: argparse.Namespace,
    run_id: str,
    started_at: str,
    classified: list[ClassifiedEntry],
    manifest: dict[str, Any],
    normalized: dict[str, Any] | None,
    raw: bytes,
) -> dict[str, Any]:
    raw_ref = str(Path(args.raw_output))
    normalized_ref = str(Path(args.normalized_output))
    clusters = normalized["clusters"] if normalized is not None else []
    projection = _test_projection_metrics(clusters)
    findings = _make_findings(clusters, context.tree_listing_sha256)
    evidence = _base_envelope(
        run_id=run_id,
        started_at=started_at,
        profile=context.profile,
        universe=universe_definition(),
        stage_policy=stage_policy_definition(),
        raw_sha256=digest_bytes(raw),
        raw_ref=raw_ref,
        normalized_ref=normalized_ref,
        commit=context.commit,
        tree=context.tree,
        tree_listing_sha256=context.tree_listing_sha256,
        manifest=manifest,
        config_items=context.config_items,
        tool=context.tool,
    )
    scope = manifest["scope"]
    metric_status = (
        "not_applicable"
        if scope == "not_applicable"
        else ("findings" if findings else "clean")
    )
    evidence["run"]["profile"]["sha256"] = context.profile_sha256
    evidence["run"]["expected_universe"]["sha256"] = context.universe_sha256
    evidence["run"]["stage_policy"]["sha256"] = context.stage_policy_sha256
    evidence["result"]["scope"] = scope
    evidence["result"]["exit_class"] = (
        "clean" if scope == "applicable" else "not_applicable"
    )
    evidence["result"]["advisory_findings"] = len(findings)
    evidence["result"]["findings_by_class"]["product_debt"] = len(findings)
    evidence["result"]["metrics"] = [
        {
            "id": ALGORITHM_ID,
            "stage_policy_id": STAGE_POLICY_ID,
            "scope_kind": "full_census",
            "profile_id": PROFILE_ID,
            "algorithm": ALGORITHM_ID,
            "source_id": "dupehound.native.scan",
            "universe_id": EXPECTED_UNIVERSE_ID,
            "universe_sha256": context.universe_sha256,
            "threshold_or_policy_id": THRESHOLD_POLICY_ID,
            "status": metric_status,
            "raw_sha256": digest_bytes(raw),
            "raw_ref": str(Path(args.raw_output)),
            "normalized_sha256": None,
            "normalized_ref": normalized_ref,
        }
    ]
    evidence["findings"] = findings
    native_report = (
        _public_native_report(normalized) if normalized is not None else None
    )
    if native_report is not None:
        native_report["test_projection"] = projection
    evidence["normalized"] = {
        "candidate": {
            "commit": context.commit,
            "tree_id": context.tree,
            "tree_listing_sha256": context.tree_listing_sha256,
            "materialized_root_sha256": manifest["candidate"][
                "materialized_root_sha256"
            ],
        },
        "profile_id": PROFILE_ID,
        "native": native_report,
        "production": {
            "file_count": sum(entry.class_name == "production" for entry in classified),
            "function_count": (
                normalized["stats"]["functions"] if normalized is not None else 0
            ),
            "function_count_scope": (
                "native_production_files_including_inline_test_members"
                if normalized is not None
                else "not_applicable"
            ),
            "cluster_count": projection["production"]["cluster_count"],
            "extra_copies": projection["production"]["extra_copies"],
            "deletable_lines": projection["production"]["deletable_lines"],
            "advisory_finding_count": len(findings),
            "not_applicable_count": int(scope == "not_applicable"),
            "native_scan_executed": normalized is not None,
            "test_projection": projection["production"],
        },
        "manifest": {
            "included_count": len(manifest["included"]),
            "excluded_count": len(manifest["excluded"]),
            "source_paths_sha256": manifest["source_paths_sha256"],
            "path_class_counts": _path_counts(classified),
        },
    }
    if normalized is None:
        evidence["report"]["normalization"] = "not_applicable"
        evidence["report"]["normalization_reason"] = "empty-production-universe-v1"
    _finalize_normalized_digest(evidence)
    return evidence


def _scan_context(
    context: CandidateContext,
    args: argparse.Namespace,
    run_id: str,
    started_at: str,
) -> tuple[dict[str, Any], bytes, bytes]:
    with materialize(context.commit, context.entries) as materialized:
        classified = classify_entries(
            context.entries, materialized.contents, context.config
        )
        manifest, _ = build_manifest(
            commit=context.commit,
            tree=context.tree,
            tree_listing_sha256=context.tree_listing_sha256,
            materialized=materialized,
            entries=classified,
            profile_sha256=context.profile_sha256,
        )
        context.manifest = manifest
        if manifest["scope"] == "not_applicable":
            return (
                _success_evidence(
                    context=context,
                    args=args,
                    run_id=run_id,
                    started_at=started_at,
                    classified=classified,
                    manifest=manifest,
                    normalized=None,
                    raw=b"",
                ),
                b"",
                b"",
            )
        context.executable, context.tool = _tool_context(context.config)
        assert context.executable is not None
        command = scan_command(context.executable, materialized.root, context.config)
        context.tool["invocation"] = list(command)
        raw, stderr = _invoke_scan(command)
        normalized, _unused = _validate_native_output(
            raw,
            stderr=stderr,
            snapshot=materialized.root,
            manifest_entries=classified,
            expected_skip_counts=_native_skip_counts(classified),
        )
        evidence = _success_evidence(
            context=context,
            args=args,
            run_id=run_id,
            started_at=started_at,
            classified=classified,
            manifest=manifest,
            normalized=normalized,
            raw=raw,
        )
        return evidence, raw, stderr


def _failure_evidence(
    *,
    context: CandidateContext | None,
    args: argparse.Namespace,
    run_id: str,
    started_at: str,
    raw: bytes,
    error: CensusError,
) -> dict[str, Any]:
    evidence = _base_envelope(
        run_id=run_id,
        started_at=started_at,
        profile=context.profile if context else {"id": PROFILE_ID},
        universe=universe_definition(),
        stage_policy=stage_policy_definition(),
        raw_sha256=digest_bytes(raw),
        raw_ref=str(Path(args.raw_output)),
        normalized_ref=str(Path(args.normalized_output)),
        commit=context.commit if context else None,
        tree=context.tree if context else None,
        tree_listing_sha256=context.tree_listing_sha256 if context else None,
        manifest=context.manifest if context else None,
        config_items=context.config_items if context else [],
        tool=context.tool if context else _empty_tool(),
    )
    evidence["errors"] = [{"code": error.code, "message": str(error)}]
    evidence["report"]["normalization"] = "none"
    evidence["report"]["normalization_reason"] = "cannot-run-before-normalization"
    evidence["report"]["normalized_sha256"] = None
    return evidence


def execute(args: argparse.Namespace) -> tuple[dict[str, Any], bytes, bytes]:
    started_at = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    run_id = str(uuid.uuid4())
    raw = b""
    stderr = b""
    context: CandidateContext | None = None
    try:
        context = _load_context(args)
        return _scan_context(context, args, run_id, started_at)
    except CensusError as exc:
        # Preserve the command output on a malformed or failing native run.
        raw = exc.raw or raw
        stderr = exc.stderr or stderr
        return (
            _failure_evidence(
                context=context,
                args=args,
                run_id=run_id,
                started_at=started_at,
                raw=raw,
                error=exc,
            ),
            raw,
            stderr,
        )


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository", default=REPOSITORY)
    parser.add_argument("--commit", default="HEAD")
    parser.add_argument("--profile", default=PROFILE_ID)
    parser.add_argument("--raw-output", required=True, type=Path)
    parser.add_argument("--normalized-output", required=True, type=Path)
    parser.add_argument("--stderr-output", type=Path)
    parser.add_argument("--manifest-output", type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    stderr_output = args.stderr_output or args.raw_output.with_suffix(
        args.raw_output.suffix + ".stderr"
    )
    try:
        evidence, raw, native_stderr = execute(args)
        _write_bytes(args.raw_output, raw)
        _write_bytes(stderr_output, native_stderr)
        _write_json(args.normalized_output, evidence)
        if args.manifest_output:
            _write_json(args.manifest_output, evidence["run"]["manifest"])
    except CensusError as exc:
        # Output-path failures are already a failed operation.  Keep the
        # message concise and do not print native stderr, which can contain
        # unrelated environment details.
        print(f"dupehound census: CANNOT RUN: {exc}", file=sys.stderr)
        return 2
    if evidence["result"]["exit_class"] == "cannot_run":
        error = evidence.get("errors", [{"message": "unknown census error"}])[0]
        print(f"dupehound census: CANNOT RUN: {error['message']}", file=sys.stderr)
        return 2
    print(
        "dupehound census: complete: "
        f"{evidence['result']['advisory_findings']} advisory cluster(s); "
        f"scope={evidence['result']['scope']}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
