//! Emit the generated Python client surface (`epistemic_graph/generated/`).
//!
//! One module per domain, each holding a pydantic v2 request model and a typed send
//! function per method the contract publishes to the `python` consumer profile. The
//! hand-written transport (`SyncEpistemicGraphClient`/`EpistemicGraphClient`, framing,
//! auth, pooling) is NOT generated and is untouched — these functions own only the
//! method identity, the request-shape validation, and the result decode.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use super::{normalize, schema, Artifact};
use crate::{ConsumerProfile, MethodDescriptor, PayloadShape, SchemaRef};

const HEADER: &str = "# @generated by `cargo run -p eg-capabilities --features contract --bin gen_contract`.\n# Source of truth: crates/eg-capabilities/src/domains/*.rs. Do NOT edit by hand.\n";

/// `AddNode` -> `add_node`. Collisions are asserted against in [`artifacts`].
fn snake_case(id: &str) -> String {
    let mut out = String::with_capacity(id.len() + 8);
    for (index, ch) in id.char_indices() {
        if ch.is_ascii_uppercase() && index > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_lowercase());
    }
    out
}

fn python_result_type(schema_ref: SchemaRef) -> &'static str {
    match schema_ref {
        SchemaRef::Payload(PayloadShape::Bool) => "bool",
        SchemaRef::Payload(PayloadShape::Count) => "int",
        SchemaRef::Payload(PayloadShape::Float) => "float",
        SchemaRef::Payload(PayloadShape::Text) => "str",
        SchemaRef::Payload(PayloadShape::Ids) => "list[str]",
        SchemaRef::Payload(PayloadShape::NodeList) => "list[tuple[str, Any]]",
        SchemaRef::Payload(PayloadShape::EdgeList) => "list[tuple[str, str, bytes]]",
        _ => "OpaqueResult",
    }
}

fn result_note(schema_ref: SchemaRef) -> String {
    match schema_ref {
        SchemaRef::Payload(shape) => format!(
            "typed ResultPayload::{} (contract/schemas/result.{}.json)",
            shape.as_str(),
            shape.as_str()
        ),
        SchemaRef::Opaque(kind) => {
            format!(
                "opaque ({}) - the contract declares no result schema",
                kind.as_str()
            )
        }
        SchemaRef::MethodVariant => "the method's own variant subschema".to_string(),
    }
}

/// Map one JSON Schema node to a Python annotation.
///
/// A `$ref` resolves to `Any`: the referenced wire DTOs are fully described in
/// `contract/schemas/method.request.json`, and emitting a nested pydantic model per DTO
/// is follow-on work this mapping makes visible rather than pretending to have done.
fn python_type(node: &serde_json::Value) -> String {
    if let Some(any_of) = node.get("anyOf").and_then(|v| v.as_array()) {
        return union_type(any_of);
    }
    match node.get("type").and_then(|v| v.as_str()) {
        Some("string") => "str".to_string(),
        Some("integer") => "int".to_string(),
        Some("number") => "float".to_string(),
        Some("boolean") => "bool".to_string(),
        Some("array") => array_type(node),
        Some("object") => object_type(node),
        Some("null") => "None".to_string(),
        _ => "Any".to_string(),
    }
}

fn union_type(any_of: &[serde_json::Value]) -> String {
    let mut parts: Vec<String> = Vec::new();
    for node in any_of {
        let part = python_type(node);
        if !parts.contains(&part) {
            parts.push(part);
        }
    }
    parts.join(" | ")
}

fn array_type(node: &serde_json::Value) -> String {
    let Some(items) = node.get("items") else {
        return "list[Any]".to_string();
    };
    if items.get("format").and_then(|v| v.as_str()) == Some("uint8") {
        return "bytes".to_string();
    }
    format!("list[{}]", python_type(items))
}

fn object_type(node: &serde_json::Value) -> String {
    match node.get("additionalProperties") {
        Some(inner) if inner.is_object() => format!("dict[str, {}]", python_type(inner)),
        _ => "dict[str, Any]".to_string(),
    }
}

/// `(field name, annotation, required)` for one method, from its request subschema.
fn request_fields(subschema: &serde_json::Value) -> Vec<(String, String, bool)> {
    let Some(params) = subschema.get("properties").and_then(|p| p.get("params")) else {
        return Vec::new();
    };
    let required: Vec<&str> = params
        .get("required")
        .and_then(|r| r.as_array())
        .map(|r| r.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default();
    let Some(properties) = params.get("properties").and_then(|p| p.as_object()) else {
        return Vec::new();
    };
    properties
        .iter()
        .map(|(name, node)| {
            let annotation = python_type(node);
            let is_required = required.contains(&name.as_str());
            (name.clone(), annotation, is_required)
        })
        .collect()
}

/// Python keywords a wire field name may collide with. A model field is then emitted
/// under a trailing-underscore name bound to the real wire key by a pydantic alias, so
/// the validated document still carries the exact field the engine deserializes.
const PYTHON_KEYWORDS: &[&str] = &[
    "and", "as", "assert", "async", "await", "break", "class", "continue", "def", "del", "elif",
    "else", "except", "False", "finally", "for", "from", "global", "if", "import", "in", "is",
    "lambda", "None", "nonlocal", "not", "or", "pass", "raise", "return", "True", "try", "while",
    "with", "yield",
];

fn is_python_keyword(name: &str) -> bool {
    PYTHON_KEYWORDS.contains(&name)
}

fn push_model(out: &mut String, id: &str, fields: &[(String, String, bool)]) {
    let _ = writeln!(out, "class {id}Request(BaseModel):");
    let _ = writeln!(
        out,
        "    \"\"\"Request body for {id} - contract/schemas/method.request.json#/methods/{id}.\"\"\""
    );
    out.push('\n');
    let _ = writeln!(out, "    model_config = ConfigDict(extra=\"forbid\")");
    if fields.is_empty() {
        let _ = writeln!(out, "\n    # Method::{id} carries no request fields.");
        return;
    }
    out.push('\n');
    for (name, annotation, required) in fields {
        if is_python_keyword(name) {
            let default = if *required { "..." } else { "None" };
            let optional = if *required { "" } else { " | None" };
            let _ = writeln!(
                out,
                "    {name}_: {annotation}{optional} = Field({default}, alias=\"{name}\")"
            );
        } else if *required {
            let _ = writeln!(out, "    {name}: {annotation}");
        } else {
            let _ = writeln!(out, "    {name}: {annotation} | None = None");
        }
    }
}

fn push_send(out: &mut String, d: &MethodDescriptor) {
    let id = d.id.as_str();
    let name = snake_case(id);
    let result = python_result_type(d.result_schema);
    let _ = writeln!(out, "async def send_{name}(");
    let _ = writeln!(out, "    client: Any,");
    let _ = writeln!(out, "    params: dict[str, Any] | None = None,");
    let _ = writeln!(out, "    graph: str | None = None,");
    let _ = writeln!(out, "    *,");
    let _ = writeln!(out, "    idempotency_key: str | None = None,");
    let _ = writeln!(out, ") -> {result}:");
    let _ = writeln!(
        out,
        "    \"\"\"{id} - {authz}, {durability:?}, replay {replay:?}.",
        authz = d.policy.authz_action,
        durability = d.policy.durability_domain,
        replay = d.replay_class,
    );
    out.push('\n');
    let _ = writeln!(out, "    Result: {}.", result_note(d.result_schema));
    let _ = writeln!(out, "    Errors: {}.", d.error_set.join(", "));
    let _ = writeln!(out, "    \"\"\"");
    let _ = writeln!(out, "    {id}Request.model_validate(params or {{}})");
    let _ = writeln!(out, "    payload = await client._send(");
    let _ = writeln!(out, "        \"{id}\",");
    out.push_str(
        "        params,\n        graph,\n        idempotency_key=idempotency_key,\n    )\n",
    );
    if d.result_schema.is_typed() {
        let _ = writeln!(out, "    return payload");
    } else {
        let _ = writeln!(out, "    return OpaqueResult(\"{id}\", payload)");
    }
}

fn domain_module(
    domain: &str,
    descriptors: &[MethodDescriptor],
    schemas: &serde_json::Value,
) -> String {
    let mut body = String::new();
    let empty = serde_json::json!({});
    for d in descriptors {
        let id = d.id.as_str();
        let subschema = schemas.get(id).unwrap_or(&empty);
        body.push_str("\n\n");
        push_model(&mut body, id, &request_fields(subschema));
        body.push_str("\n\n");
        push_send(&mut body, d);
    }
    // `Field` is imported only where an aliased keyword field actually uses it: an
    // unused import is a ruff F401 on every other module.
    let pydantic_import = if body.contains(" = Field(") {
        "from pydantic import BaseModel, ConfigDict, Field\n\n"
    } else {
        "from pydantic import BaseModel, ConfigDict\n\n"
    };
    let mut out = String::from(HEADER);
    let _ = writeln!(
        out,
        "\"\"\"Generated {domain} engine-contract client surface.\"\"\""
    );
    out.push_str("\nfrom __future__ import annotations\n\nfrom typing import Any\n\n");
    out.push_str(pydantic_import);
    out.push_str("from ._runtime import OpaqueResult\n");
    out.push_str(&body);
    out
}

fn runtime_module() -> String {
    let mut out = String::from(HEADER);
    out.push_str("\"\"\"Shared runtime for the generated engine-contract client.\n\n");
    out.push_str("OpaqueResult is what a method whose result the contract does NOT declare\n");
    out.push_str("returns: the raw decoded payload paired with the method id that produced it,\n");
    out.push_str(
        "so a caller can never mistake an undeclared body for a validated one.\n\"\"\"\n\n",
    );
    out.push_str("from __future__ import annotations\n\nfrom typing import Any, NamedTuple\n\n");
    out.push_str("from ._ids import METHOD_IDS\n\n\n");
    out.push_str("class OpaqueResult(NamedTuple):\n");
    out.push_str("    method: str\n    payload: Any\n\n\n");
    out.push_str("async def send_by_id(\n");
    out.push_str("    client: Any,\n    method: str,\n");
    out.push_str("    params: dict[str, Any] | None = None,\n");
    out.push_str("    graph: str | None = None,\n    *,\n");
    out.push_str("    idempotency_key: str | None = None,\n) -> Any:\n");
    out.push_str("    \"\"\"Send a method chosen at run time.\n\n");
    out.push_str(
        "    The hand-written helpers that pick a method from a parameter reach the wire\n",
    );
    out.push_str(
        "    through this one entry point, so no method id is spelled outside generated code.\n",
    );
    out.push_str("    \"\"\"\n");
    out.push_str("    if method not in METHOD_IDS:\n");
    out.push_str("        raise ValueError(f\"{method} is not an engine-contract method\")\n");
    out.push_str("    return await client._send(\n");
    out.push_str("        method,\n        params,\n        graph,\n        idempotency_key=idempotency_key,\n    )\n");
    out
}

fn ids_module(published: &[&str]) -> String {
    let mut out = String::from(HEADER);
    out.push_str(
        "\"\"\"Every method id the engine contract publishes to the python profile.\"\"\"\n\n",
    );
    out.push_str("METHOD_IDS = frozenset(\n    {\n");
    for id in published {
        let _ = writeln!(out, "        \"{id}\",");
    }
    out.push_str("    }\n)\n");
    out
}

fn init_module(modules: &[String], sends: &BTreeMap<String, String>) -> String {
    let mut out = String::from(HEADER);
    out.push_str("\"\"\"Generated engine-contract client surface (RF-RULING-003).\"\"\"\n\n");
    out.push_str("from . import (\n");
    for module in modules {
        let _ = writeln!(out, "    {module},");
    }
    out.push_str(")\n");
    out.push_str("from ._ids import METHOD_IDS\nfrom ._runtime import OpaqueResult, send_by_id\n");
    out.push_str("\n__all__ = [\n    \"METHOD_IDS\",\n    \"OpaqueResult\",\n    \"SEND_BY_METHOD\",\n    \"send_by_id\",\n");
    for module in modules {
        let _ = writeln!(out, "    \"{module}\",");
    }
    out.push_str(
        "]\n\n# method id -> the generated coroutine that sends it.\nSEND_BY_METHOD = {\n",
    );
    for (id, path) in sends {
        let _ = writeln!(out, "    \"{id}\": {path},");
    }
    out.push_str("}\n");
    out
}

/// `epistemic_graph/contract/__init__.py` -- the ONE entry point a consumer pins.
///
/// Deliberately stdlib-only (json + pathlib): a consumer must be able to read and verify
/// the receipt without importing the client, the transport, or pydantic.
fn package_contract_module() -> String {
    let mut out = String::from(HEADER);
    out.push_str("\"\"\"The shipped engine-contract receipt (RF-RULING-003).\n\n");
    out.push_str(
        "`RECEIPT` is the parsed `contract/receipt.json` of the exact engine build this\n",
    );
    out.push_str(
        "package was generated from. `RECEIPT_DIGEST` is the one value a consumer pins:\n",
    );
    out.push_str(
        "it folds the hand-written source digest together with every generated artifact's\n",
    );
    out.push_str(
        "digest, so a change to the wire registry, a schema, the generated client, or the\n",
    );
    out.push_str("hand-written transport all move it.\n\n");
    out.push_str(
        "Stdlib only on purpose -- verifying the contract must not require importing the\n",
    );
    out.push_str("client, the transport, or pydantic.\n\"\"\"\n\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("import json\nfrom pathlib import Path\nfrom typing import Any\n\n");
    out.push_str("__all__ = [\n    \"RECEIPT\",\n    \"RECEIPT_DIGEST\",\n    \"RECEIPT_PATH\",\n    \"ContractDigestMismatch\",\n    \"verify_receipt\",\n]\n\n");
    out.push_str("RECEIPT_PATH = Path(__file__).with_name(\"receipt.json\")\n\n");
    out.push_str(
        "RECEIPT: dict[str, Any] = json.loads(RECEIPT_PATH.read_text(encoding=\"utf-8\"))\n\n",
    );
    out.push_str("RECEIPT_DIGEST: str = RECEIPT[\"contract_digest\"]\n\n\n");
    out.push_str("class ContractDigestMismatch(RuntimeError):\n");
    out.push_str(
        "    \"\"\"The installed engine contract is not the one the caller pinned.\"\"\"\n\n\n",
    );
    out.push_str("def verify_receipt(expected_digest: str) -> None:\n");
    out.push_str("    \"\"\"Raise unless the installed contract is exactly `expected_digest`.\n\n");
    out.push_str(
        "    A consumer records one digest and calls this at import or start-up: a wheel\n",
    );
    out.push_str(
        "    built from a different engine contract then fails loudly instead of sending a\n",
    );
    out.push_str("    request the engine will reject.\n    \"\"\"\n");
    out.push_str("    if expected_digest != RECEIPT_DIGEST:\n");
    out.push_str("        raise ContractDigestMismatch(\n");
    out.push_str(
        "            f\"pinned engine contract {expected_digest} but this package ships \"\n",
    );
    out.push_str("            f\"{RECEIPT_DIGEST}\"\n");
    out.push_str("        )\n");
    out
}

/// Every generated Python file, in deterministic path order.
pub(super) fn artifacts() -> Vec<Artifact> {
    let document = schema::method_request_document();
    let empty = serde_json::json!({});
    let schemas = document.get("methods").cloned().unwrap_or(empty);
    let mut by_domain: BTreeMap<String, Vec<MethodDescriptor>> = BTreeMap::new();
    let mut published: Vec<&str> = Vec::new();
    let mut sends: BTreeMap<String, String> = BTreeMap::new();
    for d in crate::method_descriptors() {
        if !d.serves(ConsumerProfile::PythonClient) {
            continue;
        }
        published.push(d.id.as_str());
        sends.insert(
            d.id.as_str().to_string(),
            format!("{}.send_{}", d.domain, snake_case(d.id.as_str())),
        );
        by_domain.entry(d.domain.to_string()).or_default().push(d);
    }
    let names: std::collections::BTreeSet<&String> = sends.values().collect();
    assert_eq!(
        names.len(),
        published.len(),
        "two method ids collapsed onto one generated function name"
    );
    let mut out = vec![
        Artifact {
            path: "epistemic_graph/generated/_ids.py".to_string(),
            bytes: normalize(ids_module(&published)),
        },
        Artifact {
            path: "epistemic_graph/generated/_runtime.py".to_string(),
            bytes: normalize(runtime_module()),
        },
    ];
    let modules: Vec<String> = by_domain.keys().cloned().collect();
    for (domain, descriptors) in &by_domain {
        out.push(Artifact {
            path: format!("epistemic_graph/generated/{domain}.py"),
            bytes: normalize(domain_module(domain, descriptors, &schemas)),
        });
    }
    out.push(Artifact {
        path: "epistemic_graph/generated/__init__.py".to_string(),
        bytes: normalize(init_module(&modules, &sends)),
    });
    out.push(Artifact {
        path: "epistemic_graph/contract/__init__.py".to_string(),
        bytes: normalize(package_contract_module()),
    });
    out
}
