//! Emit the generated Python client surface (`epistemic_graph/generated/`).
//!
//! One module per domain, each holding a pydantic v2 request model and a typed send
//! function per method the contract publishes to the `python` consumer profile. The
//! hand-written transport (`SyncEpistemicGraphClient`/`EpistemicGraphClient`, framing,
//! auth, pooling) is NOT generated and is untouched — these functions own only the
//! method identity, the request-shape validation, and the result decode.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use super::python_render::{
    push_doc_field, push_error_bullets, push_method_schema, push_result_schema,
    push_send_mapping_entry,
};
use super::results::{Body, Catalog, Declared};
use super::{normalize, schema, Artifact};
use crate::{ConsumerProfile, MethodDescriptor};

mod digest;
mod dto;
mod package;
mod runtime;

use digest::digest_module;
#[cfg(test)]
use dto::CANONICAL_DIGEST_SPECS;
use dto::{dto_module, dto_python_type, DtoSurface, DTO_SURFACES};
use package::package_contract_module;
use runtime::runtime_module;

const HEADER: &str =
    "# @generated by `cargo run -p eg-capabilities --features contract --bin gen_contract`.\n\
# Source of truth:\n\
#   crates/eg-capabilities/src/domains/*.rs\n\
# Do not edit by hand.\n";

/// A typed adapter for one operation inside an existing tagged method.
///
/// This remains generator-owned: it does not mint a Method id or grow a
/// hand-written client facade. The declaration only identifies the already
/// served operation and the request/result DTOs its dynamic parent selects.
struct TypedOperationAdapter {
    method: &'static str,
    operation: &'static str,
    request_model: &'static str,
    result_model: &'static str,
}

const TYPED_OPERATION_ADAPTERS: &[TypedOperationAdapter] = &[TypedOperationAdapter {
    method: "AgentComponent",
    operation: "search",
    request_model: "AgentComponentSearchRequest",
    result_model: "AgentComponentSearchPage",
}];

/// `AddNode` -> `add_node`. Collisions are asserted against in [`artifacts`].
fn snake_case(id: &str) -> String {
    let mut out = String::with_capacity(id.len() + 8);
    for (index, ch) in id.char_indices() {
        if ch.is_ascii_uppercase() && index > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_lowercase());
    }
    out
}

/// The generated result checkers, in the order `_runtime` defines them.
const RESULT_CHECKERS: &[&str] = &[
    "expect_bool",
    "expect_count",
    "expect_edgelist",
    "expect_float",
    "expect_ids",
    "expect_nodelist",
    "expect_string",
];

/// `(Python annotation, runtime checker)` for a scalar encoding the client models.
fn scalar_result(encoding: &str) -> Option<(&'static str, &'static str)> {
    match encoding {
        "Bool" => Some(("bool", "expect_bool")),
        "Count" => Some(("int", "expect_count")),
        "Float" => Some(("float", "expect_float")),
        "String" => Some(("str", "expect_string")),
        "Ids" => Some(("list[str]", "expect_ids")),
        "NodeList" => Some(("list[tuple[str, Any]]", "expect_nodelist")),
        "EdgeList" => Some(("list[tuple[str, str, bytes]]", "expect_edgelist")),
        _ => None,
    }
}

/// The checked scalar a single-body, non-dynamic result decodes to, if the client models it.
fn modelled_scalar(declared: Option<&Declared>) -> Option<(&'static str, &'static str)> {
    let body = declared?.single()?;
    if body.dynamic.is_some() {
        return None;
    }
    scalar_result(body.encoding)
}

fn result_note(declared: Option<&Declared>) -> String {
    match declared.map(Declared::single) {
        None => "unclassified - the contract declares no result for this method".to_string(),
        Some(None) => "one declared body per request op".to_string(),
        Some(Some(body)) => body_note(body),
    }
}

/// The note for one declared body: its encoding, and its reason when caller-shaped.
fn body_note(body: &Body) -> String {
    match body.dynamic {
        Some(reason) => format!(
            "ResultPayload::{}, caller-shaped: {}",
            body.encoding,
            reason.summary()
        ),
        None => format!("ResultPayload::{}", body.encoding),
    }
}

/// Map one JSON Schema node to a Python annotation.
///
/// A `$ref` resolves to `Any` for legacy surfaces. Methods registered in
/// [`DTO_SURFACES`] use [`dto_python_type`] and the schema-driven nested-model
/// renderer instead.
fn python_type(node: &serde_json::Value) -> String {
    if let Some(any_of) = node.get("anyOf").and_then(|v| v.as_array()) {
        return union_type(any_of);
    }
    match node.get("type").and_then(|v| v.as_str()) {
        Some("string") => "str".to_string(),
        Some("integer") => "int".to_string(),
        Some("number") => "float".to_string(),
        Some("boolean") => "bool".to_string(),
        Some("array") => array_type(node),
        Some("object") => mapping_type(node, python_type),
        Some("null") => "None".to_string(),
        _ => "Any".to_string(),
    }
}

fn union_type(any_of: &[serde_json::Value]) -> String {
    let mut parts: Vec<String> = Vec::new();
    for node in any_of {
        let part = python_type(node);
        if !parts.contains(&part) {
            parts.push(part);
        }
    }
    parts.join(" | ")
}

fn array_type(node: &serde_json::Value) -> String {
    let Some(items) = node.get("items") else {
        return "list[Any]".to_string();
    };
    if items.get("format").and_then(|v| v.as_str()) == Some("uint8") {
        return "bytes".to_string();
    }
    format!("list[{}]", python_type(items))
}

fn mapping_type(node: &serde_json::Value, render: fn(&serde_json::Value) -> String) -> String {
    match node.get("additionalProperties") {
        Some(inner) if inner.is_object() => format!("dict[str, {}]", render(inner)),
        _ => "dict[str, Any]".to_string(),
    }
}

/// `(field name, annotation, required)` for one method, from its request subschema.
fn request_fields(id: &str, subschema: &serde_json::Value) -> Vec<(String, String, bool)> {
    let Some(params) = subschema.get("properties").and_then(|p| p.get("params")) else {
        return Vec::new();
    };
    let required: Vec<&str> = params
        .get("required")
        .and_then(|r| r.as_array())
        .map(|r| r.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default();
    let Some(properties) = params.get("properties").and_then(|p| p.as_object()) else {
        return Vec::new();
    };
    properties
        .iter()
        .map(|(name, node)| request_field(id, &required, name, node))
        .collect()
}

fn request_field(
    id: &str,
    required: &[&str],
    name: &str,
    node: &serde_json::Value,
) -> (String, String, bool) {
    let annotation = if DTO_SURFACES.iter().any(|surface| surface.method == id) {
        dto_python_type(node)
    } else {
        python_type(node)
    };
    (name.to_string(), annotation, required.contains(&name))
}

/// Python keywords a wire field name may collide with. A model field is then emitted
/// under a trailing-underscore name bound to the real wire key by a pydantic alias, so
/// the validated document still carries the exact field the engine deserializes.
const PYTHON_KEYWORDS: &[&str] = &[
    "and", "as", "assert", "async", "await", "break", "class", "continue", "def", "del", "elif",
    "else", "except", "False", "finally", "for", "from", "global", "if", "import", "in", "is",
    "lambda", "None", "nonlocal", "not", "or", "pass", "raise", "return", "True", "try", "while",
    "with", "yield",
];

fn is_python_keyword(name: &str) -> bool {
    PYTHON_KEYWORDS.contains(&name)
}

/// `T` -> `T | None`, but `T | None` -> `T | None`.
fn optional(annotation: &str) -> String {
    if annotation == "None" || annotation.ends_with(" | None") {
        return annotation.to_string();
    }
    format!("{annotation} | None")
}

fn push_model(out: &mut String, id: &str, fields: &[(String, String, bool)]) {
    let _ = writeln!(out, "class {id}Request(BaseModel):");
    let _ = writeln!(out, "    \"\"\"Validate one engine-contract request body.");
    out.push('\n');
    push_doc_field(out, "Method", id);
    push_method_schema(
        out,
        "Request schema",
        "contract/schemas/method.request.json",
        id,
    );
    let _ = writeln!(out, "    \"\"\"");
    out.push('\n');
    let _ = writeln!(out, "    model_config = ConfigDict(extra=\"forbid\")");
    if fields.is_empty() {
        let _ = writeln!(out, "\n    # Method::{id} carries no request fields.");
        return;
    }
    out.push('\n');
    for (name, annotation, required) in fields {
        if is_python_keyword(name) {
            let default = if *required { "..." } else { "None" };
            let declared = if *required {
                annotation.to_string()
            } else {
                optional(annotation)
            };
            let _ = writeln!(
                out,
                "    {name}_: {declared} = Field({default}, alias=\"{name}\")"
            );
        } else if *required {
            let _ = writeln!(out, "    {name}: {annotation}");
        } else {
            // An `anyOf` that already carries a null branch renders as `T | None`;
            // appending a second one is valid Python and ugly output.
            let _ = writeln!(out, "    {name}: {} = None", optional(annotation));
        }
    }
}

fn push_send(out: &mut String, d: &MethodDescriptor, declared: Option<&Declared>) {
    let id = d.id.as_str();
    let name = snake_case(id);
    let scalar = modelled_scalar(declared);
    let dto_result = dto_result_model(id);
    let result = dto_result.unwrap_or_else(|| scalar.map_or("OpaqueResult", |value| value.0));
    let _ = writeln!(out, "async def send_{name}(");
    let _ = writeln!(out, "    client: Any,");
    let _ = writeln!(out, "    params: dict[str, Any] | None = None,");
    let _ = writeln!(out, "    graph: str | None = None,");
    let _ = writeln!(out, "    *,");
    let _ = writeln!(out, "    idempotency_key: str | None = None,");
    let _ = writeln!(out, ") -> {result}:");
    let _ = writeln!(out, "    \"\"\"Send one engine-contract request.");
    out.push('\n');
    push_doc_field(out, "Method", id);
    push_doc_field(out, "Authorization", d.policy.authz_action);
    push_doc_field(
        out,
        "Durability",
        &format!("{:?}", d.policy.durability_domain),
    );
    push_doc_field(out, "Replay", &format!("{:?}", d.replay_class));
    push_doc_field(out, "Result", &result_note(declared));
    push_result_schema(out, d.domain, id, declared.is_some());
    push_error_bullets(out, d.error_set);
    let _ = writeln!(out, "    \"\"\"");
    let _ = writeln!(out, "    {id}Request.model_validate(params or {{}})");
    let _ = writeln!(out, "    payload = await client._send(");
    let _ = writeln!(out, "        \"{id}\",");
    out.push_str(
        "        params,\n        graph,\n        idempotency_key=idempotency_key,\n    )\n",
    );
    push_result_decode(out, id, dto_result, scalar);
}

fn dto_result_model(id: &str) -> Option<&'static str> {
    DTO_SURFACES
        .iter()
        .find(|surface| surface.method == id)
        .and_then(|surface| surface.result_model)
}

fn push_result_decode(
    out: &mut String,
    id: &str,
    dto_result: Option<&str>,
    scalar: Option<(&str, &str)>,
) {
    match (dto_result, scalar) {
        (Some(model), _) => {
            let _ = writeln!(out, "    return {model}.model_validate(payload)");
        }
        (None, Some((_, checker))) => {
            let _ = writeln!(out, "    return {checker}(\"{id}\", payload)");
        }
        (None, None) => {
            let _ = writeln!(out, "    return OpaqueResult(\"{id}\", payload)");
        }
    }
}

fn push_typed_operation_adapter(out: &mut String, adapter: &TypedOperationAdapter) {
    let method = adapter.method;
    let operation = adapter.operation;
    let function = format!("{}_{}", snake_case(method), operation);
    let request = adapter.request_model;
    let result = adapter.result_model;
    let _ = writeln!(out, "\n\nasync def send_{function}(");
    let _ = writeln!(out, "    client: Any,");
    let _ = writeln!(out, "    request: {request},");
    let _ = writeln!(out, "    graph: str | None = None,");
    let _ = writeln!(out, "    *,");
    let _ = writeln!(out, "    idempotency_key: str | None = None,");
    let _ = writeln!(out, ") -> {result}:");
    let _ = writeln!(
        out,
        "    \"\"\"Send typed {method}.{operation} through the existing {method} method.\"\"\""
    );
    let _ = writeln!(out, "    request = {request}.model_validate(request)");
    if method == "AgentComponent" && operation == "search" {
        out.push_str(
            "    if request.task is not None or request.capabilities or not request.kinds:\n",
        );
        out.push_str(
            "        raise ValueError(\n            \"AgentComponent.Search requires kinds and no task/capabilities\"\n        )\n",
        );
        out.push_str("    if request.limit is not None and not 1 <= request.limit <= 256:\n");
        out.push_str(
            "        raise ValueError(\"AgentComponent.Search limit must be in 1..=256\")\n",
        );
        out.push_str("    if request.cursor is not None and (\n        not request.cursor or len(request.cursor.encode(\"utf-8\")) > 16384\n    ):\n");
        out.push_str(
            "        raise ValueError(\"AgentComponent.Search cursor is outside its byte bound\")\n",
        );
    }
    let _ = writeln!(out, "    params = {{");
    let _ = writeln!(out, "        \"op\": {{");
    let _ = writeln!(out, "            \"op\": {operation:?},");
    let _ = writeln!(
        out,
        "            \"request\": request.model_dump(mode=\"json\", exclude_none=True),"
    );
    let _ = writeln!(out, "        }},");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "    payload = await client._send(");
    let _ = writeln!(out, "        {method:?},");
    out.push_str(
        "        params,\n        graph,\n        idempotency_key=idempotency_key,\n    )\n",
    );
    let _ = writeln!(out, "    return {result}.model_validate(payload)");
}

fn domain_module(
    domain: &str,
    descriptors: &[MethodDescriptor],
    schemas: &serde_json::Value,
    catalog: &Catalog,
) -> String {
    let body = domain_body(descriptors, schemas, catalog);
    let mut out = String::from(HEADER);
    let _ = writeln!(
        out,
        "\"\"\"Generated {domain} engine-contract client surface.\"\"\""
    );
    out.push_str("\nfrom __future__ import annotations\n\nfrom typing import Any\n\n");
    push_domain_imports(&mut out, descriptors, &body);
    out.push_str(&body);
    out
}

fn domain_body(
    descriptors: &[MethodDescriptor],
    schemas: &serde_json::Value,
    catalog: &Catalog,
) -> String {
    let mut body = String::new();
    let empty = serde_json::json!({});
    for d in descriptors {
        let id = d.id.as_str();
        let subschema = schemas.get(id).unwrap_or(&empty);
        body.push_str("\n\n");
        push_model(&mut body, id, &request_fields(id, subschema));
        body.push_str("\n\n");
        push_send(&mut body, d, catalog.methods.get(id));
        for adapter in TYPED_OPERATION_ADAPTERS
            .iter()
            .filter(|adapter| adapter.method == id)
        {
            push_typed_operation_adapter(&mut body, adapter);
        }
    }
    body
}

fn push_domain_imports(out: &mut String, descriptors: &[MethodDescriptor], body: &str) {
    // `Field` is imported only where an aliased keyword field actually uses it: an
    // unused import is a ruff F401 on every other module.
    let pydantic_import = if body.contains(" = Field(") {
        "from pydantic import BaseModel, ConfigDict, Field\n\n"
    } else {
        "from pydantic import BaseModel, ConfigDict\n\n"
    };
    out.push_str(pydantic_import);
    let mut imports: Vec<&str> = Vec::new();
    if body.contains("OpaqueResult(") {
        imports.push("OpaqueResult");
    }
    for name in RESULT_CHECKERS {
        if body.contains(&format!("{name}(")) {
            imports.push(name);
        }
    }
    imports.sort_unstable();
    // Always the exploded, magic-trailing-comma form: the one-line form exceeds the
    // formatter's width once a module uses several checkers, and a formatter that
    // rewrites generated output would fight `--check` forever.
    if !imports.is_empty() {
        out.push_str("from ._runtime import (\n");
        for name in &imports {
            let _ = writeln!(out, "    {name},");
        }
        out.push_str(")\n");
    }
    for surface in DTO_SURFACES {
        push_surface_import(out, descriptors, body, surface);
    }
}

fn push_surface_import(
    out: &mut String,
    descriptors: &[MethodDescriptor],
    body: &str,
    surface: &DtoSurface,
) {
    if !descriptors
        .iter()
        .any(|descriptor| descriptor.id.as_str() == surface.method)
    {
        return;
    }
    let mut roots: Vec<_> = surface
        .roots
        .iter()
        .filter(|root| body.contains(**root))
        .copied()
        .collect();
    roots.sort_unstable();
    if roots.is_empty() {
        return;
    }
    let _ = writeln!(out, "from .{} import (", surface.module);
    for root in roots {
        let _ = writeln!(out, "    {root},");
    }
    out.push_str(")\n");
}

fn ids_module(published: &[&str]) -> String {
    let mut out = String::from(HEADER);
    out.push_str(
        "\"\"\"Every method id the engine contract publishes to the python profile.\"\"\"\n\n",
    );
    out.push_str("METHOD_IDS = frozenset(\n    {\n");
    for id in published {
        let _ = writeln!(out, "        \"{id}\",");
    }
    out.push_str("    }\n)\n");
    out
}

fn init_module(modules: &[String], sends: &BTreeMap<String, String>) -> String {
    let mut out = String::from(HEADER);
    out.push_str("\"\"\"Generated engine-contract client surface (RF-RULING-003).\"\"\"\n\n");
    out.push_str("from . import (\n");
    for module in modules {
        let _ = writeln!(out, "    {module},");
    }
    out.push_str(")\n");
    out.push_str(
        "from ._ids import METHOD_IDS\nfrom ._runtime import (\n    ContractViolation,\n    OpaqueResult,\n    send_by_id,\n)\n",
    );
    out.push_str("\n__all__ = [\n    \"METHOD_IDS\",\n    \"ContractViolation\",\n    \"OpaqueResult\",\n    \"SEND_BY_METHOD\",\n    \"send_by_id\",\n");
    for module in modules {
        let _ = writeln!(out, "    \"{module}\",");
    }
    out.push_str(
        "]\n\n# method id -> the generated coroutine that sends it.\nSEND_BY_METHOD = {\n",
    );
    for (id, path) in sends {
        push_send_mapping_entry(&mut out, id, path);
    }
    out.push_str("}\n");
    out
}

fn merged_definitions(
    document: &serde_json::Value,
    catalog: &Catalog,
    result_domain: &str,
) -> serde_json::Map<String, serde_json::Value> {
    let mut definitions = document
        .get("$defs")
        .and_then(|value| value.as_object())
        .cloned()
        .unwrap_or_default();
    if let Some(domain_definitions) = catalog.definitions.get(result_domain) {
        for (name, definition) in domain_definitions {
            if let Some(previous) = definitions.insert(name.clone(), definition.clone()) {
                assert_eq!(
                    &previous, definition,
                    "request and result schemas disagree on definition {name}"
                );
            }
        }
    }
    definitions
}

/// Every generated Python file, in deterministic path order.
pub(super) fn artifacts(catalog: &Catalog) -> Vec<Artifact> {
    let document = schema::method_request_document();
    let empty = serde_json::json!({});
    let schemas = document.get("methods").cloned().unwrap_or(empty);
    let (by_domain, published, sends) = python_inventory();
    let mut out = base_artifacts(&published);
    let mut modules: Vec<String> = by_domain.keys().cloned().collect();
    push_domain_artifacts(&mut out, &by_domain, &schemas, catalog);
    push_dto_artifacts(&mut out, &mut modules, &document, catalog);
    push_package_artifacts(&mut out, &mut modules, &sends);
    out
}

fn python_inventory() -> (
    BTreeMap<String, Vec<MethodDescriptor>>,
    Vec<&'static str>,
    BTreeMap<String, String>,
) {
    let mut by_domain: BTreeMap<String, Vec<MethodDescriptor>> = BTreeMap::new();
    let mut published: Vec<&str> = Vec::new();
    let mut sends: BTreeMap<String, String> = BTreeMap::new();
    for d in crate::method_descriptors() {
        if !d.serves(ConsumerProfile::PythonClient) {
            continue;
        }
        published.push(d.id.as_str());
        sends.insert(
            d.id.as_str().to_string(),
            format!("{}.send_{}", d.domain, snake_case(d.id.as_str())),
        );
        by_domain.entry(d.domain.to_string()).or_default().push(d);
    }
    let names: std::collections::BTreeSet<&String> = sends.values().collect();
    assert_eq!(
        names.len(),
        published.len(),
        "two method ids collapsed onto one generated function name"
    );
    (by_domain, published, sends)
}

fn base_artifacts(published: &[&str]) -> Vec<Artifact> {
    vec![
        Artifact {
            path: "epistemic_graph/generated/_ids.py".to_string(),
            bytes: normalize(ids_module(published)),
        },
        Artifact {
            path: "epistemic_graph/generated/_runtime.py".to_string(),
            bytes: normalize(runtime_module()),
        },
        Artifact {
            path: "epistemic_graph/generated/digest.py".to_string(),
            bytes: normalize(digest_module()),
        },
    ]
}

fn push_domain_artifacts(
    out: &mut Vec<Artifact>,
    by_domain: &BTreeMap<String, Vec<MethodDescriptor>>,
    schemas: &serde_json::Value,
    catalog: &Catalog,
) {
    for (domain, descriptors) in by_domain {
        out.push(Artifact {
            path: format!("epistemic_graph/generated/{domain}.py"),
            bytes: normalize(domain_module(domain, descriptors, &schemas, catalog)),
        });
    }
}

fn push_dto_artifacts(
    out: &mut Vec<Artifact>,
    modules: &mut Vec<String>,
    document: &serde_json::Value,
    catalog: &Catalog,
) {
    for surface in DTO_SURFACES {
        let definitions = merged_definitions(&document, catalog, surface.result_domain);
        let missing: Vec<_> = surface
            .roots
            .iter()
            .filter(|root| !definitions.contains_key(**root))
            .copied()
            .collect();
        if !missing.is_empty() {
            assert!(
                !surface.required,
                "{} DTO roots are missing: {}",
                surface.method,
                missing.join(", ")
            );
            continue;
        }
        out.push(Artifact {
            path: format!("epistemic_graph/generated/{}.py", surface.module),
            bytes: normalize(dto_module(surface, &definitions)),
        });
        modules.push(surface.module.to_string());
    }
}

fn push_package_artifacts(
    out: &mut Vec<Artifact>,
    modules: &mut Vec<String>,
    sends: &BTreeMap<String, String>,
) {
    modules.push("digest".to_string());
    modules.sort();
    modules.dedup();
    out.push(Artifact {
        path: "epistemic_graph/generated/__init__.py".to_string(),
        bytes: normalize(init_module(&modules, &sends)),
    });
    out.push(Artifact {
        path: "epistemic_graph/contract/__init__.py".to_string(),
        bytes: normalize(package_contract_module()),
    });
}

#[cfg(test)]
mod tests;
