class EpistemicGraph:
    """High-performance compiled epistemic graph core."""

    def __init__(self) -> None: ...
    def add_node(self, node_id: str, properties_json: str) -> None: ...
    def add_edge(
        self, source_id: str, target_id: str, properties_json: str
    ) -> None: ...
    def remove_node(self, node_id: str) -> None: ...
    def remove_edge(self, source_id: str, target_id: str) -> None: ...
    def has_node(self, node_id: str) -> bool: ...
    def has_edge(self, source_id: str, target_id: str) -> bool: ...
    def get_nodes(self) -> list[tuple[str, str]]: ...
    def get_edges(self) -> list[tuple[str, str, str]]: ...

    # O(1) property lookups (Phase A1)
    def get_node_properties(self, node_id: str) -> str | None: ...
    def get_edge_properties(self, source_id: str, target_id: str) -> list[str]: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def topological_sort(self) -> list[str]: ...
    def find_cycle(self) -> list[str] | None: ...
    def get_shortest_path(self, source_id: str, target_id: str) -> list[str] | None: ...
    def get_blast_radius(self, node_id: str, max_depth: int) -> list[str]: ...
    def to_json(self) -> str: ...
    def from_json(self, json_str: str) -> None: ...
    def get_ledger(self) -> list[str]: ...
    def clear_ledger(self) -> None: ...
    def apply_ledger(self, transactions: list[str]) -> None: ...
    def parse_repository(self, root_path: str) -> None: ...
    def vf2_subgraph_match(self, pattern: EpistemicGraph) -> list[dict[str, str]]: ...

    # CONCEPT:KG-2.17 - Compiled Semantic Reasoner
    def run_datalog_reasoning(
        self,
        subclass_relations: list[tuple[str, str]],
        subproperty_relations: list[tuple[str, str]],
        symmetric_properties: list[str],
        transitive_properties: list[str],
        inverse_properties: list[tuple[str, str]],
    ) -> list[dict[str, str]]: ...

    # CONCEPT:KG-2.18 - High-Performance Quant FFI Engine
    def compute_rolling_mean(self, values: list[float], window: int) -> list[float]: ...
    def compute_rolling_std(self, values: list[float], window: int) -> list[float]: ...
    def compute_rolling_zscore(
        self, values: list[float], window: int
    ) -> list[float]: ...
    def compute_exponential_decay(
        self, values: list[float], alpha: float
    ) -> list[float]: ...
    def simulate_order_matching(
        self,
        bids: list[tuple[float, float]],
        asks: list[tuple[float, float]],
        orders: list[tuple[str, str, float, float]],
    ) -> list[dict[str, str]]: ...

    # Centrality (Phase A2)
    def compute_degree_centrality(self, node_id: str) -> float: ...
    def compute_betweenness_centrality(self) -> list[tuple[str, float]]: ...

    # Compaction (Phase A3)
    def compact_nodes_by_type(self, node_type: str, threshold: int) -> list[str]: ...

    # Graph Forking (Phase A4)
    def fork(self) -> EpistemicGraph: ...
    def diff_against(self, other: EpistemicGraph) -> str: ...
