# @generated by `cargo run -p eg-capabilities --features contract --bin gen_contract`.
# Source of truth:
#   crates/eg-capabilities/src/domains/*.rs
# Do not edit by hand.
"""Shared contract exceptions; importing this module never reads a receipt."""

__all__ = ["ContractDigestMismatch", "ContractArtifactMissing"]


class ContractDigestMismatch(RuntimeError):
    """The installed contract cannot be verified against the trusted pin."""


class ContractArtifactMissing(ContractDigestMismatch):
    """The installed receipt or one of its required contract files is missing."""
