"""Compile typed connector ontology declarations into an EG-owned Turtle pack.

The connector SDK transports the resulting document. EG owns its RDF syntax and
validates it again when a GraphSchema source is attached. Callers may supply
declarations; they may not supply Turtle fragments or unescaped RDF terms.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence

_LOCAL = re.compile(r"[A-Za-z_][A-Za-z0-9_-]*\Z")
_SOURCE = re.compile(r"[a-z0-9][a-z0-9._-]*\Z")
_DATATYPE = re.compile(r"xsd:[A-Za-z][A-Za-z0-9]*\Z")


def _local(value: object) -> str:
    if not isinstance(value, str) or _LOCAL.fullmatch(value) is None:
        raise ValueError("ontology pack term has an invalid local name")
    return value


def _label(value: object) -> str:
    if not isinstance(value, str) or not value or len(value) > 4096:
        raise ValueError("ontology pack label is invalid")
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def _datatype(value: object) -> str:
    if not isinstance(value, str) or _DATATYPE.fullmatch(value) is None:
        raise ValueError("ontology pack datatype must be an XSD prefixed name")
    return value


def _object_range(value: object) -> str:
    return "owl:Thing" if value == "owl:Thing" else f":{_local(value)}"


def compile_ontology_pack(
    *,
    source: str,
    classes: Sequence[Mapping[str, object]],
    object_properties: Sequence[Mapping[str, object]],
    datatype_properties: Sequence[Mapping[str, object]],
) -> str:
    """Return deterministic Turtle for typed class/property declarations.

    Unknown syntax and unsafe RDF names fail before any pack can be signed.
    Labels are escaped as Turtle literals; no caller-supplied RDF text is copied.
    """
    if not isinstance(source, str) or _SOURCE.fullmatch(source) is None:
        raise ValueError("ontology pack source must be a lowercase slug")
    lines = [
        "# GENERATED by epistemic_graph.ontology_pack from typed declarations.",
        "# Do not edit by hand; regenerate the connector pack.",
        "@prefix : <http://knuckles.team/kg#> .",
        "@prefix owl: <http://www.w3.org/2002/07/owl#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
        "",
        f"<http://knuckles.team/kg/{source}> a owl:Ontology ;",
        f'    rdfs:label "{_label(source)} Ontology (generated)" ;',
        "    owl:imports <http://knuckles.team/kg> .",
    ]
    for item in sorted(classes, key=lambda row: _local(row.get("local"))):
        local = _local(item.get("local"))
        lines.extend(
            (
                "",
                f":{local} a owl:Class ;",
                f'    rdfs:label "{_label(item.get("label"))}"',
            )
        )
        parent = item.get("parent")
        if parent is not None:
            lines[-1] += " ;"
            lines.append(f"    rdfs:subClassOf :{_local(parent)} .")
        else:
            lines[-1] += " ."
    for item in sorted(
        object_properties,
        key=lambda row: (_local(row.get("local")), str(row.get("domain") or "")),
    ):
        local = _local(item.get("local"))
        lines.extend(
            (
                "",
                f":{local} a owl:ObjectProperty ;",
                f'    rdfs:label "{_label(item.get("label"))}" ;',
            )
        )
        domain = item.get("domain")
        if domain is not None:
            lines.append(f"    rdfs:domain :{_local(domain)} ;")
        lines.append(f"    rdfs:range {_object_range(item.get('range'))} .")
    for item in sorted(datatype_properties, key=lambda row: _local(row.get("local"))):
        lines.extend(
            (
                "",
                f":{_local(item.get('local'))} a owl:DatatypeProperty ;",
                f'    rdfs:label "{_label(item.get("label"))}" ;',
                f"    rdfs:range {_datatype(item.get('range'))} .",
            )
        )
    return "\n".join(lines) + "\n"


def compile_ontology_proposal(
    *,
    classes: Sequence[Mapping[str, object]],
    object_properties: Sequence[Mapping[str, object]],
) -> str:
    """Render review-only typed declarations without attaching them to a schema.

    Concept IDs stay unresolved; a proposal must be reviewed and reserved before
    it can become a GraphSchema pack.
    """
    if not classes and not object_properties:
        return ""
    lines = [
        "# PROPOSED ontology extension — review + reserve concept ids before landing.",
        "# Generated by epistemic_graph.ontology_pack. Do NOT auto-merge.",
        "@prefix : <http://knuckles.team/kg#> .",
        "@prefix owl: <http://www.w3.org/2002/07/owl#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "",
    ]
    for item in classes:
        lines.extend(
            (
                "# CONCEPT:RESERVE-PENDING",
                f":{_local(item.get('local'))} a owl:Class ;",
                f'    rdfs:label "{_label(item.get("label"))}" ;',
            )
        )
        description = item.get("description")
        if description:
            lines.append(f'    rdfs:comment "{_label(description)}" ;')
        lines.extend(("    rdfs:subClassOf owl:Thing .", ""))
    for item in object_properties:
        lines.extend(
            (
                "# CONCEPT:RESERVE-PENDING",
                f":{_local(item.get('local'))} a owl:ObjectProperty ;",
                f'    rdfs:label "{_label(item.get("label"))}"',
            )
        )
        for predicate in ("domain", "range"):
            value = item.get(predicate)
            if value:
                lines[-1] += " ;"
                lines.append(f"    rdfs:{predicate} :{_local(value)}")
        lines[-1] += " ."
        lines.append("")
    return "\n".join(lines)


__all__ = ["compile_ontology_pack", "compile_ontology_proposal"]
