# @generated by `cargo run -p eg-capabilities --features contract --bin gen_contract`.
# Source of truth: crates/eg-capabilities/src/domains/*.rs. Do NOT edit by hand.
"""The shipped engine-contract receipt (RF-RULING-003).

`RECEIPT` is the parsed `contract/receipt.json` of the exact engine build this
package was generated from. `RECEIPT_DIGEST` is the one value a consumer pins:
it folds the hand-written source digest together with every generated artifact's
digest, so a change to the wire registry, a schema, the generated client, or the
hand-written transport all move it.

Stdlib only on purpose -- verifying the contract must not require importing the
client, the transport, or pydantic.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

__all__ = [
    "RECEIPT",
    "RECEIPT_DIGEST",
    "RECEIPT_PATH",
    "ContractDigestMismatch",
    "verify_receipt",
]

RECEIPT_PATH = Path(__file__).with_name("receipt.json")

RECEIPT: dict[str, Any] = json.loads(RECEIPT_PATH.read_text(encoding="utf-8"))

RECEIPT_DIGEST: str = RECEIPT["contract_digest"]


class ContractDigestMismatch(RuntimeError):
    """The installed engine contract is not the one the caller pinned."""


def verify_receipt(expected_digest: str) -> None:
    """Raise unless the installed contract is exactly `expected_digest`.

    A consumer records one digest and calls this at import or start-up: a wheel
    built from a different engine contract then fails loudly instead of sending a
    request the engine will reject.
    """
    if expected_digest != RECEIPT_DIGEST:
        raise ContractDigestMismatch(
            f"pinned engine contract {expected_digest} but this package ships "
            f"{RECEIPT_DIGEST}"
        )
